/**
 * Compositional racer fact corpus — Playboy-interview confessional energy.
 * Pools are expanded at module load; combinations exceed 10k gated facts.
 */

function pair(a: readonly string[], b: readonly string[], joiner: string): string[] {
  const out: string[] = [];
  for (const left of a) {
    for (const right of b) {
      out.push(`${left}${joiner}${right}`);
    }
  }
  return out;
}

function withArticle(nouns: readonly string[]): string[] {
  const out: string[] = [];
  for (const noun of nouns) {
    const article = /^[aeiou]/i.test(noun.trim()) ? "an" : "a";
    out.push(`${article} ${noun}`);
  }
  return out;
}

const SEASONS = [
  "summer",
  "winter",
  "spring",
  "fall",
  "August",
  "one humid July",
  "a rainy October",
  "the year he turned thirty",
  "six weeks in Maine",
  "a long weekend in Ohio",
] as const;

const YEARS = [
  "1998",
  "2003",
  "2007",
  "2011",
  "2014",
  "2019",
  "the Bush administration",
  "college",
  "his divorce year",
  "before smartphones existed",
] as const;

const ADJECTIVES = [
  "wooden",
  "forgotten",
  "laminated",
  "suspicious",
  "velvet",
  "government-issue",
  "unmarked",
  "ceremonial",
  "slightly haunted",
  "discount",
  "imported",
  "unlicensed",
  "retired",
  "borrowed",
  "misprinted",
  "autographed",
  "water-damaged",
  "church-grade",
  "motel-quality",
  "hand-painted",
  "expired",
  "commemorative",
  "unopened",
  "re-gifted",
  "unlabeled",
  "mirrored",
  "oversized",
  "pocket-sized",
  "fluorescent",
  "beige",
  "chrome",
  "plastic",
  "porcelain",
  "rubber",
  "silk",
  "wool",
  "leather",
  "cardboard",
  "crystal",
  "brass",
] as const;

const NOUNS = [
  "accordion",
  "mailbox",
  "mannequin head",
  "snow globe",
  "typewriter",
  "cassette deck",
  "meat thermometer",
  "garden gnome",
  "pool noodle",
  "desk fan",
  "coat rack",
  "birdcage",
  "lava lamp",
  "cheese grater",
  "trophy",
  "diploma frame",
  "alarm clock",
  "rotary phone",
  "punching bag",
  "floor lamp",
  "cookie jar",
  "wine opener",
  "shoe tree",
  "hat box",
  "record player",
  "film camera",
  "bowling pin",
  "hockey puck",
  "golf tee",
  "baseball card",
  "comic book",
  "road atlas",
  "phone book",
  "dictionary",
  "bible",
  "yearbook",
  "postcard",
  "receipt book",
  "checkbook",
  "passport photo",
  "mug shot",
  "parking ticket",
  "love letter",
  "breakup letter",
  "apology note",
  "grocery list",
  "recipe card",
  "business card",
  "library card",
  "hotel key",
  "room key",
] as const;

const MORE_NOUNS = [
  "ashtray",
  "blender",
  "calculator",
  "candelabra",
  "can opener",
  "coat hanger",
  "coffee mug",
  "compass",
  "corkboard",
  "curtain rod",
  "doorstop",
  "extension cord",
  "flashlight",
  "fly swatter",
  "frying pan",
  "hair dryer",
  "hammock",
  "hand mirror",
  "ice tray",
  "inhaler",
  "jewelry box",
  "kettle",
  "kitchen scale",
  "ladder",
  "lampshade",
  "lawn chair",
  "letter opener",
  "light bulb",
  "lint roller",
  "locket",
  "lunchbox",
  "magazine rack",
  "measuring cup",
  "metronome",
  "mixing bowl",
  "napkin ring",
  "nightlight",
  "paperweight",
  "pepper mill",
  "picture frame",
  "pillow",
  "pitcher",
  "plunger",
  "radio",
  "rain gauge",
  "rolling pin",
  "rubber duck",
  "salt lamp",
  "scissors",
  "sewing kit",
] as const;

const MORE_ADJECTIVES = [
  "haunted",
  "forbidden",
  "sacred",
  "cursed",
  "blessed",
  "illegal",
  "classified",
  "anonymous",
  "engraved",
  "monogrammed",
  "framed",
  "folded",
  "wrinkled",
  "polished",
  "rusted",
  "painted",
  "stained",
  "scented",
  "silent",
  "loud",
  "tiny",
  "giant",
  "invisible",
  "fake",
  "real",
  "stolen",
  "borrowed",
  "abandoned",
  "forgotten",
  "celebrated",
  "cursed-looking",
  "holy",
  "unholy",
  "suspiciously warm",
  "room-temperature",
  "deeply personal",
  "legally distinct",
  "emotionally loaded",
  "mildly threatening",
  "surprisingly heavy",
  "ethically complicated",
  "vintage-looking",
  "museum-quality",
  "gas-station",
  "church-basement",
  "divorce-era",
  "pre-war",
  "post-divorce",
  "uninsured",
] as const;

function buildObjectFragments(): string[] {
  return [
    ...withArticle(pair([...ADJECTIVES], [...NOUNS], " ")),
    ...withArticle(pair([...MORE_ADJECTIVES], [...NOUNS], " ")),
    ...withArticle(pair([...ADJECTIVES], [...MORE_NOUNS], " ")),
    ...withArticle(pair([...MORE_ADJECTIVES], [...MORE_NOUNS], " ")),
  ];
}

function buildBareObjectFragments(): string[] {
  return [
    ...pair([...ADJECTIVES], [...NOUNS], " "),
    ...pair([...MORE_ADJECTIVES], [...NOUNS], " "),
    ...pair([...ADJECTIVES], [...MORE_NOUNS], " "),
    ...pair([...MORE_ADJECTIVES], [...MORE_NOUNS], " "),
  ];
}

const OBJECTS = buildObjectFragments();

const CONTAINERS = [
  "a shoebox under the bed",
  "a filing cabinet he refuses to label",
  "the glove compartment",
  "a freezer bag",
  "a gym bag that smells like regret",
  "a bedside drawer",
  "a hall closet",
  "a storage unit in Nevada",
  "his mother's attic",
  "a locked briefcase",
  "a Tupperware he calls the vault",
  "the trunk of a car he no longer owns",
  "a desk he has not opened since 2012",
  "a coat pocket",
  "a suitcase that is never unpacked",
  "a toolbox in the garage",
  "a bread box",
  "a cereal box",
  "a hollowed-out book",
  "a false bottom in a suitcase",
] as const;

const BELIEFS = pair(
  [
    "the moon",
    "his neighbor",
    "grocery store lighting",
    "elevator music",
    "pigeons",
    "his own reflection",
    "the number seven",
    "Tuesdays",
    "hotel hallways",
    "voicemail",
    "automatic doors",
    "weather apps",
    "his childhood dentist",
    "the concept of brunch",
    "self-checkout machines",
    "crosswalk signals",
    "the post office",
    "his left knee",
    "ceiling fans",
    "garage door openers",
  ],
  [
    "is personally offended by him",
    "is sending him coded messages",
    "knows something about him",
    "is judging his posture",
    "is waiting for an apology",
    "remembers what he did",
    "is not what it claims to be",
    "is plotting quietly",
    "can hear his thoughts",
    "is disappointed in his choices",
    "is trying to warn him",
    "has been replaced",
    "is older than it looks",
    "is laughing at him",
    "is keeping a file on him",
  ],
  " "
);

const FOODS = withArticle([
  "scrambled eggs",
  "tuna salad",
  "gas station sushi",
  "room-temperature pasta",
  "airport sandwich",
  "hotel omelet",
  "buffet shrimp",
  "street hot dog",
  "leftover pizza",
  "canned soup",
  "gas station taquito",
  "airplane pretzels",
  "conference bagel",
  "wedding cake",
  "funeral potatoes",
  "church coffee",
  "diner pie",
  "drive-thru fries",
  "microwave burrito",
  "gas station banana",
]);

const BIZARRE_CONDITIONS = [
  "someone else orders first",
  "the lights are too bright",
  "a stranger is watching",
  "it is not raining",
  "he is wearing socks",
  "the radio is off",
  "he has already apologized to the table",
  "his phone is on silent",
  "the waiter makes eye contact",
  "he can see the kitchen",
  "the menu has no pictures",
  "the booth is not vinyl",
  "the salt shaker is full",
  "the ketchup is not expired",
  "he has written three sentences in his journal",
] as const;

const PROFESSIONS = [
  "dentists",
  "notaries",
  "mall security guards",
  "regional weathermen",
  "substitute teachers",
  "hotel clerks",
  "DMV employees",
  "tax preparers",
  "wedding DJs",
  "funeral directors",
  "life coaches",
  "psychics",
  "chiropractors",
  "dog groomers",
  "car wash attendants",
  "parking valets",
  "bartenders",
  "baristas",
  "librarians",
  "plumbers",
] as const;

const INCIDENTS = pair(
  ["incident", "situation", "misunderstanding", "mix-up", "episode", "afternoon", "phone call", "email"],
  [
    "with the revolving door",
    "involving a birthday cake",
    "at the hardware store",
    "during a thunderstorm",
    "on a cruise ship",
    "in a parking garage",
    "at Thanksgiving",
    "in a hotel hot tub",
    "with the wrong twin",
    "involving a parrot",
    "at jury duty",
    "during a power outage",
    "at a farmer's market",
    "in an IKEA",
    "with a bounce house",
  ],
  " "
);

const DOCUMENTS = [
  "unsent letters",
  "draft apologies",
  "numbered lists of regrets",
  "poems about elevators",
  "complaints to corporations",
  "thank-you notes he never mailed",
  "journal entries in the third person",
  "letters to his future self",
  "letters to his past self",
  "fake resumes",
  "real resumes he is ashamed of",
  "grocery lists with hidden meanings",
  "dream transcripts",
  "voice memos he cannot delete",
] as const;

const RECIPIENTS = [
  "his ex-wife's cousin",
  "a man he met once on a train",
  "his childhood barber",
  "a hotel concierge in Prague",
  "the author of a cookbook",
  "a regional news anchor",
  "his former landlord",
  "a woman who sold him a couch",
  "his therapist's answering machine",
  "a customer service department",
  "his younger brother",
  "a priest he does not know",
  "a park ranger",
  "a flight attendant",
  "his high school gym teacher",
] as const;

const MUNDANE_ACTIVITIES = [
  "folding laundry",
  "waiting in line at the post office",
  "watching a ceiling fan spin",
  "listening to hold music",
  "standing in a parking lot",
  "organizing his spice rack",
  "shoveling snow incorrectly",
  "reading the fine print",
  "sitting in a dentist's waiting room",
  "watching cargo ships online",
  "ironing one shirt",
  "cleaning his glasses",
  "checking the mail",
  "watering a plant he dislikes",
  "rewinding a cassette he no longer owns",
  "staring at a blank wall",
  "counting ceiling tiles",
  "waiting for paint to dry",
  "watching a loading bar",
  "sitting in a car with the engine off",
] as const;

const FICTIONAL_SPOUSES = [
  "a woman named Carol who may not exist",
  "a man he met at a bus stop",
  "a florist from Tacoma",
  "his cousin's friend Denise",
  "someone he only knows from a dream",
  "a flight attendant on a cancelled flight",
  "a voice on a wrong number",
  "a bartender in New Orleans",
  "a librarian who shushed him",
  "a woman who sold him a vacuum",
] as const;

const COLLECTIBLES = pair(
  ["vintage", "broken", "unopened", "signed", "misprinted", "foreign", "illegal-looking", "church-sale"],
  [
    "salt shakers",
    "hotel soaps",
    "boarding passes",
    "matchbooks",
    "pens from banks",
    "mini shampoo bottles",
    "sugar packets",
    "napkin holders",
    "menus",
    "coat check tickets",
    "parking stubs",
    "fortune cookie papers",
    "wine corks",
    "keychains",
    "magnets",
    "thimbles",
    "spoons",
    "ashtrays",
    "beer cans",
    "ticket stubs",
  ],
  " "
);

const CHAIN_STORES = [
  "Home Depot",
  "Target",
  "Walmart",
  "Costco",
  "Trader Joe's",
  "a Cracker Barrel",
  "a Joann Fabrics",
  "a Bed Bath & Beyond",
  "a Staples",
  "a Best Buy",
  "a PetSmart",
  "a Michaels",
  "a Kohl's",
  "a Sears that is still open",
  "a RadioShack",
] as const;

const MELODRAMAS = [
  "the lighting reminded him of childhood",
  "a song came on the speakers",
  "he saw someone who looked like his father",
  "the prices had changed",
  "he remembered a promise he broke",
  "the automatic doors hesitated",
  "a child stared at him too long",
  "he lost his coupon",
  "the sample lady ignored him",
  "he could not find the exit",
  "his cart had a wobbly wheel",
  "the intercom said his name wrong",
] as const;

const BODY_PARTS = [
  "left elbow",
  "right knee",
  "lower back",
  "pinkie toe",
  "left eyebrow",
  "shoulder blade",
  "jaw",
  "wrist",
  "big toe",
  "scalp",
  "belly button",
  "earlobe",
] as const;

const HISTORICAL_EVENTS = [
  "the moon landing",
  "Watergate",
  "the invention of the internet",
  "the fall of the Berlin Wall",
  "Y2K",
  "the first iPhone announcement",
  "the 2008 recession",
  "a blackout in 2003",
  "the day his parents met",
  "a house fire in 1987",
  "the Challenger disaster",
  "the O.J. trial",
  "the Monica Lewinsky news cycle",
  "the housing crash",
  "the day Napster died",
] as const;

const TRAVEL_SUPERSTITIONS = [
  "the hotel room number adds up to seven",
  "he has eaten eggs that morning",
  "his suitcase is on the left side of the bed",
  "he has called his mother",
  "the flight number contains no fours",
  "he is wearing his lucky socks",
  "the cab driver does not talk",
  "the minibar is empty",
  "the mirror is not facing the bed",
  "he has written his will in the notes app",
] as const;

const MINOR_AUTHORITIES = [
  "a crossing guard",
  "a HOA president",
  "a Little League umpire",
  "a camp counselor",
  "a substitute teacher",
  "a mall Santa",
  "a bouncer at a wedding",
  "a church usher",
  "a lifeguard",
  "a tour guide",
  "a museum docent",
  "a parking attendant",
  "a train conductor",
  "a ferry captain",
  "a zookeeper",
] as const;

const DREAM_SUBJECTS = [
  "a kitchen that keeps getting larger",
  "his teeth falling into a salad",
  "being late to a school he never attended",
  "a dog that speaks French",
  "an elevator that only goes sideways",
  "his childhood home with no doors",
  "a swimming pool full of soup",
  "a phone that will not stop ringing",
  "a highway with no exits",
  "his ex-wife's new husband teaching him yoga",
  "a grocery store where everything is free but sad",
  "a dentist who is also a cowboy",
] as const;

const HOARD_ITEMS = [
  "every birthday card since 2004",
  "plastic grocery bags",
  "takeout menus",
  "broken remote controls",
  "hotel pens",
  "rubber bands",
  "twist ties",
  "old phones",
  "expired coupons",
  "wine corks",
  "ticket stubs",
  "napkins from restaurants",
  "condiment packets",
  "single socks",
  "instruction manuals",
] as const;

const VENUES = [
  "a public library",
  "a community pool",
  "a minor league stadium",
  "a karaoke bar",
  "a yoga studio",
  "a farmer's market",
  "a bowling alley",
  "a bingo hall",
  "a Renaissance fair",
  "a wine tasting",
  "a comedy club",
  "a skating rink",
  "a dog park",
  "a botanical garden",
  "a courthouse",
] as const;

const PETTY_CRIMES = [
  "bringing outside food",
  "using the wrong bathroom",
  "filming without permission",
  "touching the exhibits",
  "clapping at the wrong time",
  "laughing during a eulogy",
  "wearing shoes indoors",
  "feeding the ducks the wrong bread",
  "sitting in reserved seating",
  "asking too many questions",
  "returning an item he did not buy",
  "whistling indoors",
] as const;

const HOUSEHOLD_OBJECTS = [
  "his toaster",
  "the refrigerator",
  "a floor lamp",
  "the thermostat",
  "his microwave",
  "the washing machine",
  "a smoke detector",
  "the garage door",
  "his desk chair",
  "the bathroom mirror",
  "a houseplant",
  "the vacuum cleaner",
] as const;

const SERVICE_WORKERS = [
  "private investigator",
  "personal chef",
  "professional organizer",
  "life coach",
  "psychic",
  "dog walker",
  "portrait photographer",
  "hypnotist",
  "mime",
  "magician",
  "tutor",
  "publicist",
] as const;

const AWKWARD_WORDS = [
  "moist",
  "pulchritude",
  "rural",
  "squirrel",
  "anemone",
  "colonel",
  "worcestershire",
  "phlegm",
  "croissant",
  "quinoa",
] as const;

const CITIES = [
  "Cleveland",
  "Tampa",
  "Albuquerque",
  "Boise",
  "Tulsa",
  "Syracuse",
  "Fresno",
  "Des Moines",
  "Baton Rouge",
  "Providence",
  "Omaha",
  "Madison",
  "Spokane",
  "Birmingham",
  "Toledo",
] as const;

const OBSOLETE_TECH = [
  "flip phone",
  "pager",
  "PalmPilot",
  "Discman",
  "VCR",
  "answering machine",
  "dial-up modem",
  "dot matrix printer",
  "fax machine",
  "car phone",
  "GPS unit",
  "digital camera",
] as const;

const PLACE_TYPES = [
  "within 500 feet of a Chuck E. Cheese",
  "inside any casino",
  "near a public fountain",
  "on the property of his ex-wife",
  "inside a Bath & Body Works",
  "within sight of a billboard he sued",
  "near a school zone",
  "inside a trampoline park",
  "on the grounds of a winery",
  "near a place he once proposed",
] as const;

const ABSURD_WAGERS = [
  "how long a man could hold his breath in a hot tub",
  "whether a squirrel would enter a sedan",
  "the exact minute of a thunderstorm",
  "how many napkins one person could steal",
  "whether a wedding DJ would play Whitney Houston",
  "the weight of a grocery store watermelon",
  "how many times a door would open in an hour",
  "whether a goose would chase a child",
  "the color of a stranger's socks",
  "how long hold music would last",
] as const;

const NICHE_OPINIONS = [
  "the correct way to load a dishwasher",
  "whether hot dogs are sandwiches",
  "the moral status of cruise ships",
  "how much cilantro is too much",
  "the best day to buy tires",
  "whether ghosts would use doors",
  "the ideal shower temperature",
  "how long leftovers are actually safe",
  "whether birds are trustworthy",
  "the proper way to fold a fitted sheet",
] as const;

const HARMLESS_THINGS = [
  "a balloon",
  "a mannequin",
  "a baby carrot",
  "a soap bubble",
  "a butterfly",
  "a cardboard cutout",
  "a foam finger",
  "a garden hose",
  "a piñata",
  "a parade float",
  "a mascot costume",
  "a foam pool noodle",
] as const;

const PERSONAL_ITEMS = [
  "his wallet",
  "his passport",
  "a family photo",
  "his wedding ring",
  "a lock of hair",
  "his diploma",
  "a hospital bracelet",
  "a lottery ticket",
  "a parking pass",
  "his car keys",
] as const;

const VISUAL_TRIGGERS = [
  "yellow car",
  "man in a fedora",
  "broken umbrella",
  "closed ice cream shop",
  "neon open sign",
  "plastic flamingo",
  "missing street sign",
  "dog wearing a sweater",
  "cloud shaped like a face",
  "revolving door",
] as const;

const SECRET_NOUNS = [
  "storage unit",
  "second phone",
  "safe deposit box",
  "journal",
  "voicemail password",
  "middle name",
  "real birthday",
  "first kiss",
  "bank account",
  "brother",
  "fear of dolphins",
  "tattoo",
] as const;

const GENRES = [
  "romance",
  "true crime",
  "self-help",
  "western",
  "cookbook",
  "poetry",
  "celebrity memoir",
  "conspiracy",
  "travel guide",
  "horror",
] as const;

const ODD_LOCATIONS = [
  "the bathtub",
  "a parked car",
  "a laundromat",
  "a hospital waiting room",
  "an airport gate",
  "a stairwell",
  "a storage unit",
  "a hotel bathroom",
  "a church pew",
  "a grocery store aisle",
] as const;

const PET_TYPES = [
  "hamster",
  "goldfish",
  "parakeet",
  "turtle",
  "ferret",
  "iguana",
  "rabbit",
  "hermit crab",
  "newt",
  "chinchilla",
] as const;

const CLOTHING = [
  "sandals",
  "a turtleneck",
  "cargo shorts",
  "a fedora",
  "white after Labor Day",
  "socks with sandals",
  "a leather jacket",
  "a scarf",
  "a tie",
  "a belt",
] as const;

const WEEKDAYS = [
  "Mondays",
  "Tuesdays",
  "Wednesdays",
  "Thursdays",
  "Fridays",
  "weekends",
  "his birthday",
  "tax day",
  "the first of the month",
  "any day it rains",
] as const;

const QUANTITIES = [
  "fourteen",
  "twenty-seven",
  "thirty-one",
  "an unreasonable number of",
  "exactly eleven",
  "too many",
  "a suspicious",
  "a ceremonial",
  "a tragic number of",
  "seven identical",
] as const;

const BARE_OBJECTS = buildBareObjectFragments();

const HANDWRITTEN_GEMS = [
  "once cried in a rental car because the radio played a song his mother hated.",
  "still owns a pager number he pays twelve dollars a month to keep.",
  "refuses to throw away a voicemail from a wrong number dated 2009.",
  "writes his name differently depending on which pen he carries.",
  "has never been photographed smiling with his teeth showing on purpose.",
  "keeps a laminated list of people who owe him apologies.",
  "once got into a shoving match with a man dressed as Benjamin Franklin.",
  "believes he can taste the difference between identical brands of bottled water.",
  "only feels handsome in hospital lighting.",
  "still sends a Christmas card to a landlord who is dead.",
  "owns a suit he has worn exactly once, to a funeral for a fish.",
  "will not enter a room if someone is already sitting in the good chair.",
  "has a favorite fire exit in every building he visits.",
  "once spent forty minutes arguing with a GPS about dignity.",
  "secretly rates every handshake he receives on a private scale.",
  "cannot hear the word \"moist\" without leaving the room.",
  "still sleeps with a fan on because silence sounds like judgment.",
  "has strong opinions about which grocery cart is the fastest.",
  "once fainted at a gender reveal because the color was wrong.",
  "writes thank-you notes to customer service reps who were rude to him.",
  "keeps a Ziploc bag of teeth that are not his.",
  "refuses to eat fruit that has been cut by someone else.",
  "calls his mother before every haircut like it is a medical procedure.",
  "once dated a woman because she owned the same microwave he had in college.",
  "believes mirrors are more honest in the morning.",
  "has a recurring nightmare about being trapped in a Pottery Barn.",
  "still mourns a plant he killed on purpose.",
  "will only buy toothpaste if the box is perfectly rectangular.",
  "once got banned from a YMCA for excessive whistling.",
  "owns a tie he has never worn but talks about like it is a pet.",
] as const;

const PROFESSIONAL_CONFESSIONS = pair(
  ["a therapist", "a priest", "a bartender", "a flight attendant", "a dentist", "a psychic"],
  [
    "that he is afraid of quiet rooms",
    "that he still loves someone he should not",
    "that he fakes half his opinions",
    "that he has never felt understood by a chair",
    "that he cries in rental cars",
    "that he counts ceiling tiles when nervous",
    "that he has never finished a book he started in public",
    "that he is waiting for an apology from a cloud",
    "that he once ate an entire cake alone",
    "that he does not know his own blood type",
  ],
  " "
);

const TEMPLATE_PATTERNS = [
  "once spent an entire {season} convinced that {belief}.",
  "still will not discuss what happened with {object} in {year}.",
  "refuses to eat {food} unless {bizarre_condition}.",
  "keeps {quantity} {bare_objects} inside {container}.",
  "has not trusted {profession} since the {incident}.",
  "secretly writes {documents} to {recipient}.",
  "only feels calm while {mundane_activity}.",
  "claims to have been married briefly to {fictional_spouse}.",
  "owns an alarming number of {collectibles}.",
  "once cried in {chain_store} because {melodrama}.",
  "believes his {body_part} remembers {historical_event}.",
  "will only travel if {travel_superstition}.",
  "still owes an apology to {minor_authority}.",
  "has a recurring dream about {dream_subject}.",
  "refuses to throw away {hoard_item}.",
  "got banned from {venue} for {petty_crime}.",
  "talks to {household_object} like it is a therapist.",
  "once hired a {service_worker} to follow him around for a week.",
  "cannot pronounce the word \"{awkward_word}\" after what happened in {city}.",
  "still uses {obsolete_tech} he bought in {year}.",
  "is legally prohibited from approaching {place_type}.",
  "won a small amount of money betting on {absurd_wager}.",
  "has strong feelings about {niche_opinion_topic}.",
  "once fainted at the sight of {harmless_thing}.",
  "stores {personal_item} in the freezer for luck.",
  "calls his mother every time he sees {visual_trigger}.",
  "has never told anyone about the {secret_noun}.",
  "reads {genre} novels exclusively in {odd_location}.",
  "still mourns a {pet_type} that died in {year}.",
  "refuses to wear {clothing} on {weekday}.",
  "once wrote a letter to {recipient} and mailed it to the wrong country.",
  "still checks the obituaries in case someone he dislikes has died.",
  "owns {object} and will not explain where he got it.",
  "once got lost inside {chain_store} for two hours on purpose.",
  "believes {belief} and has never apologized for it.",
  "will only shower if {bizarre_condition}.",
  "keeps a photo of {minor_authority} in {container}.",
  "has been asked to leave {venue} more than once.",
  "once fell asleep while {mundane_activity} and woke up crying.",
  "still has voicemails from {year} he cannot delete.",
  "refuses to sign anything in front of {profession}.",
  "once told a stranger on a plane his entire life story and regretted nothing.",
  "owns three copies of the same {genre} novel for emotional insurance.",
  "has never eaten {food} and considers that a personality trait.",
  "once got into an argument with {household_object} at three in the morning.",
  "still thinks about {dream_subject} at least once a week.",
  "will not visit {city} because of what happened with {awkward_word}.",
  "keeps {hoard_item} in {container} and calls it research.",
  "once paid a {service_worker} to lie to his family.",
  "believes he was replaced by {fictional_spouse} in a previous life.",
  "has a scar he blames on {historical_event}.",
  "once wore {clothing} to a funeral and was not asked to leave.",
  "still writes checks at {chain_store} out of spite.",
  "refuses to watch movies where {harmless_thing} appears on screen.",
  "once left {personal_item} in {odd_location} and never went back.",
  "has a folder labeled {secret_noun} on his computer desktop.",
  "only trusts {profession} who wear glasses.",
  "once cried while {mundane_activity} because the silence was too honest.",
  "still owns a ticket stub from {venue} he was too ashamed to use.",
  "will not throw away {object} because it witnessed something.",
  "once told {minor_authority} that he was sorry in a language he made up.",
  "believes {niche_opinion_topic} is a moral issue.",
  "has been married to the idea of moving to {city} for twelve years.",
  "once ate {food} in a bathroom stall and called it a spiritual experience.",
  "still flinches when he hears {awkward_word} in public.",
  "refuses to answer the door if {visual_trigger} is visible outside.",
  "once spent {year} trying to become friends with {minor_authority}.",
  "keeps a list of every {pet_type} he has ever met.",
  "will only buy groceries on {weekday}.",
  "once got a tattoo of {harmless_thing} and immediately regretted it.",
  "still believes {absurd_wager} was a good investment.",
  "has never forgiven himself for the {incident}.",
  "once wrote {documents} and burned them in a hotel sink.",
  "refuses to sit with his back to {household_object}.",
  "still uses {obsolete_tech} because he does not trust the cloud.",
  "once proposed to {recipient} in a {chain_store} parking lot.",
  "believes his {body_part} is older than the rest of him.",
  "has a recurring argument with {household_object} about temperature.",
  "once wore {clothing} inside out for an entire year as a protest.",
  "still thinks {fictional_spouse} might come back.",
  "will not eat at a restaurant if the menu mentions {food}.",
  "once got stuck in {odd_location} overnight and called it formative.",
  "keeps {collectibles} sorted by how guilty they make him feel.",
  "refuses to discuss {secret_noun} with anyone named Carol.",
  "once cried at {venue} because {melodrama}.",
  "still owns a suit tailored for {absurd_wager}.",
  "has never been to {city} but has strong opinions about it.",
  "once hired a {service_worker} to investigate {fictional_spouse}.",
  "believes {travel_superstition} saved his life once.",
  "will only open mail on {weekday}.",
  "once left {object} on a bus and chased it for six blocks.",
  "still has nightmares about {petty_crime} at {venue}.",
  "refuses to throw away {hoard_item} because his mother touched one once.",
  "once told {profession} he was fine and then fainted.",
  "keeps a candle lit for {pet_type} he never owned.",
  "will not use public restrooms unless {bizarre_condition}.",
  "once wrote his name on {personal_item} in three different inks.",
  "still mourns a {genre} novel he lent to someone in {year}.",
  "believes {chain_store} changed after he stopped shopping there.",
  "has a voice memo about {dream_subject} he is afraid to listen to.",
  "once got into a fistfight over {niche_opinion_topic}.",
  "refuses to sleep without {object} nearby.",
  "still sends birthday texts to {recipient} who never replies.",
  "once spent an entire {season} learning about {absurd_wager}.",
  "will not ride in an elevator with {harmless_thing}.",
  "keeps {documents} in {container} labeled \"tax stuff\".",
  "once lied to {minor_authority} about his age and never corrected it.",
  "believes he is allergic to {food} emotionally.",
  "has never trusted a man who owns {object}.",
  "once got a restraining order reversed by apologizing to {household_object}.",
  "still uses a password based on {historical_event}.",
  "refuses to watch the news if {visual_trigger} appears.",
  "once cried in {odd_location} because he missed {pet_type}.",
  "will only drink coffee from mugs that depict {harmless_thing}.",
  "keeps a drawer full of {collectibles} he calls his pension.",
  "once told {professional_confession}.",
] as const;

export const RACER_FACT_TEMPLATES = [
  ...TEMPLATE_PATTERNS,
  ...HANDWRITTEN_GEMS,
] as const;

let cachedPools: Record<string, readonly string[]> | null = null;

export function getRacerFactFragmentPools(): Record<string, readonly string[]> {
  if (cachedPools) return cachedPools;

  cachedPools = {
    season: SEASONS,
    year: YEARS,
    belief: BELIEFS,
    object: OBJECTS,
    bare_objects: BARE_OBJECTS,
    container: CONTAINERS,
    food: FOODS,
    bizarre_condition: BIZARRE_CONDITIONS,
    quantity: QUANTITIES,
    profession: PROFESSIONS,
    incident: INCIDENTS,
    documents: DOCUMENTS,
    recipient: RECIPIENTS,
    mundane_activity: MUNDANE_ACTIVITIES,
    fictional_spouse: FICTIONAL_SPOUSES,
    collectibles: COLLECTIBLES,
    chain_store: CHAIN_STORES,
    melodrama: MELODRAMAS,
    body_part: BODY_PARTS,
    historical_event: HISTORICAL_EVENTS,
    travel_superstition: TRAVEL_SUPERSTITIONS,
    minor_authority: MINOR_AUTHORITIES,
    dream_subject: DREAM_SUBJECTS,
    hoard_item: HOARD_ITEMS,
    venue: VENUES,
    petty_crime: PETTY_CRIMES,
    household_object: HOUSEHOLD_OBJECTS,
    service_worker: SERVICE_WORKERS,
    awkward_word: AWKWARD_WORDS,
    city: CITIES,
    obsolete_tech: withArticle([...OBSOLETE_TECH]),
    place_type: PLACE_TYPES,
    absurd_wager: ABSURD_WAGERS,
    niche_opinion_topic: NICHE_OPINIONS,
    harmless_thing: withArticle([...HARMLESS_THINGS]),
    personal_item: PERSONAL_ITEMS,
    visual_trigger: withArticle([...VISUAL_TRIGGERS]),
    secret_noun: SECRET_NOUNS,
    genre: GENRES,
    odd_location: ODD_LOCATIONS,
    pet_type: PET_TYPES,
    clothing: CLOTHING,
    weekday: WEEKDAYS,
    professional_confession: PROFESSIONAL_CONFESSIONS,
  };

  return cachedPools;
}

export function countRawRacerFactFragments(): number {
  return Object.values(getRacerFactFragmentPools()).reduce((sum, pool) => sum + pool.length, 0);
}
