/** Large recap phrase pools — imported by recap-phrases.ts */

export const RECAP_OPENERS = [
  "belongs in the permanent highlight reel",
  "will be talked about in the pits for years",
  "delivered absolute carnage from wire to wire",
  "was not a race — it was a survival test",
  "refused to behave like a normal sporting event",
  "felt less like a race and more like a reckoning",
  "left the standings looking like a crime scene",
  "had no interest in being polite",
  "turned the leaderboard into a rotating door",
  "played out like a slow-motion pileup in the sun",
  "was the kind of day that breaks group chats",
  "refused to give anyone a comfortable lap",
  "unspooled like a fever dream with points attached",
  "had chaos hiding in every quarter-hour",
  "treated mercy like a foreign concept",
  "kept finding new ways to humiliate the field",
  "read like a warning label for future racers",
  "was pure scoreboard violence from start to finish",
  "made the broadcast booth run out of synonyms",
  "had the energy of a bar fight with spreadsheets",
  "refused to settle into any predictable rhythm",
  "felt like watching eight people lose a bet with physics",
  "turned routine ticks into genuine emergencies",
  "was an all-day argument about who deserved P1",
  "delivered more plot twists than the field could handle",
  "looked calm on the clock and feral on the board",
  "was not interested in your narrative expectations",
  "unfolded like a highlight package nobody asked for",
  "kept punishing anyone who looked comfortable",
  "had the rhythm of a race that hated everyone equally",
  "played like a grudge match wearing a league jersey",
  "turned every quiet stretch into a setup for disaster",
  "was twenty-four hours of scoreboard malpractice",
  "felt like the standings were being edited in real time",
  "refused to let a single racer feel safe",
  "had the tone of a documentary about hubris",
  "was a masterclass in controlled panic",
  "kept answering calm with catastrophe",
  "looked innocent until the first real surge hit",
  "was the sort of race that ages racers overnight",
  "treated the leaderboard like a suggestion board",
  "had more reversals than a courtroom drama",
  "felt like the points were being handed out by dice",
  "was ugly, loud, and completely unforgettable",
  "turned patience into a losing strategy",
  "had the broadcast energy of a weather emergency",
  "refused to end the way anyone predicted",
  "was a full-contact lesson in scoreboard humility",
  "left everyone with a story and a grudge",
] as const;

export const RECAP_OPENING_FRAME_PHRASES = [
  "Race {n} {opener}.",
  "Race {n} {opener} — the scoreboard backed it up.",
  "By the end, Race {n} {opener}.",
  "If you only read the standings, Race {n} {opener}.",
  "On paper it was Race {n}; in practice it {opener}.",
  "Race {n} did not ease into anything — it {opener}.",
  "The recap writes itself: Race {n} {opener}.",
  "Twenty-four hours later, Race {n} {opener}.",
  "Nobody needed a second look — Race {n} {opener}.",
  "From the first tick to the last, Race {n} {opener}.",
  "The field went in hoping for calm; Race {n} {opener}.",
  "Call it what you want — Race {n} {opener}.",
  "However you score it, Race {n} {opener}.",
  "Race {n} was billed as routine and instead {opener}.",
  "The broadcast kept calling it Race {n}; the board said it {opener}.",
  "In the pits they will say Race {n} {opener}.",
  "Race {n} is over, and it {opener}.",
  "When the points locked, Race {n} {opener}.",
  "There is no gentle read on Race {n} — it {opener}.",
  "Race {n} finished the way it started: it {opener}.",
] as const;

export const RECAP_WIN_PHRASES = [
  "{winner} seized the win at {score} points",
  "{winner} took the race at {score} points",
  "{winner} crossed first at {score} points",
  "{winner} finished on top with {score} points",
  "{winner} claimed the checkered flag at {score} points",
  "{winner} held the line and won at {score} points",
  "{winner} got the last laugh at {score} points",
  "{winner} stood tallest at {score} points",
  "{winner} walked away with the win at {score} points",
  "{winner} earned the top spot at {score} points",
  "{winner} finished ahead of the field at {score} points",
  "{winner} took P1 at {score} points",
  "{winner} won the day at {score} points",
  "{winner} closed it out at {score} points",
  "{winner} survived the chaos and won at {score} points",
  "{winner} outlasted everyone at {score} points",
  "{winner} finished first at {score} points",
  "{winner} grabbed the win at {score} points",
  "{winner} ended the race in front at {score} points",
  "{winner} took the crown at {score} points",
  "{winner} got the final word at {score} points",
  "{winner} owned the finish at {score} points",
  "{winner} punched through at {score} points",
  "{winner} held off the field at {score} points",
  "{winner} finished clear at {score} points",
  "{winner} took the flag at {score} points",
  "{winner} won with {score} points on the board",
  "{winner} left no doubt at {score} points",
  "{winner} finished in command at {score} points",
  "{winner} took the race home at {score} points",
  "{winner} got the win at {score} points",
  "{winner} stood on top at {score} points",
  "{winner} finished strongest at {score} points",
  "{winner} took the points crown at {score} points",
  "{winner} ended up alone in front at {score} points",
  "{winner} won the scoreboard battle at {score} points",
  "{winner} finished with the lead at {score} points",
  "{winner} took the top step at {score} points",
  "{winner} closed the door at {score} points",
  "{winner} won after twenty-four hours at {score} points",
] as const;

export const RECAP_MARGIN_PHRASES = [
  ", {margin} clear of {runnerUp} in {rank}",
  ", beating {runnerUp} by {margin} for {rank}",
  ", {margin} ahead of {runnerUp} in {rank}",
  ", finishing {margin} up on {runnerUp} in {rank}",
  ", holding a {margin}-point edge on {runnerUp} in {rank}",
  ", with {margin} separating them from {runnerUp} in {rank}",
  ", {margin} better than {runnerUp} in {rank}",
  ", edging {runnerUp} by {margin} for {rank}",
  ", leaving {runnerUp} {margin} back in {rank}",
  ", ahead of {runnerUp} by {margin} for {rank}",
  ", with {runnerUp} {margin} behind in {rank}",
  ", winning the gap battle by {margin} over {runnerUp} in {rank}",
  ", {margin} to the good over {runnerUp} in {rank}",
  ", separating from {runnerUp} by {margin} in {rank}",
  ", outpointing {runnerUp} by {margin} for {rank}",
  ", taking {rank} by {margin} over {runnerUp}",
  ", finishing {margin} clear of {runnerUp} for {rank}",
  ", with a {margin}-point cushion on {runnerUp} in {rank}",
  ", denying {runnerUp} by {margin} in {rank}",
  ", holding off {runnerUp} by {margin} for {rank}",
  ", {margin} in front of {runnerUp} in {rank}",
  ", beating {runnerUp} to {rank} by {margin}",
  ", leaving only {margin} between them and {runnerUp} in {rank}",
  ", taking the runner-up spot battle by {margin} over {runnerUp}",
  ", with {margin} separating first from {runnerUp} in {rank}",
  ", winning by {margin} over {runnerUp} in {rank}",
  ", finishing with {margin} on {runnerUp} in {rank}",
  ", ahead by {margin} with {runnerUp} in {rank}",
  ", holding the line {margin} clear of {runnerUp} in {rank}",
  ", taking the win by {margin} from {runnerUp} in {rank}",
] as const;

export const RECAP_LAST_PHRASES = [
  "{loser} finished last at {score} and was eliminated to holding.",
  "{loser} brought up the rear at {score} and got sent to holding.",
  "{loser} ended the race at {score} and was eliminated to holding.",
  "{loser} landed last at {score} and got eliminated to holding.",
  "{loser} closed the day at {score} and was sent to holding.",
  "{loser} finished at the back at {score} and was eliminated to holding.",
  "{loser} took last at {score} and got moved to holding.",
  "{loser} wound up last at {score} and was eliminated to holding.",
  "{loser} finished bottom at {score} and got sent to holding.",
  "{loser} ended last at {score} and was eliminated to holding.",
  "{loser} finished in last at {score} and got eliminated to holding.",
  "{loser} came home last at {score} and was sent to holding.",
  "{loser} finished dead last at {score} and was eliminated to holding.",
  "{loser} took the rear at {score} and got sent to holding.",
  "{loser} ended at the back at {score} and was eliminated to holding.",
  "{loser} finished last on {score} and got eliminated to holding.",
  "{loser} landed at the bottom at {score} and was sent to holding.",
  "{loser} closed out last at {score} and was eliminated to holding.",
  "{loser} finished in the basement at {score} and got sent to holding.",
  "{loser} ended the day last at {score} and was eliminated to holding.",
  "{loser} took the last spot at {score} and got sent to holding.",
  "{loser} finished behind everyone at {score} and was eliminated to holding.",
  "{loser} wound up at the back at {score} and got sent to holding.",
  "{loser} ended in last place at {score} and was eliminated to holding.",
  "{loser} finished last with {score} and got sent to holding.",
  "{loser} brought up the back at {score} and was eliminated to holding.",
  "{loser} closed last at {score} and got eliminated to holding.",
  "{loser} finished at {score} in last and was sent to holding.",
  "{loser} ended on the bottom at {score} and was eliminated to holding.",
  "{loser} took the cellar at {score} and got sent to holding.",
] as const;

export const RECAP_WEATHER_PHRASES = [
  "the sky went wild — {total} weather bursts",
  "Mother Nature unloaded {total} weather bursts",
  "the elements hit {total} times",
  "the weather turned hostile {total} separate times",
  "the field got punished by weather {total} times",
  "the broadcast kept cutting to sky shots — {total} weather bursts",
  "the race got interrupted by the elements {total} times",
  "the clouds had opinions — {total} weather bursts",
  "the weather desk stayed busy with {total} bursts",
  "the field fought the sky {total} times",
  "the elements showed up {total} separate times",
  "the race got hit by weather {total} times",
  "the sky kept changing the script — {total} bursts",
  "the weather rolled through {total} times",
  "the field absorbed {total} weather bursts",
  "the race got lashed by the elements {total} times",
  "the sky made itself part of the story {total} times",
  "the weather kept swinging — {total} bursts total",
  "the elements barged in {total} times",
  "the field weathered {total} separate bursts",
  "the race got {total} full weather swings",
  "the sky refused to stay quiet — {total} bursts",
  "the weather turned the board sideways {total} times",
  "the elements crashed the party {total} times",
  "the field took {total} weather hits",
] as const;

export const RECAP_FIGHT_PHRASES = [
  "{a} and {b} threw down mid-race",
  "fists flew when {a} and {b} got into it",
  "{a} and {b} scrapped in the middle of the pack",
  "{a} and {b} got tangled up mid-race",
  "{a} and {b} traded blows in the pack",
  "tempers flared between {a} and {b}",
  "{a} and {b} went at it in the middle of the field",
  "{a} and {b} had a mid-race dustup",
  "{a} and {b} collided with more than points on the line",
  "{a} and {b} turned the pack into a brawl",
  "{a} and {b} got into it deep in the race",
  "{a} and {b} scrapped when nobody was looking",
  "{a} and {b} brought the fight to the middle of the order",
  "{a} and {b} exchanged more than scores",
  "{a} and {b} turned a quiet tick into a fight",
  "{a} and {b} went shoulder to shoulder and then some",
  "{a} and {b} made the broadcast cut to chaos",
  "{a} and {b} turned momentum into a melee",
  "{a} and {b} got personal in the pack",
  "{a} and {b} turned the race into a grudge match for a moment",
  "{a} and {b} brawled in the middle of the standings",
  "{a} and {b} let the points wait and fought instead",
  "{a} and {b} turned the lane into a problem",
  "{a} and {b} had words and then worse",
  "{a} and {b} made the pit crew look nervous",
  "{a} and {b} turned a routine stretch into a fight",
  "{a} and {b} got after it in the pack",
  "{a} and {b} brought the heat mid-race",
  "{a} and {b} turned the board into a boxing card",
  "{a} and {b} scrapped while the race kept moving",
  "{a} and {b} made everyone else get out of the way",
  "{a} and {b} turned a score tick into a confrontation",
  "{a} and {b} got into a full mid-race scrap",
  "{a} and {b} threw hands in the pack",
  "{a} and {b} turned the middle of the field into a problem",
  "{a} and {b} went from racing to fighting fast",
  "{a} and {b} had a mid-pack explosion",
  "{a} and {b} made the race uglier for a minute",
  "{a} and {b} turned the standings into a contact sport",
  "{a} and {b} got rough when the pace tightened",
] as const;

export const RECAP_FIGHT_MULTI_PHRASES = [
  "{count} separate fights broke out, including {first} and {second}",
  "the field brawled {count} times — {first} and {second} among them",
  "{count} different fights hit the race, including {first} and {second}",
  "the pack fought {count} times, with {first} and {second} in the mix",
  "{count} brawls broke out, including {first} and {second}",
  "the race saw {count} fights, including {first} and {second}",
  "{count} separate dustups landed, including {first} and {second}",
  "the field could not keep its hands to itself — {count} fights, including {first} and {second}",
  "{count} fights made the recap harder to write, including {first} and {second}",
  "the race turned chippy {count} times, including {first} and {second}",
  "{count} mid-race fights broke out, including {first} and {second}",
  "the standings got violent {count} times, including {first} and {second}",
  "{count} separate scraps hit the field, including {first} and {second}",
  "the broadcast kept cutting to fights — {count} total, including {first} and {second}",
  "{count} fights interrupted the scoring, including {first} and {second}",
  "the pack erupted {count} times, including {first} and {second}",
  "{count} fights made the race feel personal, including {first} and {second}",
  "the field fought {count} separate times, including {first} and {second}",
  "{count} brawls changed the temperature, including {first} and {second}",
  "the race logged {count} fights, including {first} and {second}",
  "{count} separate confrontations broke out, including {first} and {second}",
  "the middle of the pack kept exploding — {count} fights, including {first} and {second}",
  "{count} fights left marks on the recap, including {first} and {second}",
  "the field went to war {count} times, including {first} and {second}",
  "{count} fights made the day messier, including {first} and {second}",
] as const;

export const RECAP_GOD_SCORE_PHRASES = [
  "somebody touched the forbidden 240 — GOD score territory",
  "the leaderboard cracked open at 240 — a GOD score moment",
  "the race briefly entered forbidden scoring territory at 240",
  "someone knocked on the door of 240 — a GOD score moment",
  "the scoreboard flirted with 240 and meant it",
  "the field got a glimpse of 240 — GOD score territory",
  "somebody climbed into mythic scoring at 240",
  "the race produced a 240-point GOD score moment",
  "the standings went supernatural at 240",
  "someone hit the number the league whispers about — 240",
  "the board touched holy ground at 240",
  "the race found GOD score air at 240",
  "somebody reached the forbidden peak at 240",
  "the score line turned legendary at 240",
  "the field witnessed a GOD score push to 240",
  "someone stepped into scoring folklore at 240",
  "the race briefly broke the ceiling at 240",
  "the leaderboard saw GOD score energy at 240",
  "somebody made 240 look possible",
  "the race delivered a true GOD score moment at 240",
] as const;

export const RECAP_CHAOS_SURGE_PHRASES = [
  "{count} chaos surge{plural} ripped through the field",
  "{count} chaos surge{plural} detonated across the standings",
  "{count} chaos surge{plural} rewrote the board",
  "{count} chaos surge{plural} hit the race",
  "{count} chaos surge{plural} shook the standings loose",
  "{count} chaos surge{plural} turned the race feral",
  "{count} chaos surge{plural} blasted through the order",
  "{count} chaos surge{plural} made the leaderboard unstable",
  "{count} chaos surge{plural} tore through the pack",
  "{count} chaos surge{plural} left the field scrambling",
  "{count} chaos surge{plural} hit like weather indoors",
  "{count} chaos surge{plural} scrambled the standings",
  "{count} chaos surge{plural} made the race feel unhinged",
  "{count} chaos surge{plural} detonated in the middle of the board",
  "{count} chaos surge{plural} turned calm stretches into emergencies",
  "{count} chaos surge{plural} punished anyone standing still",
  "{count} chaos surge{plural} kept the field off balance",
  "{count} chaos surge{plural} made the recap write itself",
  "{count} chaos surge{plural} hit the race at the worst times",
  "{count} chaos surge{plural} left the standings looking wounded",
  "{count} chaos surge{plural} turned the board into a pinball machine",
  "{count} chaos surge{plural} made the day feel unstable",
  "{count} chaos surge{plural} ripped the order apart",
  "{count} chaos surge{plural} kept the broadcast on alert",
  "{count} chaos surge{plural} made every tick feel dangerous",
] as const;

export const RECAP_COLLAPSE_PHRASES = [
  "{count} late collapse{plural} torched the leaderboard",
  "{count} collapse{plural} gutted the back half",
  "{count} collapse{plural} wrecked the standings",
  "{count} collapse{plural} turned leads into regrets",
  "{count} collapse{plural} hit the field late",
  "{count} collapse{plural} made the finish line cruel",
  "{count} collapse{plural} shredded the order",
  "{count} collapse{plural} left the board looking bruised",
  "{count} collapse{plural} punished the front at the wrong time",
  "{count} collapse{plural} turned momentum into rubble",
  "{count} collapse{plural} broke the back of the field",
  "{count} collapse{plural} made the final hours ugly",
  "{count} collapse{plural} flipped the script late",
  "{count} collapse{plural} turned confidence into chaos",
  "{count} collapse{plural} hit like a trap door",
  "{count} collapse{plural} left the standings gasping",
  "{count} collapse{plural} made the race feel cruel at the end",
  "{count} collapse{plural} tore through the order late",
  "{count} collapse{plural} turned the board into a funeral",
  "{count} collapse{plural} made the finish brutal",
  "{count} collapse{plural} wrecked anyone who looked safe",
  "{count} collapse{plural} hit the field when it mattered most",
  "{count} collapse{plural} turned the leaderboard into a warning",
  "{count} collapse{plural} made the final stretch humiliating",
  "{count} collapse{plural} left the standings in pieces",
] as const;

export const RECAP_RANK_SURGE_PHRASES = [
  "{count} rank surge{plural} shook the standings",
  "{count} rank surge{plural} rewrote the order",
  "{count} rank surge{plural} moved the board fast",
  "{count} rank surge{plural} changed the picture",
  "{count} rank surge{plural} hit the field hard",
  "{count} rank surge{plural} scrambled the standings",
  "{count} rank surge{plural} made the race feel alive",
  "{count} rank surge{plural} turned quiet ticks into drama",
  "{count} rank surge{plural} shuffled the pack",
  "{count} rank surge{plural} kept the order unstable",
  "{count} rank surge{plural} moved names up the board",
  "{count} rank surge{plural} made the leaderboard restless",
  "{count} rank surge{plural} hit like a wave through the field",
  "{count} rank surge{plural} kept everyone nervous",
  "{count} rank surge{plural} turned position into a live wire",
  "{count} rank surge{plural} made the standings impossible to trust",
  "{count} rank surge{plural} kept the race from settling",
  "{count} rank surge{plural} moved the order around",
  "{count} rank surge{plural} made the board feel temporary",
  "{count} rank surge{plural} kept the field in motion",
] as const;

export const RECAP_UNDERDOG_PHRASES = [
  "underdog pressure flared {count} time{plural}",
  "the long shots pushed back {count} time{plural}",
  "the winless kept causing trouble {count} time{plural}",
  "the field got reminded the long shots matter {count} time{plural}",
  "underdog energy showed up {count} time{plural}",
  "the outsiders made noise {count} time{plural}",
  "the long shots refused to disappear {count} time{plural}",
  "underdog runs kept the race honest {count} time{plural}",
  "the field got tested by outsiders {count} time{plural}",
  "the winless made the board nervous {count} time{plural}",
  "underdog chaos hit {count} time{plural}",
  "the long shots kept swinging {count} time{plural}",
  "the outsiders kept showing up {count} time{plural}",
  "underdog pressure kept building {count} time{plural}",
  "the field got hunted from below {count} time{plural}",
  "the long shots made the race feel open {count} time{plural}",
  "underdog storylines flared {count} time{plural}",
  "the outsiders kept stealing moments {count} time{plural}",
  "the winless kept making the leaders sweat {count} time{plural}",
  "underdog runs changed the temperature {count} time{plural}",
] as const;

export const RECAP_INJURY_PHRASES = [
  "{count} injur{injuryWord} forced racers off the track",
  "{count} injur{injuryWord} knocked racers out of the running",
  "{count} injur{injuryWord} interrupted the race",
  "{count} injur{injuryWord} sent racers to the shelf",
  "{count} injur{injuryWord} changed the roster mid-race",
  "{count} injur{injuryWord} hit the field hard",
  "{count} injur{injuryWord} left the standings wounded",
  "{count} injur{injuryWord} made the day uglier",
  "{count} injur{injuryWord} forced timeouts",
  "{count} injur{injuryWord} kept the medical desk busy",
  "{count} injur{injuryWord} removed racers from contention",
  "{count} injur{injuryWord} turned the race into a triage report",
  "{count} injur{injuryWord} broke up the flow",
  "{count} injur{injuryWord} left gaps in the field",
  "{count} injur{injuryWord} made the finish line meaner",
  "{count} injur{injuryWord} punished the board",
  "{count} injur{injuryWord} forced the race to adapt",
  "{count} injur{injuryWord} kept the standings in flux",
  "{count} injur{injuryWord} made the day feel dangerous",
  "{count} injur{injuryWord} knocked racers out of rhythm",
] as const;

export const RECAP_DELAY_PHRASES = [
  "the race went dark during {title} — full delay",
  "the broadcast cut out for {title} — full race delay",
  "the field went on hold during {title}",
  "the race stopped cold for {title}",
  "the clock froze during {title}",
  "the board went quiet during {title}",
  "the race hit a full delay during {title}",
  "the field waited out {title}",
  "the race paused for {title}",
  "the standings froze during {title}",
  "the race lost time to {title}",
  "the broadcast turned into static during {title}",
  "the field got stuck in {title}",
  "the race went into delay mode during {title}",
  "the day stopped moving during {title}",
  "the race hit the brakes for {title}",
  "the field sat in darkness during {title}",
  "the race lost a chapter to {title}",
  "the board stopped ticking during {title}",
  "the race went offline for {title}",
] as const;

export const RECAP_QUIET_PHRASES = [
  "No fights, no injuries, no race delay — just pure scoring warfare.",
  "No brawls, no injuries, no delay — just points and panic.",
  "Nobody fought, nobody broke, and the points still did all the damage.",
  "The race stayed clean on paper and vicious on the board.",
  "No chaos in the log — only the scoreboard misbehaving.",
  "No fights and no injuries, but the standings still bled.",
  "The race behaved itself off the track and not on it.",
  "No delays, no brawls — just twenty-four hours of scoreboard tension.",
  "The field kept its hands to itself and still made a mess.",
  "No injuries, no fights, no mercy in the points.",
  "The race stayed quiet in the pits and loud on the leaderboard.",
  "No one threw a punch, but the board still got violent.",
  "Clean race log, dirty scoreboard — that was the whole story.",
  "No delay, no fights, just a full day of scoreboard pressure.",
  "The race avoided drama everywhere except the standings.",
  "No brawls and no injuries, but the points kept swinging anyway.",
  "The field raced clean and scored dirty.",
  "No chaos events — only the leaderboard acting up.",
  "The race kept the violence purely numerical.",
  "No fights, no injuries, no excuses — just points.",
  "The log stayed calm while the standings did not.",
  "No one got hurt and everyone still suffered on the board.",
  "The race was quiet in the pits and brutal in the points.",
  "No delay, no fights — only scoreboard warfare.",
  "The field behaved and the leaderboard did not.",
  "No injuries, no brawls, no shelter from the scoring.",
  "The race looked peaceful until you checked the board.",
  "No chaos in the ticker — just a day of pure points.",
  "The field kept it clean and still made it hurt.",
  "No fights, no injuries, no delay — only the standings turning.",
] as const;

export const RECAP_ABILITY_GAIN_LEAD_PHRASES = [
  "Coming out of the race, ",
  "After the checkered flag, ",
  "When the dust settled, ",
  "Once the points were final, ",
  "Leaving the finish behind, ",
  "On the way out of race day, ",
  "After twenty-four hours of racing, ",
  "With the standings locked, ",
  "Once the board went final, ",
  "Coming off the finish, ",
] as const;

export const RECAP_ABILITY_GAIN_PLAYER_PHRASES = [
  "{name} picked up {gains}",
  "{name} walked away with {gains}",
  "{name} banked {gains}",
  "{name} left with {gains}",
  "{name} carried out {gains}",
  "{name} earned {gains}",
  "{name} stacked {gains}",
  "{name} added {gains}",
  "{name} took home {gains}",
  "{name} finished with {gains}",
  "{name} secured {gains}",
  "{name} pocketed {gains}",
  "{name} came away with {gains}",
  "{name} gained {gains}",
  "{name} upgraded with {gains}",
  "{name} boosted their sheet with {gains}",
  "{name} left the race with {gains}",
  "{name} collected {gains}",
  "{name} hauled away {gains}",
  "{name} ended the day with {gains}",
] as const;
