export {
  RECAP_OPENERS,
  RECAP_OPENING_FRAME_PHRASES,
  RECAP_WIN_PHRASES,
  RECAP_MARGIN_PHRASES,
  RECAP_LAST_PHRASES,
  RECAP_WEATHER_PHRASES,
  RECAP_FIGHT_PHRASES,
  RECAP_FIGHT_MULTI_PHRASES,
  RECAP_GOD_SCORE_PHRASES,
  RECAP_CHAOS_SURGE_PHRASES,
  RECAP_COLLAPSE_PHRASES,
  RECAP_RANK_SURGE_PHRASES,
  RECAP_UNDERDOG_PHRASES,
  RECAP_INJURY_PHRASES,
  RECAP_DELAY_PHRASES,
  RECAP_QUIET_PHRASES,
  RECAP_ABILITY_GAIN_LEAD_PHRASES,
  RECAP_ABILITY_GAIN_PLAYER_PHRASES,
} from "./recap-phrase-pools";

export const RECAP_OPENER_PHRASES = [
  "Race {n} {opener}.",
] as const;

export const RECAP_STALL_PHRASES = [
  "{count} stall events stopped racers cold",
  "{count} long stalls froze the field",
  "{count} dead stops slowed the whole race",
  "{count} frozen ticks locked up the standings",
  "{count} standstills killed momentum across the field",
  "{count} gridlock moments strangled the pace",
  "{count} motionless stretches reshaped the order",
  "{count} pauses on the scoreboard shook the race",
  "{count} flat ticks left the field stuck",
  "{count} long freezes broke up the flow",
  "{count} zero-output stretches stopped the hunt",
  "{count} bogged-down moments hit the leaderboard",
  "{count} stranded stretches slowed the charge",
  "{count} ice-cold ticks stalled the front",
  "{count} dead-quiet stretches froze the pack",
  "{count} stuck-in-neutral moments hit the field",
  "{count} pace droughts stopped racers in place",
  "{count} scoreboard freezes rewrote the tempo",
  "{count} traction losses stalled the standings",
  "{count} long pauses killed the momentum",
  "{count} flatline ticks stopped the field cold",
  "{count} motionless runs slowed the whole hunt",
  "{count} dead patches on the board shook the race",
  "{count} stuck stretches hit multiple racers",
  "{count} frozen moments stopped the charge",
  "{count} neutral-gear ticks killed the pace",
  "{count} standstill stretches froze the leaderboard",
  "{count} zero-momentum runs hit the field",
  "{count} long dead stops broke the rhythm",
  "{count} score droughts stalled the standings",
  "{count} ice stretches slowed the whole race",
  "{count} parked-on-the-board moments hit the field",
  "{count} stuck-in-the-mud ticks reshaped the order",
  "{count} flat stretches killed forward motion",
  "{count} dead ticks stopped the hunt cold",
  "{count} frozen scoreboard moments hit the race",
  "{count} long standstills broke the pace",
  "{count} traction failures stalled the field",
  "{count} quiet ticks stopped the leaderboard",
  "{count} motionless board moments hit the race",
  "{count} stuck-in-place stretches froze the hunt",
  "{count} pace kills stopped racers cold",
  "{count} dead-output ticks hit the field",
  "{count} long freezes on the board shook the race",
  "{count} stranded-on-the-score moments slowed the field",
  "{count} ice-cold stretches hit the standings",
  "{count} zero-point ticks stalled the hunt",
  "{count} flatboard moments killed the momentum",
  "{count} stuck stretches on the scoreboard hit the race",
  "{count} dead-stop ticks froze the field",
  "{count} long neutral runs stopped the charge",
  "{count} scoreboard standstills hit the race",
  "{count} frozen hunt moments slowed the field",
  "{count} traction droughts stopped the standings",
  "{count} motionless ticks hit the leaderboard",
  "{count} dead stretches on the board shook the race",
  "{count} stuck-in-neutral runs killed the pace",
  "{count} flat ticks on the hunt stopped the field",
  "{count} long score pauses hit the race",
  "{count} ice-on-the-board moments stalled the field",
  "{count} zero-momentum ticks reshaped the order",
  "{count} dead-quiet board runs hit the standings",
  "{count} stuck stretches killed the hunt",
  "{count} frozen pace moments stopped the field",
  "{count} long flat ticks hit the race",
  "{count} standstill board moments slowed the charge",
  "{count} traction-free stretches hit the field",
  "{count} motionless hunt ticks stopped the race",
  "{count} dead board moments froze the standings",
  "{count} stuck-on-zero stretches hit the field",
  "{count} ice stretches on the hunt killed momentum",
  "{count} long dead ticks stopped the field",
  "{count} scoreboard droughts hit the race",
  "{count} frozen stretches slowed the whole hunt",
  "{count} zero-output board moments stopped the field",
  "{count} stuck-in-the-pack ticks hit the race",
  "{count} flat hunt stretches killed the pace",
  "{count} dead momentum runs stopped the standings",
  "{count} long ice ticks hit the field",
  "{count} standstill hunt moments slowed the race",
  "{count} traction breaks stopped the charge",
  "{count} motionless score runs hit the field",
  "{count} dead-stop board moments froze the hunt",
  "{count} stuck stretches on the hunt hit the race",
  "{count} frozen output ticks stopped the field",
  "{count} long quiet stretches killed the pace",
  "{count} flatboard droughts hit the standings",
  "{count} zero-pace ticks stopped the race",
  "{count} stuck scoreboard moments hit the field",
  "{count} ice-cold board runs slowed the hunt",
  "{count} dead tick stretches stopped the field",
  "{count} long motionless runs hit the race",
  "{count} neutral stretches froze the standings",
  "{count} stuck hunt ticks killed momentum",
  "{count} flat score moments stopped the field",
  "{count} frozen board stretches hit the race",
  "{count} dead pace ticks slowed the hunt",
  "{count} long stuck stretches stopped the field",
  "{count} score standstill moments hit the race",
  "{count} ice hunt ticks killed the charge",
  "{count} zero-traction stretches stopped the field",
  "{count} dead board runs hit the standings",
  "{count} long flatboard moments slowed the race",
  "{count} stuck score ticks stopped the hunt",
  "{count} frozen momentum runs hit the field",
  "{count} motionless board stretches killed the pace",
  "{count} dead-output board moments stopped the race",
  "{count} long ice stretches hit the field",
  "{count} stuck neutral ticks slowed the hunt",
  "{count} flat momentum runs stopped the standings",
  "{count} zero-board ticks hit the race",
  "{count} dead hunt stretches froze the field",
  "{count} long traction losses stopped the charge",
  "{count} stuck flat ticks hit the race",
  "{count} frozen score stretches slowed the field",
  "{count} motionless output runs stopped the hunt",
  "{count} dead quiet board moments hit the race",
  "{count} long stuck board ticks killed momentum",
  "{count} ice score stretches stopped the field",
  "{count} zero-motion board runs hit the race",
  "{count} flat hunt droughts slowed the standings",
  "{count} dead neutral ticks stopped the field",
  "{count} long frozen board moments hit the race",
  "{count} stuck output stretches killed the pace",
  "{count} motionless scoreboard ticks stopped the hunt",
  "{count} dead flat stretches hit the field",
  "{count} long zero-output runs slowed the race",
  "{count} ice board droughts stopped the field",
  "{count} stuck momentum ticks hit the standings",
  "{count} frozen hunt stretches killed the charge",
  "{count} dead score pauses stopped the field",
  "{count} long quiet board runs hit the race",
  "{count} flat traction losses slowed the hunt",
  "{count} zero-board stretches stopped the field",
  "{count} stuck ice ticks hit the race",
  "{count} motionless hunt droughts killed momentum",
  "{count} dead frozen stretches stopped the standings",
  "{count} long dead board ticks hit the field",
  "{count} stuck flatboard moments slowed the race",
  "{count} frozen quiet runs stopped the hunt",
  "{count} ice momentum droughts hit the field",
  "{count} zero-pace board stretches killed the charge",
  "{count} dead stuck ticks stopped the race",
  "{count} long motionless board runs hit the field",
  "{count} flat output droughts slowed the hunt",
  "{count} stuck frozen stretches stopped the standings",
  "{count} dead ice board moments hit the race",
  "{count} long zero-traction ticks killed momentum",
  "{count} frozen flat stretches stopped the field",
  "{count} motionless stuck runs hit the race",
  "{count} dead board droughts slowed the hunt",
  "{count} long quiet score ticks stopped the field",
  "{count} ice stuck stretches hit the standings",
  "{count} zero-motion hunt runs killed the pace",
  "{count} flat frozen board moments stopped the race",
  "{count} dead traction droughts hit the field",
  "{count} long stuck hunt ticks slowed the charge",
  "{count} frozen dead stretches stopped the field",
  "{count} motionless ice runs hit the race",
  "{count} stuck quiet board moments killed momentum",
  "{count} dead flat hunt ticks stopped the standings",
  "{count} long zero-board stretches hit the field",
  "{count} ice motionless runs slowed the race",
  "{count} flat stuck board moments stopped the hunt",
  "{count} dead frozen hunt ticks hit the field",
  "{count} long traction droughts killed the pace",
  "{count} stuck dead board stretches stopped the race",
  "{count} frozen quiet hunt runs hit the field",
  "{count} motionless flat ticks slowed the standings",
  "{count} dead ice hunt stretches stopped the field",
  "{count} long stuck score ticks hit the race",
  "{count} zero frozen board runs killed momentum",
  "{count} flat dead hunt moments stopped the field",
  "{count} ice stuck score ticks hit the race",
  "{count} long motionless hunt droughts slowed the charge",
  "{count} dead flat board stretches stopped the standings",
  "{count} stuck zero-output ticks hit the field",
  "{count} frozen dead hunt runs killed the pace",
  "{count} motionless ice board moments stopped the race",
  "{count} long quiet hunt stretches hit the field",
  "{count} flat stuck momentum ticks slowed the standings",
  "{count} dead zero-board runs stopped the hunt",
  "{count} ice flat score stretches hit the race",
  "{count} long frozen hunt droughts killed momentum",
  "{count} stuck motionless board ticks stopped the field",
  "{count} dead quiet hunt runs hit the race",
] as const;

/** @deprecated use RECAP_QUOTE_PHRASES from notable lines when wired */
export const RECAP_QUOTE_PHRASES = [
  "the broadcast desk lost it: \"{quote}\"",
  "the booth could not believe it: \"{quote}\"",
] as const;
