import { seededInt } from "./seeded-rng";

export type TickerPhraseVars = Record<string, string | number>;

export function fillTickerPhrase(template: string, vars: TickerPhraseVars): string {
  let out = template;
  for (const [key, val] of Object.entries(vars)) {
    out = out.replaceAll(`{${key}}`, String(val));
  }
  return out;
}

export function pickTickerPhrase(
  seed: string,
  phrases: readonly string[],
  vars: TickerPhraseVars
): string {
  if (!phrases.length) return "";
  const template = phrases[seededInt(seed, 0, phrases.length - 1)];
  return fillTickerPhrase(template, vars);
}

function extractTemplateVars(template: string): string[] {
  return [...template.matchAll(/\{([a-zA-Z_]+)\}/g)].map((m) => m[1]!);
}

export function isCompleteTickerMessage(message: string): boolean {
  const trimmed = message.trim();
  return trimmed.length > 0 && !/\{[a-zA-Z_]+\}/.test(trimmed);
}

export function pickGatedTickerPhrase(
  seed: string,
  phrases: readonly string[],
  vars: TickerPhraseVars
): string | null {
  if (!phrases.length) return null;
  const eligible = phrases.filter((template) => phraseVarsAreValid(template, vars));
  if (!eligible.length) return null;
  return pickTickerPhrase(seed, eligible, vars);
}

function phraseVarsAreValid(template: string, vars: TickerPhraseVars): boolean {
  for (const key of extractTemplateVars(template)) {
    const val = vars[key];
    if (val === undefined || val === null || val === "") return false;
    if (key === "loss" || key === "gain" || key === "delta" || key === "gap") {
      const n = Number(val);
      if (!Number.isFinite(n) || n < 1) return false;
    }
    if (key === "rank") {
      const n = Number(val);
      if (!Number.isInteger(n) || n < 1 || n > 8) return false;
    }
  }
  return true;
}

export const SCORE_COLLAPSE_PHRASES = [
  "{name} COLLAPSE — {delta} PTS LOST!",
  "POINT COLLAPSE FOR {name} — MINUS {delta}!",
  "{name} BLEW UP — {delta} POINTS GONE!",
  "SCORE DISASTER — {name} LOST {delta} PTS!",
  "{name} MELTED {delta} POINTS OFF THE BOARD!",
  "BRUTAL TICK FOR {name} — DOWN {delta} PTS!",
  "{name} GAVE BACK {delta} POINTS!",
  "THE WHEELS CAME OFF — {name} MINUS {delta}!",
  "{name} UNRAVELING — {delta} PT DROP!",
  "COLLAPSE ON THE SCOREBOARD — {name} -{delta}!",
  "{name} LOST {delta} IN ONE SWING!",
  "POINTS EVAPORATED FOR {name} — {delta} GONE!",
  "{name} TOOK A {delta}-POINT HIT!",
  "SCORE FADE — {name} DOWN {delta}!",
  "{name} IS CRUMBLING — {delta} PTS LOST!",
  "DISASTER ON POINTS — {name} -{delta}!",
  "{name} DROPPED {delta} ON THE SCOREBOARD!",
  "COLLAPSE CONFIRMED — {name} -{delta} PTS!",
  "{name} LOST THE PLOT — {delta} POINTS!",
  "HARD FALL ON POINTS — {name} MINUS {delta}!",
] as const;

export const LEAD_CHANGE_PHRASES = [
  "OH! {name} TAKES THE LEAD — {prev} DROPPED!",
  "LEAD CHANGE! {name} IS OUT FRONT NOW!",
  "{name} SEIZES THE POINT! WHAT A MOVE!",
  "NEW LEADER! {name} AT THE FRONT!",
  "WE HAVE A NEW LEADER — {name} PASSES {prev}!",
  "BREAKING: {name} GRABS THE TOP SPOT FROM {prev}!",
  "THE LEAD BELONGS TO {name} NOW — {prev} FADED!",
  "{name} STEPS INTO P1! {prev} CAN'T HOLD IT!",
  "UP FRONT IT'S {name}! {prev} LOSES THE POINT!",
  "LEAD CHANGE AT THE FRONT — {name} IS FLYING!",
  "{name} SNATCHES THE LEAD AWAY FROM {prev}!",
  "POINT LEADERSHIP FLIPS — {name} IS YOUR NEW FRONT RUNNER!",
  "LISTEN TO THIS CROWD — {name} TAKES COMMAND!",
  "{prev} HAD IT… AND NOW {name} HAS IT!",
  "THE THRONE CHANGES HANDS — {name} LEADS!",
  "OUT FRONT: {name}! {prev} PUSHED ASIDE!",
  "WHAT A SWAP! {name} LEADS, {prev} CHASING!",
  "{name} GRABS THE BRIGHT SPOT — LEAD CHANGE!",
  "LEAD UPDATE: {name} FROM {prev} — WE GO AGAIN!",
  "CAN YOU BELIEVE IT? {name} IS LEADING NOW!",
  "{name} TOOK THE WHEEL UP FRONT — {prev} DROPPED BACK!",
  "THE POINT IS {name}'S — {prev} LOST THE HANDLE!",
  "FRONT RUNNER ALERT: {name}!",
  "{name} PUNCHES THROUGH — NEW LEADER!",
  "LEAD TRANSFER COMPLETE — {name} OUT FRONT!",
  "OH MY — {name} STOLE THE LEAD FROM {prev}!",
  "WE'VE GOT DRAMA UP FRONT — {name} LEADS!",
  "{name} IS YOUR RACE LEADER NOW!",
  "THE LEAD LINE READS {name} — NOT {prev}!",
  "SWITCH AT THE FRONT — {name} IN P1!",
  "{name} WRESTLED THE LEAD AWAY FROM {prev}!",
  "POINT POSITION ONE: {name}!",
  "LEAD CHANGE CONFIRMED — {name} UP TOP!",
  "{prev} FADED — {name} TOOK OVER UP FRONT!",
  "THE FRONT SPOT FLIPS TO {name}!",
  "{name} IS LEADING THE CHARGE NOW!",
  "NEW NAME UP FRONT — IT'S {name}!",
  "LEADERSHIP CHANGE — {name} FROM {prev}!",
  "{name} GRABS P1 WITH AUTHORITY!",
  "UP TOP IT'S ALL {name} NOW!",
  "THE LEAD BELONGS TO {name} — STUNNING!",
] as const;

export const CHAOS_SURGE_PHRASES = [
  "CHAOS SURGE! {name} IS UNLEASHED!",
  "{name} WENT ABSOLUTELY WILD!",
  "OH MY — {name} HIT A CHAOS BURST!",
  "TOTAL CHAOS FROM {name} RIGHT NOW!",
  "{name} DETONATED A CHAOS SURGE!",
  "UNPREDICTABLE ENERGY — {name} EXPLODED!",
  "CHAOS MODE: {name} IS OFF THE CHARTS!",
  "{name} UNLEASHED PURE CHAOS OUT THERE!",
  "THE FIELD CAN'T HANDLE {name} RIGHT NOW!",
  "CHAOS BURST! {name} IS ELECTRIC!",
  "WILD SWING FROM {name} — CHAOS SURGE!",
  "{name} TURNED IT UP TO CHAOS!",
  "ABSOLUTE MAYHEM — {name} SURGED!",
  "CHAOS FACTOR MAX — {name} FLYING!",
  "{name} HIT THE CHAOS BUTTON!",
  "UNHINGED RUN FROM {name}!",
  "CHAOS SURGE ALERT — {name}!",
  "{name} IS PLAYING WITH FIRE AND WINNING!",
  "THE CHAOS GODS SMILE ON {name}!",
  "ERRATIC BRILLIANCE FROM {name}!",
  "{name} WENT CHAOTIC — POINTS POURING IN!",
  "CHAOS UNLEASHED — {name} ON A TEAR!",
  "{name} — CHAOS SURGE — HOLD ON!",
  "PURE CHAOS ENERGY FROM {name}!",
  "NOBODY CALLED THIS — {name} CHAOS SURGE!",
] as const;

export const COLLAPSE_PHRASES = [
  "{name} IS FADING FAST — DOWN {loss} SPOTS!",
  "DISASTER FOR {name}! {loss}-SPOT COLLAPSE!",
  "{name} IS FALLING APART OUT THERE!",
  "COLLAPSE! {name} DROPPED {loss} POSITIONS!",
  "{name} IS MELTING DOWN — {loss} SPOTS LOST!",
  "BRUTAL SLIDE FOR {name} — MINUS {loss}!",
  "{name} TUMBLING — {loss}-SPOT DISASTER!",
  "THE WHEELS CAME OFF FOR {name}!",
  "{name} IN FREE FALL — DOWN {loss}!",
  "CATASTROPHIC DROP FOR {name}!",
  "{name} LOST {loss} SPOTS IN ONE SWING!",
  "OH NO — {name} COLLAPSED {loss} PLACES!",
  "{name} IS SPIRALING — {loss} SPOT DROP!",
  "COMPLETE MELTDOWN — {name} DOWN {loss}!",
  "{name} GOT CAUGHT AND PAID — {loss} SPOTS!",
  "THE BOTTOM DROPPED OUT FOR {name}!",
  "{name} — {loss}-SPOT COLLAPSE — BRUTAL!",
  "DISASTER STRIKES {name} — DOWN {loss}!",
  "{name} FELL APART — {loss} POSITIONS GONE!",
  "COLLAPSE ALERT: {name} DOWN {loss}!",
  "{name} IS CRUMBLING OUT THERE!",
  "HARD FALL FOR {name} — {loss} SPOTS!",
  "{name} LOST THE PLOT — DOWN {loss}!",
  "THE FIELD PASSED {name} — {loss} SPOT DROP!",
  "{name} UNRAVELING — MINUS {loss}!",
  "TROUBLE FOR {name} — {loss}-SPOT SLIDE!",
  "{name} GOT SWALLOWED — DOWN {loss}!",
  "COLLAPSE CONFIRMED — {name} FADING!",
  "{name} DROPPED LIKE A STONE — {loss} SPOTS!",
  "NIGHTMARE MOMENT FOR {name}!",
] as const;

export const RANK_SLIP_PHRASES = [
  "{name} SLIPPED TWO SPOTS — TROUBLE!",
  "TWO-SPOT DROP FOR {name}!",
  "{name} LOST TWO POSITIONS!",
  "SLIDE FOR {name} — DOWN TWO!",
  "{name} FELL BACK A PAIR!",
  "TWO-SPOT SLIP — {name} IN TROUBLE!",
  "{name} DROPPED TWO — NOT IDEAL!",
  "PAIR OF SPOTS LOST FOR {name}!",
  "{name} SLID TWO PLACES BACK!",
  "MINOR DISASTER — {name} DOWN TWO!",
  "{name} LOST GROUND — TWO SPOTS!",
  "TWO DOWN FOR {name} THIS TICK!",
  "{name} SLIPPED — TWO SPOT DROP!",
  "BACKWARD STEP FOR {name} — MINUS TWO!",
  "{name} FADED TWO SPOTS!",
  "TWO-POSITION SLIP FOR {name}!",
  "{name} DROPPED A COUPLE!",
  "NOT THE MOVE {name} NEEDED — DOWN TWO!",
  "{name} LOST TWO IN THE SHUFFLE!",
  "SLIPPING: {name} DOWN TWO SPOTS!",
] as const;

export const RANK_SURGE_BIG_PHRASES = [
  "{name} SURGED {gain} SPOTS! INCREDIBLE!",
  "WHAT A RUN! {name} CLIMBED {gain} POSITIONS!",
  "{name} IS CHARGING — UP {gain} SPOTS!",
  "MASSIVE GAIN — {name} UP {gain}!",
  "{name} ROCKETED {gain} SPOTS!",
  "UNREAL CLIMB FROM {name} — PLUS {gain}!",
  "{name} FLEW UP {gain} POSITIONS!",
  "SENSATIONAL — {name} GAINED {gain} SPOTS!",
  "{name} ON A TEAR — UP {gain}!",
  "THE FIELD CAN'T STOP {name} — {gain} SPOT SURGE!",
  "{name} CHARGED {gain} PLACES!",
  "HUGE MOVE — {name} UP {gain} SPOTS!",
  "{name} SURGED THROUGH — {gain} SPOT GAIN!",
  "INCREDIBLE RUN — {name} PLUS {gain}!",
  "{name} CLIMBED {gain} — WHAT A SURGE!",
  "BREAKOUT MOMENT — {name} UP {gain}!",
  "{name} GAINED {gain} IN ONE BURST!",
  "THE CHASE IS ON — {name} UP {gain} SPOTS!",
  "{name} EXPLODED UP THE ORDER — {gain}!",
  "RANK SURGE — {name} PLUS {gain} SPOTS!",
  "{name} MOTORING — {gain} SPOT JUMP!",
  "STUNNING CLIMB — {name} UP {gain}!",
  "{name} WENT UP {gain} — FIELD SHAKEN!",
  "SURGE ALERT: {name} GAINED {gain}!",
  "{name} — {gain}-SPOT RUN — UNSTOPPABLE!",
  "WHAT A CHARGE FROM {name} — UP {gain}!",
  "{name} BLITZED {gain} SPOTS!",
  "RISING FAST — {name} PLUS {gain}!",
  "{name} CLAWED BACK {gain} POSITIONS!",
  "ELECTRIC SURGE — {name} UP {gain} SPOTS!",
] as const;

export const RANK_SURGE_TWO_PHRASES = [
  "{name} MOVED UP TWO — COMEBACK ALERT!",
  "TWO-SPOT GAIN FOR {name}!",
  "{name} CLIMBED TWO POSITIONS!",
  "PAIR OF SPOTS GAINED — {name}!",
  "{name} UP TWO — MOMENTUM BUILDING!",
  "TWO-SPOT SURGE FROM {name}!",
  "{name} GAINED TWO IN THE SHUFFLE!",
  "UP TWO FOR {name} — NICE MOVE!",
  "{name} STEPPED UP TWO SPOTS!",
  "COMEBACK FEELING — {name} PLUS TWO!",
  "{name} MOVED UP A PAIR!",
  "TWO-POSITION GAIN — {name}!",
  "{name} CLIMBED TWO — LOOK OUT!",
  "GAINING: {name} UP TWO SPOTS!",
  "{name} TOOK TWO SPOTS BACK!",
  "TWO UP FOR {name} THIS TICK!",
  "{name} SURGED TWO PLACES!",
  "POSITIVE MOVE — {name} PLUS TWO!",
  "{name} GAINED A COUPLE OF SPOTS!",
  "TWO-SPOT CHARGE FROM {name}!",
] as const;

export const BIG_LAP_PHRASES = [
  "{name} WITH A MONSTER LAP — +{delta} PTS!",
  "BIG LAP FROM {name}! GROUND GAINED!",
  "HUGE TICK FOR {name} — +{delta}!",
  "{name} PUT UP +{delta} THIS CYCLE!",
  "MONSTER OUTPUT — {name} +{delta} PTS!",
  "{name} SCORED +{delta} — BIG LAP!",
  "MASSIVE POINTS FROM {name} — +{delta}!",
  "{name} WITH A BANNER LAP — +{delta}!",
  "BIG NUMBERS — {name} +{delta} PTS!",
  "{name} UNLOADED +{delta} POINTS!",
  "LARGE LAP ALERT — {name} +{delta}!",
  "{name} STACKED +{delta} THIS TICK!",
  "ENORMOUS LAP — {name} +{delta}!",
  "{name} PUT THE FIELD ON NOTICE — +{delta}!",
  "POINT BURST FROM {name} — +{delta}!",
  "{name} WITH +{delta} — THAT'S A LAP!",
  "BIG-TICK ENERGY FROM {name} — +{delta}!",
  "{name} STACKED +{delta} POINTS!",
  "MAJOR LAP — {name} +{delta} PTS!",
  "{name} DROPPED +{delta} ON THE BOARD!",
  "HUGE OUTPUT — {name} +{delta}!",
  "{name} WITH A STATEMENT LAP — +{delta}!",
  "BIG POINTS — {name} +{delta}!",
  "{name} RIPPED +{delta} THIS CYCLE!",
  "LAP OF THE TICK — {name} +{delta}!",
] as const;

export const HOT_STRETCH_PHRASES = [
  "{name} ON A HEATER — SCORING BURST!",
  "HOT STRETCH! {name} IS UNSTOPPABLE RIGHT NOW!",
  "{name} CATCHING FIRE OUT THERE!",
  "{name} IS RED HOT RIGHT NOW!",
  "HEATER ALERT — {name} ON FIRE!",
  "{name} CAN'T MISS — HOT STRETCH!",
  "SCORCHING RUN FROM {name}!",
  "{name} IS BLAZING HOT!",
  "ON FIRE — {name} HOT STRETCH!",
  "{name} TURNED UP THE HEAT!",
  "HOT STREAK — {name} UNLOADING!",
  "{name} IS COOKING OUT THERE!",
  "TEMPERATURE RISING — {name} HEATING UP!",
  "{name} ON A SCORCHING STRETCH!",
  "WHITE HOT — {name} RIGHT NOW!",
  "{name} IS BURNING UP THE TRACK!",
  "HOT STRETCH CONFIRMED — {name}!",
  "{name} — UNREAL HEAT RIGHT NOW!",
  "THE HEATER IS ON — {name}!",
  "{name} IN THE ZONE — HOT STRETCH!",
] as const;

export const STALL_LONG_PHRASES = [
  "{name} STOPPED COLD — LONG STALL!",
  "{name} IS FROZEN OUT THERE!",
  "NO POINTS FROM {name} — IS THE RACE OVER FOR THEM?!",
  "{name} STUCK — LONG STALL IN PLAY!",
  "DEAD STOP FOR {name}!",
  "{name} WENT NOWHERE — LONG STALL!",
  "THE CLOCK IS TICKING — {name} STALLED!",
  "{name} FROZE UP COMPLETELY!",
  "LONG STALL — {name} STRANDED!",
  "{name} HIT A WALL — NOT MOVING!",
  "ZERO OUTPUT FROM {name} — STALLED!",
  "{name} IS STUCK IN THE MUD!",
  "STALL ALERT — {name} MOTIONLESS!",
  "{name} CAN'T GET GOING — LONG STALL!",
  "THE RACE LEFT {name} BEHIND — STALLED!",
  "{name} GRIND TO A HALT — STALL!",
  "LONG STALL FOR {name} — TROUBLE!",
  "{name} STOPPED DEAD IN THE WATER!",
  "NO FORWARD MOTION — {name} STALLED!",
  "{name} IS PARALYZED OUT THERE!",
  "{name} IS PARKED ON THE TRACK!",
  "ABSOLUTELY NOTHING FROM {name} THIS TICK!",
  "{name} FLATLINED ON POINTS!",
  "THE SCOREBOARD DIDN'T BLINK FOR {name}!",
  "{name} IS RUNNING IN QUICKSAND!",
  "MOTOR CUT — {name} GOING NOWHERE!",
  "{name} SEIZED UP MID-RACE!",
  "GRIDLOCK — {name} CAN'T ADVANCE!",
  "{name} LOOKS CEMENTED IN PLACE!",
  "A FULL STOP FROM {name} OUT THERE!",
  "{name} IS IDLING AT THE BACK!",
  "THE FIELD PULLED AWAY FROM {name}!",
  "{name} STUCK WITH THE HANDBRAKE ON!",
  "NO MOMENTUM LEFT FOR {name}!",
  "{name} BOGGED DOWN BAD!",
  "THE PACE VANISHED FOR {name}!",
  "{name} CAN'T BUY A POINT RIGHT NOW!",
  "STUCK IN NEUTRAL — {name}!",
  "{name} IS MAROONED OUT THERE!",
  "THE ENGINE DIED FOR {name} THIS TICK!",
  "{name} FROZE LIKE A STATUE!",
  "NOT A SINGLE POINT FOR {name}!",
  "{name} IS SPINNING THEIR WHEELS!",
  "THE RACE MOVED — {name} DIDN'T!",
  "{name} HIT AN INVISIBLE WALL!",
  "OUTPUT: ZERO — {name}!",
  "{name} IS STUCK IN TRAFFIC!",
  "THE SCORE STAYED PUT FOR {name}!",
  "{name} WENT FULL PARKING BRAKE!",
  "NO GAS IN THE TANK FOR {name}!",
  "{name} IS LOCKED UP OUT THERE!",
  "THE TICK PASSED {name} BY!",
  "{name} CAN'T FIND A GEAR!",
  "STANDSTILL — {name} NOT MOVING!",
  "{name} IS STUCK ON THE RAILS!",
  "THE POINTS DRIED UP FOR {name}!",
  "{name} FROZE MID-STRIDE!",
  "NOTHING. ZERO. NADA FROM {name}!",
  "{name} IS STUCK IN THE TAR!",
  "THE SCORE DIDN'T TICK FOR {name}!",
  "{name} WENT COMPLETELY DORMANT!",
  "A DEAD TICK FOR {name}!",
  "{name} IS STUCK IN THE SHALLOW END!",
  "THE RACE KEPT GOING — {name} DIDN'T!",
  "{name} HIT A BRICK WALL ON POINTS!",
  "NO TRACTION FOR {name} THIS TICK!",
  "{name} IS STUCK ON REPEAT!",
  "THE MOMENTUM DIED FOR {name}!",
  "{name} CAN'T GET UNSTUCK!",
  "FROZEN SOLID — {name}!",
  "{name} IS STUCK IN LOW GEAR!",
  "THE LEADERBOARD IGNORED {name}!",
  "{name} WENT DARK ON THE SCOREBOARD!",
  "NOT EVEN A FLICKER FROM {name}!",
  "{name} IS STUCK IN THE WRONG LANE!",
  "THE POINT PIPELINE SHUT FOR {name}!",
  "{name} CAN'T PUSH THROUGH!",
  "STUCK AND STRANDED — {name}!",
  "{name} IS RUNNING ON EMPTY!",
  "THE TICK WAS A BLANK FOR {name}!",
  "{name} FROZE AT THE WORST TIME!",
  "NO LIFT FROM {name} AT ALL!",
  "{name} IS STUCK IN THE MIDDLE!",
  "THE SCORE STALLED OUT FOR {name}!",
  "{name} CAN'T GET OUT OF FIRST!",
  "A LONG FREEZE FOR {name} OUT THERE!",
  "{name} IS STUCK BEHIND THE PACE!",
  "THE RACE CLOCK MOVED — {name} DIDN'T!",
  "{name} WENT NOWHERE FAST!",
  "ZERO FORWARD PROGRESS — {name}!",
  "{name} IS STUCK IN THE SHADOWS!",
  "THE FIELD GAINED — {name} DIDN'T!",
  "{name} CAN'T BREAK FREE!",
  "STUCK ON THE INSIDE — {name}!",
  "{name} IS FROZEN IN PLACE!",
  "THE SCOREBOARD SKIPPED {name}!",
  "{name} HIT A DEAD PATCH!",
  "NO MOVEMENT DETECTED FROM {name}!",
  "{name} IS STUCK AT THE LINE!",
  "THE PACE KILLED {name} THIS TICK!",
  "{name} WENT COMPLETELY STILL!",
  "STUCK WITHOUT A PULSE — {name}!",
  "{name} CAN'T FIND THE GAS!",
  "THE TICK WAS BRUTAL FOR {name} — NO POINTS!",
  "{name} IS STUCK IN THE REARVIEW!",
  "A FULL FREEZE FROM {name}!",
  "{name} DIDN'T MOVE THE NEEDLE!",
  "THE RACE PULLED AWAY — {name} STUCK!",
  "{name} IS STUCK IN THE SLOW LANE!",
  "NO SCORE ACTIVITY FROM {name}!",
  "{name} WENT ICE COLD ON POINTS!",
  "STUCK IN THE MUD — {name}!",
  "{name} CAN'T GET THE WHEELS TURNING!",
  "THE LEADERBOARD LEFT {name} BEHIND!",
  "{name} IS STUCK ON ZERO OUTPUT!",
  "A DEAD STOP IN PLAY FOR {name}!",
  "{name} FROZE WHEN IT MATTERED!",
  "NOTHING ON THE BOARD FOR {name}!",
  "{name} IS STUCK IN THE PACK!",
  "THE MOMENTUM VANISHED — {name}!",
  "{name} CAN'T SHIFT GEARS!",
  "STUCK FLAT — {name}!",
  "{name} IS RUNNING IN PLACE!",
  "THE SCORE DIDN'T MOVE FOR {name}!",
  "{name} WENT FULL STOP!",
  "NO POINTS. NO PACE. NO {name}!",
  "{name} IS STUCK IN THE GRIND!",
  "THE TICK FORGOT ABOUT {name}!",
  "{name} CAN'T GET LOOSE!",
  "FROZEN ON THE SCOREBOARD — {name}!",
  "{name} IS STUCK IN THE FOUL WEATHER!",
  "A LONG PAUSE FROM {name} OUT THERE!",
  "{name} DIDN'T GAIN AN INCH!",
  "THE RACE MOVED ON WITHOUT {name}!",
  "{name} IS STUCK IN THE BASEMENT!",
  "NO TRACTION — {name} SPINNING!",
  "{name} WENT COMPLETELY QUIET!",
  "STUCK AT THE BACK — {name}!",
  "{name} CAN'T FIND THE LINE!",
  "THE PACE LEFT {name} IN THE DUST!",
  "{name} IS FROZEN ON THE LEADERBOARD!",
  "A BRUTAL STANDSTILL FOR {name}!",
  "{name} DIDN'T TICK UP AT ALL!",
  "THE SCORE STAYED FLAT FOR {name}!",
  "{name} IS STUCK IN THE REAR!",
  "NO MOMENTUM — {name} STRANDED!",
  "{name} CAN'T BUY TRACTION!",
  "THE FIELD ADVANCED — {name} DIDN'T!",
  "{name} WENT STONE COLD THIS TICK!",
  "STUCK WITHOUT POINTS — {name}!",
  "{name} IS LOCKED IN PLACE!",
  "THE RACE KEPT ROLLING — {name} STOPPED!",
  "{name} CAN'T GET OUT OF THE HOLE!",
  "A FULL STALL CYCLE FOR {name}!",
  "{name} IS STUCK ON THE OUTSIDE!",
  "ZERO MOMENTUM FROM {name}!",
  "{name} FROZE WHEN THE FIELD MOVED!",
  "THE SCORE DIDN'T BUDGE FOR {name}!",
  "{name} IS STUCK IN THE CLUTTER!",
  "NO LIFT. NO POINTS. NO {name}!",
  "{name} CAN'T BREAK THE ICE!",
  "STUCK IN THE PACK — {name}!",
  "{name} WENT NOWHERE THIS TICK!",
  "THE PACE PASSED {name} BY!",
  "{name} IS FROZEN OUT OF THE HUNT!",
  "A DEAD QUIET TICK FOR {name}!",
  "{name} CAN'T GET THE MOTOR RUNNING!",
  "THE LEADERBOARD MOVED — {name} DIDN'T!",
  "{name} IS STUCK IN THE SHUFFLE!",
  "NO FORWARD GROUND FOR {name}!",
  "{name} WENT FULL FREEZE!",
  "STUCK ON THE SCOREBOARD — {name}!",
  "{name} CAN'T FIND A WAY THROUGH!",
  "THE TICK WAS EMPTY FOR {name}!",
  "{name} IS STUCK IN THE MIDDLE OF NOWHERE!",
  "NOT A WHISPER OF POINTS FROM {name}!",
  "{name} FROZE UP AT THE WRONG MOMENT!",
  "THE RACE LEFT {name} STANDING STILL!",
  "{name} IS STUCK IN THE GRAVEL!",
  "NO SCORE MOVEMENT FOR {name}!",
  "{name} CAN'T GET BACK IN GEAR!",
  "A LONG PAUSE ON POINTS — {name}!",
  "{name} WENT COMPLETELY FLAT!",
  "STUCK WITHOUT LIFT — {name}!",
  "{name} IS FROZEN IN THE ORDER!",
  "THE FIELD SCORED — {name} DIDN'T!",
  "{name} CAN'T PUSH PAST THE WALL!",
  "ZERO ACTIVITY FROM {name} THIS TICK!",
  "{name} IS STUCK IN THE BACKMARKER ZONE!",
  "THE PACE KILLED {name}'S MOMENTUM!",
  "{name} WENT ICE COLD OUT THERE!",
  "STUCK AND FROZEN — {name}!",
  "{name} CAN'T GET THE NEEDLE MOVING!",
  "THE SCOREBOARD FROZE FOR {name}!",
  "{name} IS STUCK IN THE DRAG!",
  "NO POINTS ON THE BOARD FOR {name}!",
  "{name} FROZE SOLID THIS TICK!",
  "THE RACE ADVANCED — {name} STUCK!",
  "{name} CAN'T FIND ANY PACE!",
  "A COMPLETE STOP FROM {name}!",
  "{name} IS STUCK IN THE REAR GUARD!",
  "THE TICK MOVED — {name} DIDN'T!",
  "{name} WENT DORMANT ON POINTS!",
  "STUCK IN THE SHUFFLE — {name}!",
  "{name} CAN'T GET UNFROZEN!",
  "THE LEADERBOARD SKIPPED {name}!",
  "{name} IS STUCK AT ZERO OUTPUT!",
  "NO GAIN. NO PACE. {name} STUCK!",
  "{name} FROZE WHEN THE BELL RANG!",
  "THE FIELD PULLED — {name} STUCK!",
  "{name} CAN'T MOVE THE SCORE!",
  "A BRUTAL FREEZE FOR {name}!",
  "{name} IS STUCK IN THE FOUL LANE!",
  "THE PACE VANISHED — {name} STRANDED!",
  "{name} WENT FULL PARKING LOT!",
  "STUCK WITHOUT A POINT — {name}!",
  "{name} CAN'T GET BACK ON THE GAS!",
  "THE SCORE STAYED DEAD FOR {name}!",
  "{name} IS FROZEN OUT OF CONTENTION!",
  "NO TRACTION THIS TICK — {name}!",
  "{name} FROZE ON THE LEADERBOARD!",
  "THE RACE ROLLED — {name} DIDN'T!",
  "{name} IS STUCK IN THE BACK!",
  "A LONG STANDSTILL FOR {name}!",
  "{name} CAN'T BREAK THE STALL!",
  "THE TICK WAS SILENT FOR {name}!",
  "{name} WENT COMPLETELY STUCK!",
  "STUCK IN PLACE — {name}!",
  "{name} CAN'T FIND FORWARD MOTION!",
  "THE SCORE DIDN'T FLINCH FOR {name}!",
  "{name} IS FROZEN ON THE TRACK!",
  "NO MOMENTUM ON THE BOARD — {name}!",
  "{name} FROZE UP — LONG STALL IN PLAY!",
  "THE PACE LEFT {name} BEHIND!",
  "{name} CAN'T GET OUT OF THE STALL!",
  "STUCK AT ZERO — {name}!",
  "{name} IS RUNNING ON FUMES AND STILL!",
  "THE FIELD MOVED — {name} FROZE!",
  "{name} CAN'T BUY MOMENTUM!",
  "A DEAD STALL FOR {name} OUT THERE!",
  "{name} WENT NOWHERE ON THE SCOREBOARD!",
  "STUCK IN THE REAR — {name}!",
  "{name} IS FROZEN SOLID ON POINTS!",
  "THE TICK PASSED {name} WITHOUT A POINT!",
  "{name} CAN'T GET THE PACE BACK!",
  "NO LIFT THIS TICK — {name}!",
  "{name} IS STUCK IN THE FOUL PATCH!",
  "THE RACE KEPT SCORING — {name} DIDN'T!",
  "{name} FROZE WHEN IT COUNTED!",
  "STUCK WITHOUT PROGRESS — {name}!",
  "{name} CAN'T MOVE UP THE BOARD!",
  "THE SCORE STALLED FOR {name}!",
  "{name} IS STUCK IN THE DRAG ZONE!",
  "ZERO PACE FROM {name} THIS TICK!",
  "{name} WENT FULL ICE OUT THERE!",
  "STUCK ON THE LEADERBOARD — {name}!",
  "{name} CAN'T FIND THE GROOVE!",
  "THE FIELD GAINED GROUND — {name} DIDN'T!",
  "{name} IS FROZEN IN THE PACK!",
  "NO POINTS LANDED FOR {name}!",
  "{name} FROZE AT THE START OF THE TICK!",
  "THE PACE DRIED UP — {name}!",
  "{name} CAN'T GET THE WHEELS SPINNING!",
  "STUCK IN THE MIDDLE — {name}!",
  "{name} WENT DEAD QUIET ON POINTS!",
  "THE SCOREBOARD DIDN'T MOVE FOR {name}!",
  "{name} IS STUCK IN THE FOUL WEATHER PATCH!",
  "NO FORWARD MOTION THIS TICK — {name}!",
  "{name} CAN'T BREAK OUT OF THE STALL!",
  "A FULL FREEZE ON THE BOARD — {name}!",
  "{name} IS STUCK IN THE SHADOW OF THE PACK!",
  "THE RACE ADVANCED WITHOUT {name}!",
  "{name} FROZE WHEN THE FIELD MOVED!",
  "STUCK WITHOUT SCORE — {name}!",
  "{name} CAN'T GET BACK IN THE HUNT!",
  "THE TICK WAS BRUTAL — {name} STUCK!",
  "{name} IS FROZEN OUT OF THE POINTS!",
  "NO MOMENTUM THIS TICK — {name}!",
  "{name} WENT STONE STILL OUT THERE!",
  "STUCK IN THE REARVIEW — {name}!",
  "{name} CAN'T FIND THE PACE LINE!",
  "THE LEADERBOARD FROZE FOR {name}!",
  "{name} IS STUCK IN THE GRIND ZONE!",
  "ZERO OUTPUT THIS TICK — {name}!",
  "{name} FROZE ON CONTACT WITH THE PACE!",
  "THE FIELD SCORED POINTS — {name} DIDN'T!",
  "{name} CAN'T GET OFF THE MARK!",
  "STUCK AT THE BACK — {name}!",
  "{name} IS RUNNING IN CEMENT!",
  "THE PACE PASSED {name} BY COMPLETELY!",
  "{name} WENT FULL STOP ON POINTS!",
  "NO TRACTION ON THE BOARD — {name}!",
  "{name} IS FROZEN OUT OF THE RACE FLOW!",
  "STUCK WITHOUT A TICK — {name}!",
  "{name} CAN'T MOVE THE NEEDLE AT ALL!",
  "THE SCORE STAYED FLAT — {name}!",
  "{name} FROZE WHEN THE PACE PICKED UP!",
  "A LONG STALL CYCLE FOR {name}!",
  "{name} IS STUCK IN THE FOUL LANE AGAIN!",
  "THE RACE MOVED FORWARD — {name} DIDN'T!",
  "{name} CAN'T GET BACK ON TRACK!",
  "STUCK IN NEUTRAL GEAR — {name}!",
  "{name} WENT ICE COLD THIS TICK!",
  "THE FIELD PULLED AHEAD — {name} STUCK!",
  "{name} IS FROZEN ON THE SCORE LINE!",
  "NO POINTS THIS TICK — {name}!",
  "{name} CAN'T FIND ANY LIFT!",
  "STUCK IN THE PACK AGAIN — {name}!",
  "{name} FROZE SOLID OUT THERE!",
  "THE PACE KILLED {name}!",
  "{name} IS STUCK WITHOUT A GEAR!",
  "ZERO FORWARD MOTION THIS TICK — {name}!",
  "{name} CAN'T GET THE ENGINE TURNING!",
  "STUCK ON ZERO — {name}!",
  "{name} WENT DORMANT OUT THERE!",
  "THE SCORE DIDN'T TICK UP — {name}!",
  "{name} IS FROZEN IN THE STANDINGS!",
  "NO GAS FROM {name} THIS TICK!",
  "{name} CAN'T BREAK THE FREEZE!",
  "STUCK IN THE FOUL PATCH — {name}!",
  "{name} FROZE WHEN THE LEAD GROUP MOVED!",
  "THE TICK LEFT {name} BEHIND!",
  "{name} IS STUCK IN THE BACK HALF!",
  "NO MOMENTUM ON POINTS — {name}!",
  "{name} WENT FULL PARKING MODE!",
  "STUCK WITHOUT PACE — {name}!",
  "{name} CAN'T GET BACK IN THE MIX!",
  "THE SCOREBOARD STALLED FOR {name}!",
  "{name} IS FROZEN OUT OF THE SCRUM!",
  "ZERO LIFT FROM {name}!",
  "{name} FROZE AT THE WRONG TIME AGAIN!",
  "THE FIELD MOVED — {name} STUCK STILL!",
  "{name} CAN'T FIND THE ACCELERATOR!",
  "STUCK IN THE DRAG — {name}!",
  "{name} WENT NOWHERE ON POINTS!",
  "THE PACE VANISHED FOR {name} THIS TICK!",
  "{name} IS STUCK IN THE FOUL ZONE!",
  "NO SCORE FROM {name} AT ALL!",
  "{name} CAN'T GET UNSTUCK THIS TICK!",
  "STUCK AND MOTIONLESS — {name}!",
  "{name} FROZE ON THE LEADERBOARD AGAIN!",
  "THE RACE SCORED — {name} DIDN'T!",
  "{name} IS STUCK IN THE REAR PACK!",
  "NO POINTS LANDED THIS TICK — {name}!",
  "{name} CAN'T MOVE UP AT ALL!",
  "STUCK IN THE SHUFFLE AGAIN — {name}!",
  "{name} WENT COMPLETELY ICE COLD!",
  "THE TICK FORGOT {name} EXISTED!",
  "{name} IS FROZEN OUT OF THE POINT RACE!",
  "ZERO PACE ON THE BOARD — {name}!",
  "{name} CAN'T GET THE PACE LINE BACK!",
  "STUCK WITHOUT MOMENTUM — {name}!",
  "{name} FROZE WHEN THE FIELD SURGED!",
  "THE SCORE STAYED PUT — {name}!",
  "{name} IS STUCK IN THE BACKMARK!",
  "NO TRACTION OUT THERE — {name}!",
  "{name} WENT FULL FREEZE THIS TICK!",
  "STUCK ON THE INSIDE LINE — {name}!",
  "{name} CAN'T BUY A POINT THIS TICK!",
  "THE PACE LEFT {name} IN THE DUST AGAIN!",
  "{name} IS FROZEN SOLID IN THE ORDER!",
  "NO FORWARD GROUND THIS TICK — {name}!",
  "{name} FROZE WHEN IT MATTERED MOST!",
  "STUCK IN THE REAR GUARD — {name}!",
  "{name} CAN'T GET THE SCORE MOVING!",
  "THE FIELD ADVANCED — {name} FROZE!",
  "{name} IS STUCK IN THE FOUL WEATHER!",
  "ZERO MOMENTUM THIS TICK — {name}!",
  "{name} WENT DEAD STOP OUT THERE!",
  "STUCK WITHOUT LIFT THIS TICK — {name}!",
  "{name} CAN'T FIND THE GROOVE AT ALL!",
  "THE SCOREBOARD IGNORED {name} THIS TICK!",
  "{name} IS FROZEN OUT OF THE HUNT AGAIN!",
  "NO POINTS. NO PACE. {name} FROZE!",
  "{name} CAN'T BREAK FREE THIS TICK!",
  "STUCK IN THE MUD AGAIN — {name}!",
  "{name} FROZE ON THE SCORE LINE!",
  "THE RACE MOVED ON — {name} STUCK!",
  "{name} IS STUCK IN THE SLOW ZONE!",
  "NO LIFT ON THE BOARD — {name}!",
  "{name} WENT STONE COLD ON POINTS!",
  "STUCK AT ZERO OUTPUT — {name}!",
  "{name} CAN'T GET BACK IN GEAR THIS TICK!",
  "THE PACE KILLED {name} AGAIN!",
  "{name} IS FROZEN IN THE REAR!",
  "ZERO ACTIVITY THIS TICK — {name}!",
  "{name} FROZE WHEN THE TICK TURNED!",
  "STUCK WITHOUT FORWARD MOTION — {name}!",
  "{name} CAN'T MOVE THE SCORE AT ALL!",
  "THE LEADERBOARD MOVED — {name} DIDN'T!",
  "{name} IS STUCK IN THE FOUL LANE ONCE MORE!",
  "NO GAIN THIS TICK — {name}!",
  "{name} WENT FULL STANDSTILL!",
  "STUCK IN THE PACK ONCE MORE — {name}!",
  "{name} CAN'T FIND ANY TRACTION!",
  "THE TICK WAS EMPTY — {name}!",
  "{name} IS FROZEN OUT THERE AGAIN!",
  "NO MOMENTUM FROM {name} AT ALL!",
  "{name} FROZE SOLID ON THE BOARD!",
  "STUCK BEHIND THE PACE — {name}!",
  "{name} CAN'T GET OFF ZERO!",
  "THE SCORE DIDN'T MOVE — {name}!",
  "{name} IS STUCK IN THE REARVIEW MIRROR!",
  "ZERO POINTS THIS TICK — {name}!",
  "{name} WENT ICE COLD ON THE LEADERBOARD!",
  "STUCK WITHOUT PROGRESS THIS TICK — {name}!",
  "{name} CAN'T GET THE PACE BACK AT ALL!",
  "THE FIELD SCORED — {name} FROZE!",
  "{name} IS STUCK IN THE FOUL PATCH ONCE MORE!",
  "NO TRACTION THIS TICK — {name}!",
  "{name} FROZE WHEN THE RACE HEATED UP!",
  "STUCK IN PLACE AGAIN — {name}!",
  "{name} CAN'T BUY MOMENTUM THIS TICK!",
  "THE PACE PASSED {name} WITHOUT A POINT!",
  "{name} IS FROZEN ON POINTS!",
  "ZERO FORWARD PROGRESS — {name} AGAIN!",
  "{name} WENT DORMANT ON THE BOARD!",
  "STUCK IN THE GRIND — {name}!",
  "{name} CAN'T SHIFT OUT OF THE STALL!",
  "THE SCORE STAYED DEAD — {name}!",
  "{name} IS STUCK IN THE BACK OF THE PACK!",
  "NO LIFT FROM {name} ON THE BOARD!",
  "{name} FROZE UP OUT THERE AGAIN!",
  "STUCK WITHOUT A POINT THIS TICK — {name}!",
  "{name} CAN'T GET THE MOTOR TURNING!",
  "THE RACE ADVANCED — {name} FROZE SOLID!",
  "{name} IS STUCK IN THE FOUL ZONE AGAIN!",
  "NO PACE ON THE BOARD — {name}!",
  "{name} WENT FULL ICE ON POINTS!",
  "STUCK IN THE REAR — {name} AGAIN!",
  "{name} CAN'T FIND FORWARD GEAR!",
  "THE TICK MOVED — {name} STUCK STILL!",
  "{name} IS FROZEN OUT OF THE POINTS RACE!",
  "ZERO OUTPUT AGAIN — {name}!",
  "{name} FROZE WHEN THE FIELD MOVED ON!",
  "STUCK ON THE SCORE LINE — {name}!",
  "{name} CAN'T GET BACK IN THE RACE FLOW!",
  "THE PACE VANISHED — {name} STRANDED AGAIN!",
  "{name} IS STUCK IN THE SHADOWS OF THE PACK!",
  "NO SCORE MOVEMENT THIS TICK — {name}!",
  "{name} WENT COMPLETELY STILL AGAIN!",
  "STUCK WITHOUT THE GAS — {name}!",
  "{name} CAN'T MOVE UP THE LEADERBOARD!",
  "THE FIELD GAINED — {name} FROZE SOLID!",
  "{name} IS STUCK IN THE FOUL WEATHER ONCE MORE!",
  "NO POINTS ON THE TICK — {name}!",
  "{name} FROZE AT THE WRONG MOMENT AGAIN!",
  "STUCK IN THE DRAG ZONE — {name}!",
  "{name} CAN'T GET LOOSE THIS TICK!",
  "THE SCOREBOARD FROZE — {name}!",
  "{name} IS STUCK WITHOUT PACE!",
  "ZERO LIFT THIS TICK — {name}!",
  "{name} WENT FULL PARKING BRAKE AGAIN!",
  "STUCK IN THE FOUL LANE — {name} AGAIN!",
  "{name} CAN'T FIND THE LINE THIS TICK!",
  "THE RACE ROLLED ON — {name} STUCK!",
  "{name} IS FROZEN IN THE BACK HALF!",
  "NO MOMENTUM ON THE TICK — {name}!",
  "{name} FROZE WHEN THE PACE RETURNED!",
  "STUCK AT THE BACK AGAIN — {name}!",
  "{name} CAN'T GET THE NEEDLE TO MOVE!",
  "THE PACE LEFT {name} STANDING STILL!",
  "{name} IS STUCK IN THE REAR GUARD AGAIN!",
  "NO FORWARD MOTION AT ALL — {name}!",
  "{name} WENT DEAD QUIET ON THE BOARD!",
  "STUCK IN THE PACK — {name} CAN'T MOVE!",
  "{name} CAN'T BREAK THE ICE THIS TICK!",
  "THE SCORE STALLED AGAIN FOR {name}!",
  "{name} IS FROZEN OUT OF THE SCRUM AGAIN!",
  "ZERO PACE FROM {name} ON THE BOARD!",
  "{name} FROZE SOLID WHEN THE FIELD MOVED!",
  "STUCK WITHOUT SCORE THIS TICK — {name}!",
  "{name} CAN'T GET BACK ON THE PACE LINE!",
  "THE TICK PASSED — {name} STUCK!",
  "{name} IS STUCK IN THE FOUL PATCH YET AGAIN!",
  "NO TRACTION FROM {name} AT ALL!",
  "{name} WENT FULL FREEZE ON THE BOARD!",
  "STUCK IN NEUTRAL — {name} AGAIN!",
  "{name} CAN'T FIND ANY GEAR THIS TICK!",
  "THE LEADERBOARD ADVANCED — {name} DIDN'T!",
  "{name} IS FROZEN ON THE TICK!",
  "NO POINTS FROM {name} ON THIS TICK!",
  "{name} FROZE UP — THE FIELD MOVED ON!",
  "STUCK BEHIND THE PACE AGAIN — {name}!",
  "{name} CAN'T GET UNFROZEN THIS TICK!",
  "THE SCORE DIDN'T FLINCH — {name}!",
  "{name} IS STUCK IN THE BACKMARK ZONE AGAIN!",
  "ZERO MOMENTUM ON POINTS — {name}!",
  "{name} WENT STONE STILL ON THE BOARD!",
  "STUCK WITHOUT THE PACE — {name}!",
  "{name} CAN'T MOVE FORWARD THIS TICK!",
  "THE RACE HEATED UP — {name} FROZE!",
  "{name} IS STUCK IN THE FOUL LANE ONE MORE TIME!",
  "NO LIFT ON POINTS — {name}!",
  "{name} FROZE WHEN THE LEADERS SCORED!",
  "STUCK IN THE REARVIEW AGAIN — {name}!",
  "{name} CAN'T GET BACK IN THE MIX THIS TICK!",
  "THE PACE KILLED {name}'S SCORE!",
  "{name} IS FROZEN OUT OF THE FLOW!",
  "ZERO FORWARD GROUND — {name}!",
  "{name} WENT ICE COLD ON THE TICK!",
  "STUCK ON ZERO POINTS — {name}!",
  "{name} CAN'T BUY TRACTION THIS TICK!",
  "THE FIELD MOVED FORWARD — {name} STUCK!",
  "{name} IS STUCK IN THE DRAG AGAIN!",
  "NO SCORE ACTIVITY THIS TICK — {name}!",
  "{name} FROZE SOLID AT THE WRONG TIME!",
  "STUCK IN THE SHUFFLE ONE MORE TIME — {name}!",
  "{name} CAN'T GET THE WHEELS TURNING AGAIN!",
  "THE SCORE STAYED FLAT THIS TICK — {name}!",
  "{name} IS FROZEN OUT THERE ON POINTS!",
  "NO GAS THIS TICK — {name}!",
  "{name} WENT FULL STOP AGAIN!",
  "STUCK IN THE MIDDLE OF THE PACK — {name}!",
  "{name} CAN'T FIND MOMENTUM THIS TICK!",
  "THE TICK WAS BRUTAL — {name} FROZE!",
  "{name} IS STUCK IN THE FOUL WEATHER PATCH AGAIN!",
  "ZERO OUTPUT ON THE BOARD — {name}!",
  "{name} FROZE WHEN THE RACE MOVED ON!",
  "STUCK WITHOUT A GEAR — {name}!",
  "{name} CAN'T GET OFF THE MARK THIS TICK!",
  "THE PACE DRIED UP FOR {name} AGAIN!",
  "{name} IS FROZEN IN THE REAR PACK!",
  "NO POINTS LANDED ON THE BOARD — {name}!",
  "{name} WENT DORMANT THIS TICK!",
  "STUCK IN THE GRAVEL — {name}!",
  "{name} CAN'T MOVE THE LEADERBOARD LINE!",
  "THE RACE SCORED AROUND {name} — THEY DIDN'T!",
  "{name} IS STUCK IN THE FOUL ZONE ONE MORE TIME!",
  "NO TRACTION ON POINTS — {name}!",
  "{name} FROZE UP ON THE SCOREBOARD!",
  "STUCK AT ZERO AGAIN — {name}!",
  "{name} CAN'T FIND THE PACE THIS TICK!",
  "THE FIELD SURGED — {name} STUCK!",
  "{name} IS FROZEN OUT OF THE POINT RACE AGAIN!",
  "ZERO LIFT ON THE TICK — {name}!",
  "{name} WENT COMPLETELY FLAT THIS TICK!",
  "STUCK IN THE BACK HALF — {name}!",
  "{name} CAN'T GET BACK ON THE GAS THIS TICK!",
  "THE SCOREBOARD SKIPPED {name} AGAIN!",
  "{name} IS STUCK WITHOUT FORWARD MOTION!",
  "NO MOMENTUM FROM {name} ON THIS TICK!",
  "{name} FROZE WHEN THE PACK MOVED!",
  "STUCK IN THE FOUL PATCH ONE LAST TIME — {name}!",
  "{name} CAN'T BREAK THE STALL THIS TICK!",
  "THE PACE LEFT {name} BEHIND AGAIN!",
  "{name} IS FROZEN SOLID OUT THERE AGAIN!",
  "NO POINTS THIS TICK AT ALL — {name}!",
  "{name} WENT FULL ICE OUT THERE AGAIN!",
  "STUCK WITHOUT LIFT — {name} ONE MORE TIME!",
  "{name} CAN'T GET THE PACE LINE BACK THIS TICK!",
  "THE RACE MOVED — {name} STUCK FROZEN!",
  "{name} IS STUCK IN THE REAR ONE MORE TIME!",
  "ZERO PACE THIS TICK — {name}!",
  "{name} FROZE ON THE BOARD AGAIN!",
  "STUCK IN THE PACK — {name} FROZE SOLID!",
  "{name} CAN'T FIND THE GROOVE THIS TICK!",
  "THE SCORE DIDN'T TICK — {name}!",
  "{name} IS FROZEN OUT OF THE HUNT THIS TICK!",
  "NO FORWARD PROGRESS ON THE BOARD — {name}!",
  "{name} WENT DEAD STOP THIS TICK!",
  "STUCK BEHIND THE LEAD GROUP — {name}!",
  "{name} CAN'T GET BACK IN THE HUNT THIS TICK!",
  "THE TICK FORGOT TO SCORE {name}!",
  "{name} IS STUCK IN THE FOUL LANE — NO POINTS!",
  "NO LIFT FROM {name} THIS TICK AT ALL!",
  "{name} FROZE SOLID — LONG STALL CONFIRMED!",
] as const;

export const STALL_TOP_PHRASES = [
  "{name} STALLED IN THE TOP FOUR!",
  "WALL HIT! {name} BARELY MOVED!",
  "{name} STALLED UP FRONT — DRAMA!",
  "TOP FOUR STALL — {name} STUCK!",
  "{name} BARELY SCORED THIS TICK!",
  "STALL UP FRONT — {name} FROZE!",
  "{name} HIT A SPEED BUMP IN P{rank}!",
  "LEADER PACK STALL — {name}!",
  "{name} COULDN'T BUY A POINT!",
  "STALLED NEAR THE FRONT — {name}!",
  "{name} STUCK IN THE TOP GROUP!",
  "MINIMAL OUTPUT FROM {name} UP FRONT!",
  "{name} STALLED — TOP FOUR DRAMA!",
  "UP FRONT AND STUCK — {name}!",
  "THE LEAD GROUP STALLED — {name}!",
  "{name} BARELY TICKED THE SCOREBOARD!",
  "STALL IN THE HUNT — {name}!",
  "{name} FROZE NEAR THE FRONT!",
  "TOP FOUR TROUBLE — {name} STALLED!",
  "{name} STOPPED MOVING UP FRONT!",
  "{name} FROZE IN P{rank} — LEADER PACK DRAMA!",
  "UP FRONT AND MOTIONLESS — {name}!",
  "{name} CAN'T BUY A POINT IN P{rank}!",
  "THE HUNT STALLED — {name} IN P{rank}!",
  "{name} WENT QUIET UP FRONT!",
  "LEADER PACK GRIDLOCK — {name}!",
  "{name} STUCK IN THE FRONT FOUR!",
  "NO PACE FROM THE FRONT — {name}!",
  "{name} FROZE AMONG THE LEADERS!",
  "TOP GROUP STANDSTILL — {name}!",
  "{name} BARELY MOVED IN P{rank}!",
  "UP FRONT ICE COLD — {name}!",
  "{name} HIT A WALL IN THE LEAD PACK!",
  "THE FRONT FOUR STALLED — {name}!",
  "{name} COULDN'T FIND A GEAR UP FRONT!",
  "STUCK IN THE HUNT — {name} P{rank}!",
  "{name} WENT FLAT NEAR THE FRONT!",
  "LEADER PACK TROUBLE — {name}!",
  "{name} FROZE IN THE TOP GROUP!",
  "MINIMAL GAIN UP FRONT — {name}!",
  "{name} STUCK IN P{rank} — DRAMA!",
  "THE POINT LEADERS STALLED — {name}!",
  "{name} CAN'T PUSH IN THE FRONT FOUR!",
  "UP FRONT DEAD STOP — {name}!",
  "{name} FROZE ON THE LEAD LAP!",
  "TOP FOUR FREEZE — {name}!",
  "{name} WENT NOWHERE IN P{rank}!",
  "THE HUNT WENT QUIET — {name}!",
  "{name} STUCK AMONG THE LEADERS!",
  "LEADER PACK PAUSE — {name}!",
  "{name} BARELY GAINED IN P{rank}!",
  "UP FRONT STRANDED — {name}!",
  "{name} FROZE IN THE LEAD SCRUM!",
  "THE FRONT STALLED OUT — {name}!",
  "{name} CAN'T MOVE UP FRONT!",
  "STUCK IN P{rank} — {name} UP FRONT!",
  "{name} WENT DORMANT IN THE HUNT!",
  "LEADER PACK STUCK — {name}!",
  "{name} FROZE AT THE SHARP END!",
  "TOP FOUR STANDSTILL — {name}!",
  "{name} HIT NEUTRAL UP FRONT!",
  "THE LEAD GROUP WENT FLAT — {name}!",
  "{name} CAN'T FIND PACE IN P{rank}!",
  "UP FRONT GRIDLOCK — {name}!",
  "{name} STUCK IN THE POINT HUNT!",
  "MINIMAL TICK UP FRONT — {name}!",
  "{name} FROZE IN THE LEADER PACK!",
  "THE HUNT HIT A WALL — {name}!",
  "{name} WENT ICE COLD IN P{rank}!",
  "STUCK NEAR THE POINT — {name}!",
  "{name} CAN'T BUY TRACTION UP FRONT!",
  "LEADER PACK DEAD STOP — {name}!",
  "{name} FROZE ON THE SHARP END!",
  "TOP GROUP TROUBLE — {name}!",
  "{name} BARELY MOVED AMONG THE LEADERS!",
  "UP FRONT PARALYSIS — {name}!",
  "{name} STUCK IN THE FRONT RUNNERS!",
  "THE LEAD PACK STALLED — {name}!",
  "{name} WENT QUIET IN P{rank}!",
  "STUCK IN THE HUNT — {name}!",
  "{name} FROZE UP FRONT AGAIN!",
  "LEADER PACK MOTIONLESS — {name}!",
  "{name} CAN'T SHIFT IN P{rank}!",
  "TOP FOUR DEAD STOP — {name}!",
  "{name} HIT A DEAD PATCH UP FRONT!",
  "THE FRONT FOUR WENT FLAT — {name}!",
  "{name} STUCK IN THE LEAD SCRUM!",
  "UP FRONT ZERO OUTPUT — {name}!",
  "{name} FROZE IN THE TOP FOUR!",
  "THE HUNT STALLED OUT — {name}!",
  "{name} CAN'T GET GOING IN P{rank}!",
  "LEADER PACK ICE COLD — {name}!",
  "{name} WENT STILL UP FRONT!",
  "STUCK AT THE SHARP END — {name}!",
  "{name} BARELY TICKED UP FRONT!",
  "TOP GROUP DEAD STOP — {name}!",
  "{name} FROZE IN THE POINT HUNT!",
  "UP FRONT NO TRACTION — {name}!",
  "{name} STUCK IN P{rank} UP FRONT!",
  "THE LEADERS WENT QUIET — {name}!",
  "{name} CAN'T MOVE THE LEAD PACK!",
  "STALL AT THE FRONT — {name} P{rank}!",
  "{name} WENT FLAT IN THE TOP GROUP!",
  "LEADER PACK STANDSTILL — {name}!",
  "{name} FROZE AMONG THE FRONT RUNNERS!",
  "TOP FOUR GRIDLOCK — {name}!",
  "{name} HIT A BRICK WALL IN P{rank}!",
  "UP FRONT STRANDED AGAIN — {name}!",
  "{name} CAN'T FIND LIFT UP FRONT!",
  "THE HUNT WENT COLD — {name}!",
  "{name} STUCK IN THE LEAD FOUR!",
  "MINIMAL PACE UP FRONT — {name}!",
  "{name} FROZE ON THE FRONT FOOT!",
  "LEADER PACK FLATLINED — {name}!",
  "{name} WENT NOWHERE UP FRONT!",
  "STUCK IN THE TOP SCRUM — {name}!",
  "{name} CAN'T BUY MOMENTUM IN P{rank}!",
  "TOP FOUR ICE COLD — {name}!",
  "{name} FROZE IN THE LEAD HUNT!",
  "UP FRONT DEAD QUIET — {name}!",
  "{name} STUCK AT P{rank} UP FRONT!",
  "THE LEAD GROUP WENT STILL — {name}!",
  "{name} BARELY SCORED IN P{rank}!",
  "STALL IN P{rank} — {name} UP FRONT!",
  "{name} CAN'T PUSH UP FRONT!",
  "LEADER PACK STUCK SOLID — {name}!",
  "{name} FROZE IN THE FRONT PACK!",
  "TOP FOUR MOTIONLESS — {name}!",
  "{name} WENT DORMANT UP FRONT!",
  "STUCK IN THE LEAD HUNT — {name}!",
  "{name} HIT NEUTRAL IN P{rank}!",
  "UP FRONT NO GAS — {name}!",
  "{name} CAN'T FIND THE LINE UP FRONT!",
  "THE POINT HUNT STALLED — {name}!",
  "{name} FROZE AT P{rank}!",
  "LEADER PACK ZERO OUTPUT — {name}!",
  "{name} STUCK IN THE SHARP END!",
  "TOP GROUP STUCK — {name}!",
  "{name} WENT ICE COLD UP FRONT!",
  "STALL UP FRONT IN P{rank} — {name}!",
  "{name} CAN'T GET TRACTION IN THE HUNT!",
  "THE FRONT RUNNERS STALLED — {name}!",
  "{name} FROZE IN P{rank} — UP FRONT!",
  "UP FRONT LOCKED UP — {name}!",
  "{name} BARELY MOVED UP FRONT!",
  "LEADER PACK NO PACE — {name}!",
  "{name} STUCK ON THE SHARP END!",
  "TOP FOUR QUIET — {name}!",
  "{name} WENT FLAT AT P{rank}!",
  "STUCK AMONG THE LEADERS — {name}!",
  "{name} CAN'T SHIFT UP FRONT!",
  "THE HUNT WENT STILL — {name}!",
  "{name} FROZE IN THE LEAD GROUP!",
  "UP FRONT STANDSTILL — {name}!",
  "{name} HIT A WALL UP FRONT!",
  "LEADER PACK CAN'T MOVE — {name}!",
  "{name} STUCK IN P{rank} NEAR THE FRONT!",
  "TOP FOUR NO TRACTION — {name}!",
  "{name} WENT DEAD STOP UP FRONT!",
  "STUCK IN THE FRONT HUNT — {name}!",
  "{name} FROZE ON THE LEAD BOARD!",
  "UP FRONT MINIMAL OUTPUT — {name}!",
  "{name} CAN'T BUY A TICK IN P{rank}!",
  "THE LEAD PACK WENT QUIET — {name}!",
  "{name} STUCK IN THE TOP HUNT!",
  "STALL NEAR P{rank} — {name}!",
  "{name} FROZE AMONG THE POINT LEADERS!",
  "TOP GROUP NO PACE — {name}!",
  "{name} WENT STILL IN P{rank}!",
  "UP FRONT FROZEN SOLID — {name}!",
  "{name} CAN'T MOVE IN THE LEAD PACK!",
  "THE HUNT HIT NEUTRAL — {name}!",
  "{name} STUCK UP FRONT IN P{rank}!",
  "LEADER PACK STALLED OUT — {name}!",
  "{name} BARELY GAINED UP FRONT!",
  "TOP FOUR LOCKED — {name}!",
  "{name} FROZE IN THE FRONT HUNT!",
  "STUCK AT THE FRONT — {name} P{rank}!",
  "{name} CAN'T FIND GAS UP FRONT!",
  "UP FRONT FLATLINED — {name}!",
  "{name} WENT QUIET IN THE LEAD PACK!",
  "THE SHARP END STALLED — {name}!",
  "{name} STUCK IN THE LEAD SCRAMBLE!",
  "TOP FOUR DEAD QUIET — {name}!",
  "{name} FROZE UP FRONT IN P{rank}!",
  "STALL IN THE LEAD GROUP — {name}!",
  "{name} CAN'T PUSH IN P{rank}!",
  "UP FRONT NO LIFT — {name}!",
  "{name} HIT A DEAD STOP IN P{rank}!",
  "LEADER PACK WENT FLAT — {name}!",
  "{name} STUCK AMONG THE TOP FOUR!",
  "THE FRONT HUNT WENT COLD — {name}!",
  "{name} FROZE ON THE HUNT!",
  "STUCK IN P{rank} — UP FRONT DRAMA!",
  "{name} CAN'T GET LOOSE UP FRONT!",
  "TOP GROUP GRIDLOCK — {name}!",
  "{name} WENT ICE IN THE LEAD PACK!",
  "UP FRONT STALLED SOLID — {name}!",
  "{name} BARELY MOVED ON THE SHARP END!",
  "THE LEADERS STUCK — {name}!",
  "{name} FROZE IN THE TOP HUNT!",
  "STALL UP FRONT — {name} IN P{rank}!",
  "{name} CAN'T FIND PACE UP FRONT!",
  "LEADER PACK STILL — {name}!",
  "{name} STUCK IN THE FRONT SCRUM!",
  "TOP FOUR WENT QUIET — {name}!",
  "{name} FROZE AT THE FRONT!",
  "UP FRONT NO MOMENTUM — {name}!",
  "{name} HIT GRIDLOCK IN P{rank}!",
  "THE HUNT STUCK — {name}!",
  "{name} CAN'T MOVE AMONG THE LEADERS!",
  "STALL ON THE SHARP END — {name}!",
  "{name} WENT FLAT UP FRONT!",
  "LEADER PACK STUCK IN P{rank} — {name}!",
  "{name} FROZE IN THE FRONT SCRUM!",
  "TOP FOUR STILL — {name}!",
  "{name} STUCK UP FRONT — NO POINTS!",
  "UP FRONT CAN'T MOVE — {name}!",
  "{name} BARELY TICKED IN P{rank}!",
  "THE LEAD GROUP ICE COLD — {name}!",
  "{name} FROZE IN THE HUNT!",
  "STUCK IN THE TOP FOUR — {name}!",
  "{name} CAN'T SHIFT IN THE LEAD PACK!",
  "UP FRONT DEAD PATCH — {name}!",
  "{name} WENT NEUTRAL UP FRONT!",
  "LEADER PACK STRANDED — {name}!",
  "{name} STUCK IN P{rank} — FRONT DRAMA!",
  "TOP GROUP STALLED — {name}!",
  "{name} FROZE NEAR P{rank}!",
  "STALL AMONG THE LEADERS — {name}!",
  "{name} CAN'T BUY PACE UP FRONT!",
  "UP FRONT ZERO GAIN — {name}!",
  "{name} HIT A STANDSTILL IN P{rank}!",
  "THE FRONT PACK STALLED — {name}!",
  "{name} FROZE UP FRONT ON POINTS!",
  "STUCK IN THE LEAD SCRAMBLE — {name}!",
  "{name} WENT DORMANT IN P{rank}!",
  "TOP FOUR STRANDED — {name}!",
  "{name} CAN'T GET OFF NEUTRAL UP FRONT!",
  "LEADER PACK QUIET — {name}!",
  "{name} STUCK ON THE SHARP END!",
  "UP FRONT STALL ALERT — {name}!",
  "{name} FROZE IN P{rank} UP FRONT!",
  "THE HUNT LOCKED UP — {name}!",
  "{name} BARELY MOVED IN THE LEAD PACK!",
  "STUCK UP FRONT — {name} IN P{rank}!",
  "{name} CAN'T FIND TRACTION IN P{rank}!",
  "TOP FOUR DEAD STOP IN PLAY — {name}!",
  "{name} WENT STILL AMONG THE LEADERS!",
  "UP FRONT NO SCORE — {name}!",
  "{name} FROZE IN THE LEAD SCRAMBLE!",
  "LEADER PACK MINIMAL OUTPUT — {name}!",
  "{name} STUCK IN THE FRONT FOUR AGAIN!",
  "STALL AT P{rank} — {name}!",
  "{name} CAN'T MOVE THE HUNT!",
  "THE SHARP END WENT QUIET — {name}!",
  "{name} FROZE UP FRONT — P{rank}!",
  "UP FRONT STUCK SOLID — {name}!",
  "{name} HIT ICE IN P{rank}!",
  "TOP GROUP DEAD QUIET — {name}!",
  "{name} CAN'T PUSH UP FRONT THIS TICK!",
  "LEADER PACK FROZEN — {name}!",
  "{name} STUCK IN THE TOP SCRUM!",
  "STALL IN THE FRONT PACK — {name}!",
  "{name} WENT FLAT IN P{rank}!",
  "UP FRONT MOTIONLESS — {name}!",
  "{name} FROZE AMONG THE HUNT!",
  "THE LEAD FOUR STALLED — {name}!",
  "{name} CAN'T BUY LIFT UP FRONT!",
  "STUCK IN P{rank} — LEADER DRAMA!",
  "{name} BARELY SCORED UP FRONT!",
  "TOP FOUR FROZEN — {name}!",
  "{name} WENT DEAD QUIET IN P{rank}!",
  "UP FRONT STANDSTILL — {name}!",
  "{name} STUCK IN THE LEAD HUNT!",
  "LEADER PACK NO LIFT — {name}!",
  "{name} FROZE ON THE FRONT LINE!",
  "STALL UP FRONT — {name} STUCK!",
  "{name} CAN'T GET GOING UP FRONT!",
  "THE HUNT DEAD STOP — {name}!",
  "{name} STUCK AT THE FRONT IN P{rank}!",
  "TOP GROUP ICE COLD — {name}!",
  "{name} WENT NEUTRAL IN P{rank}!",
  "UP FRONT CAN'T BUY A POINT — {name}!",
  "{name} FROZE IN THE LEADER SCRUM!",
  "LEADER PACK STUCK UP FRONT — {name}!",
  "{name} HIT A PAUSE IN P{rank}!",
  "STUCK NEAR THE LEAD — {name}!",
  "{name} CAN'T MOVE IN P{rank}!",
  "TOP FOUR WENT STILL — {name}!",
  "{name} FROZE UP FRONT — NO PACE!",
  "UP FRONT GRIND TO A HALT — {name}!",
  "{name} STUCK IN THE POINT LEADERS!",
  "THE LEAD PACK MOTIONLESS — {name}!",
  "{name} BARELY MOVED ON THE HUNT!",
  "STALL IN THE TOP GROUP — {name}!",
  "{name} CAN'T SHIFT UP FRONT THIS TICK!",
  "UP FRONT ICE IN P{rank} — {name}!",
  "{name} FROZE IN THE FRONT LINE!",
  "LEADER PACK DEAD QUIET — {name}!",
  "{name} STUCK UP FRONT — P{rank} DRAMA!",
  "TOP FOUR NO GAS — {name}!",
  "{name} WENT FLAT AMONG THE LEADERS!",
  "STUCK ON THE HUNT — {name}!",
  "{name} CAN'T FIND THE FRONT LINE!",
  "UP FRONT STALLED IN P{rank} — {name}!",
  "{name} FROZE IN THE LEAD LINE!",
  "THE FRONT HUNT STUCK — {name}!",
  "{name} STUCK IN P{rank} — TOP DRAMA!",
  "LEADER PACK STILL IN P{rank} — {name}!",
  "{name} WENT QUIET ON THE SHARP END!",
  "STALL UP FRONT — {name} FROZE!",
  "{name} CAN'T MOVE THE FRONT PACK!",
  "TOP FOUR PAUSE — {name}!",
  "{name} FROZE AT THE SHARP END!",
  "UP FRONT LOCKED IN P{rank} — {name}!",
  "{name} STUCK IN THE LEAD LINE!",
  "THE HUNT ICE COLD — {name}!",
  "{name} BARELY GAINED ON THE SHARP END!",
  "STUCK UP FRONT — {name}!",
  "{name} CAN'T BUY POINTS IN P{rank}!",
  "LEADER PACK FLAT — {name}!",
  "{name} FROZE IN THE FRONT LINEUP!",
  "TOP FOUR STUCK SOLID — {name}!",
  "{name} WENT DEAD IN P{rank}!",
  "UP FRONT NO OUTPUT — {name}!",
  "{name} STUCK AMONG THE TOP GROUP!",
  "STALL ON THE HUNT — {name} P{rank}!",
  "{name} CAN'T GET TRACTION UP FRONT!",
  "THE LEAD SCRUM STALLED — {name}!",
  "{name} FROZE UP FRONT THIS TICK!",
  "STUCK IN THE FRONT LINE — {name}!",
  "{name} HIT A FREEZE IN P{rank}!",
  "UP FRONT STALLED — {name}!",
  "{name} CAN'T MOVE ON THE SHARP END!",
  "LEADER PACK STANDSTILL IN P{rank} — {name}!",
  "{name} WENT STILL UP FRONT IN P{rank}!",
  "TOP FOUR MOTIONLESS IN P{rank} — {name}!",
  "{name} FROZE IN THE TOP LINEUP!",
  "STUCK UP FRONT — MINIMAL FROM {name}!",
  "{name} CAN'T PUSH THE LEAD PACK!",
  "UP FRONT DEAD IN P{rank} — {name}!",
  "{name} STUCK IN THE HUNT AT P{rank}!",
  "THE FRONT STALL — {name}!",
  "{name} FROZE ON THE HUNT IN P{rank}!",
  "LEADER PACK STUCK — {name} P{rank}!",
  "{name} WENT ICE UP FRONT IN P{rank}!",
  "STALL IN THE LEAD LINE — {name}!",
  "{name} CAN'T FIND MOMENTUM UP FRONT!",
  "TOP GROUP STILL — {name} IN P{rank}!",
  "{name} STUCK UP FRONT — LEADER PACK!",
  "UP FRONT FROZEN — {name} P{rank}!",
  "{name} BARELY MOVED ON THE HUNT!",
  "THE SHARP END STALL — {name}!",
  "{name} FROZE IN P{rank} — FRONT PACK!",
  "STUCK IN THE LEAD LINEUP — {name}!",
  "{name} CAN'T SHIFT ON THE SHARP END!",
  "UP FRONT STALL IN P{rank} — {name}!",
  "{name} WENT FLAT ON THE HUNT!",
  "LEADER PACK ICE — {name}!",
  "{name} STUCK UP FRONT — NO LIFT!",
  "TOP FOUR STALL OUT — {name}!",
  "{name} FROZE AMONG THE HUNT!",
  "STUCK AT P{rank} — {name} UP FRONT!",
  "{name} CAN'T MOVE UP FRONT IN P{rank}!",
  "UP FRONT QUIET — {name}!",
  "{name} HIT STANDSTILL UP FRONT!",
  "THE LEAD HUNT FROZE — {name}!",
  "{name} STUCK IN P{rank} — SHARP END!",
  "STALL UP FRONT THIS TICK — {name}!",
  "{name} CAN'T BUY A POINT UP FRONT!",
  "TOP GROUP STALLED IN P{rank} — {name}!",
  "{name} FROZE ON THE FRONT PACK!",
  "UP FRONT STRANDED IN P{rank} — {name}!",
  "{name} STUCK IN THE LEAD LINEUP!",
  "LEADER PACK CAN'T SHIFT — {name}!",
  "{name} WENT DEAD STOP IN P{rank}!",
  "STUCK UP FRONT — {name} FROZE IN P{rank}!",
  "{name} CAN'T GET PACE IN THE HUNT!",
  "TOP FOUR FLAT — {name}!",
  "{name} FROZE UP FRONT AMONG LEADERS!",
  "UP FRONT STUCK IN P{rank} — {name}!",
  "{name} BARELY TICKED UP FRONT IN P{rank}!",
  "THE HUNT STALL — {name} P{rank}!",
  "{name} STUCK ON THE FRONT FOOT!",
  "LEADER PACK STALLED THIS TICK — {name}!",
  "{name} CAN'T MOVE IN THE HUNT!",
  "STALL AT THE SHARP END — {name}!",
  "{name} FROZE UP FRONT — STUCK!",
  "UP FRONT NO TICK — {name}!",
  "{name} STUCK IN P{rank} — HUNT DRAMA!",
  "TOP FOUR STUCK IN P{rank} — {name}!",
  "{name} WENT QUIET AT THE FRONT!",
  "STUCK IN THE LEAD SCRUM — {name}!",
  "{name} CAN'T PUSH UP FRONT IN P{rank}!",
  "UP FRONT ICE IN THE HUNT — {name}!",
  "{name} FROZE IN THE TOP LINE!",
  "LEADER PACK STUCK THIS TICK — {name}!",
  "{name} STUCK UP FRONT AT P{rank}!",
  "THE FRONT LINE STALLED — {name}!",
  "{name} CAN'T FIND LIFT IN P{rank}!",
  "STALL UP FRONT — {name} IN THE HUNT!",
  "{name} WENT FLAT ON THE SHARP END!",
  "UP FRONT DEAD IN THE HUNT — {name}!",
  "{name} FROZE IN P{rank} THIS TICK!",
  "TOP GROUP STUCK UP FRONT — {name}!",
  "{name} STUCK AMONG LEADERS IN P{rank}!",
  "STALL IN P{rank} UP FRONT — {name}!",
  "{name} CAN'T GET OFF NEUTRAL IN P{rank}!",
  "UP FRONT STILL — {name}!",
  "{name} FROZE ON THE SHARP END IN P{rank}!",
  "LEADER PACK NO TICK — {name}!",
  "{name} STUCK UP FRONT — P{rank}!",
  "THE HUNT WENT DEAD — {name}!",
  "{name} CAN'T MOVE THE SHARP END!",
  "STUCK IN P{rank} UP FRONT — {name}!",
  "{name} FROZE IN THE LEAD HUNT AT P{rank}!",
  "TOP FOUR STUCK — {name} IN P{rank}!",
  "{name} WENT ICE ON THE HUNT!",
  "UP FRONT STALL DRAMA — {name}!",
  "{name} STUCK IN THE FRONT HUNT AT P{rank}!",
  "LEADER PACK FROZEN IN P{rank} — {name}!",
  "{name} CAN'T BUY TRACTION IN P{rank}!",
  "STALL NEAR THE FRONT — {name} P{rank}!",
  "{name} FROZE UP FRONT ON THE HUNT!",
  "UP FRONT MINIMAL FROM {name}!",
  "{name} STUCK IN P{rank} — LEAD DRAMA!",
  "TOP GROUP STALL — {name} P{rank}!",
  "{name} WENT STILL ON THE SHARP END!",
  "STUCK UP FRONT IN THE HUNT — {name}!",
  "{name} CAN'T SHIFT THE LEAD PACK!",
  "THE FRONT STALL IN P{rank} — {name}!",
  "{name} FROZE AMONG LEADERS AT P{rank}!",
  "UP FRONT LOCKED — {name}!",
  "{name} STUCK IN THE TOP LINE AT P{rank}!",
  "LEADER PACK STALL IN P{rank} — {name}!",
  "{name} CAN'T MOVE UP FRONT AT P{rank}!",
  "STALL UP FRONT — {name} AT P{rank}!",
  "{name} FROZE IN THE HUNT AT P{rank}!",
  "TOP FOUR QUIET IN P{rank} — {name}!",
  "{name} STUCK UP FRONT THIS TICK!",
  "UP FRONT DEAD STOP IN P{rank} — {name}!",
  "{name} CAN'T GET GOING IN THE HUNT!",
  "THE LEAD LINE STALLED — {name}!",
  "{name} FROZE UP FRONT IN THE PACK!",
  "STUCK IN THE HUNT AT P{rank} — {name}!",
  "{name} WENT NEUTRAL ON THE SHARP END!",
  "UP FRONT STALL — {name} P{rank}!",
  "{name} CAN'T FIND PACE IN THE HUNT!",
  "LEADER PACK STUCK AT P{rank} — {name}!",
  "{name} FROZE ON THE FRONT HUNT!",
  "TOP FOUR DEAD IN P{rank} — {name}!",
  "{name} STUCK UP FRONT — HUNT STALL!",
  "STALL IN THE FRONT HUNT — {name}!",
  "{name} CAN'T PUSH AT P{rank}!",
  "UP FRONT FROZEN IN P{rank} — {name}!",
  "{name} WENT FLAT IN THE LEAD PACK!",
  "THE SHARP END ICE — {name}!",
  "{name} STUCK IN P{rank} ON THE HUNT!",
  "LEADER PACK STILL THIS TICK — {name}!",
  "{name} FROZE UP FRONT IN THE SCRUM!",
  "STUCK AT THE FRONT — {name}!",
  "{name} CAN'T BUY A TICK UP FRONT!",
  "UP FRONT STALL TICK — {name}!",
  "{name} HIT ICE UP FRONT IN P{rank}!",
  "TOP FOUR STANDSTILL IN P{rank} — {name}!",
  "{name} STUCK IN THE LEAD SCRUM AT P{rank}!",
  "STALL UP FRONT — LEADER PACK {name}!",
  "{name} CAN'T MOVE IN THE TOP FOUR!",
  "UP FRONT NO PACE IN P{rank} — {name}!",
  "{name} FROZE IN THE FRONT HUNT AT P{rank}!",
  "THE HUNT STALL IN P{rank} — {name}!",
  "{name} STUCK UP FRONT — ICE COLD!",
  "LEADER PACK DEAD IN P{rank} — {name}!",
  "{name} CAN'T GET TRACTION ON THE HUNT!",
  "STUCK IN P{rank} — {name} FRONT STALL!",
  "{name} WENT DEAD QUIET UP FRONT!",
  "UP FRONT STUCK — {name} IN P{rank}!",
  "{name} FROZE IN THE TOP SCRUM AT P{rank}!",
  "TOP FOUR ICE IN P{rank} — {name}!",
  "{name} STUCK ON THE HUNT AT P{rank}!",
  "STALL UP FRONT — {name} NO PACE!",
  "{name} CAN'T SHIFT IN THE HUNT!",
  "UP FRONT FLAT IN P{rank} — {name}!",
  "{name} FROZE AT THE FRONT IN P{rank}!",
  "LEADER PACK STUCK ON THE HUNT — {name}!",
  "{name} STUCK IN THE FRONT AT P{rank}!",
  "THE HUNT FROZE IN P{rank} — {name}!",
  "{name} CAN'T MOVE UP FRONT ON THE HUNT!",
  "STALL IN THE TOP FOUR — {name} P{rank}!",
  "{name} WENT STILL IN THE LEAD PACK!",
  "UP FRONT STUCK ON THE HUNT — {name}!",
  "{name} FROZE UP FRONT AT THE SHARP END!",
  "TOP GROUP STALL IN P{rank} — {name}!",
  "{name} STUCK IN P{rank} — UP FRONT STALL!",
  "LEADER PACK ICE UP FRONT — {name}!",
  "{name} CAN'T BUY PACE IN P{rank}!",
  "STUCK UP FRONT — {name} NO TICK!",
  "{name} FROZE IN P{rank} ON THE HUNT!",
  "UP FRONT STALL IN THE HUNT — {name}!",
  "{name} WENT ICE IN P{rank} UP FRONT!",
  "THE FRONT HUNT ICE — {name}!",
  "{name} STUCK UP FRONT IN THE PACK!",
  "STALL AT THE FRONT — {name}!",
  "{name} CAN'T GET LOOSE IN P{rank}!",
  "UP FRONT DEAD ON THE HUNT — {name}!",
  "{name} FROZE IN THE LEAD AT P{rank}!",
  "TOP FOUR STUCK ON THE HUNT — {name}!",
  "{name} STUCK UP FRONT — FROZEN!",
  "LEADER PACK STALL ON THE HUNT — {name}!",
  "{name} CAN'T MOVE AT P{rank} UP FRONT!",
  "STALL UP FRONT IN THE PACK — {name}!",
  "{name} WENT FLAT UP FRONT IN P{rank}!",
  "UP FRONT STUCK AT P{rank} — {name}!",
  "{name} FROZE ON THE HUNT UP FRONT!",
  "THE LEAD PACK STUCK — {name}!",
  "{name} STUCK IN P{rank} — FRONT ICE!",
  "STALL UP FRONT — {name} FROZEN!",
  "{name} CAN'T PUSH UP FRONT AT P{rank}!",
  "UP FRONT STILL IN P{rank} — {name}!",
  "{name} FROZE IN THE PACK AT P{rank}!",
  "TOP FOUR STUCK AT P{rank} — {name}!",
  "{name} STUCK UP FRONT — DEAD STOP!",
  "LEADER PACK FROZE UP FRONT — {name}!",
  "{name} CAN'T FIND TRACTION UP FRONT!",
  "STUCK IN P{rank} — {name} UP FRONT STALL!",
  "{name} WENT NEUTRAL UP FRONT IN P{rank}!",
  "UP FRONT STALL AT P{rank} — {name}!",
  "{name} FROZE UP FRONT IN P{rank} THIS TICK!",
] as const;

export const RESTART_PHRASES = [
  "{name} BACK ON THE TRACK — BIG RESTART!",
  "{name} ROARS BACK TO LIFE!",
  "AFTER THE STALL — {name} IS MOVING AGAIN!",
  "RESTART! {name} BACK IN BUSINESS!",
  "{name} RECOVERED FROM THE STALL!",
  "BACK IN MOTION — {name} RESTART!",
  "{name} SHOOK OFF THE STALL!",
  "LIFE AFTER STALL — {name} MOVING!",
  "{name} RESTARTED WITH AUTHORITY!",
  "THE STALL IS OVER — {name} GOES!",
  "{name} BACK ON THE GAS!",
  "RESTART ENERGY FROM {name}!",
  "{name} WOKE BACK UP OUT THERE!",
  "SECOND WIND — {name} RESTART!",
  "{name} BACK IN THE FIGHT!",
  "RESTART COMPLETE — {name}!",
  "{name} REFUSED TO STAY STALLED!",
  "BACK FROM THE DEAD — {name}!",
  "{name} UNFREEZED — BIG RESTART!",
  "MOMENTUM RESTORED — {name}!",
  "{name} FOUND THE GEAR AGAIN!",
  "THE FREEZE IS OVER — {name} MOVES!",
  "{name} BACK ON THE PACE LINE!",
  "RESTART CONFIRMED — {name}!",
  "{name} SHOOK OFF THE FREEZE!",
  "BACK IN GEAR — {name}!",
  "{name} UNLOCKED OUT THERE!",
  "THE MOTOR'S BACK — {name}!",
  "{name} BACK ON THE THROTTLE!",
  "RESTART SURGE FROM {name}!",
  "{name} ESCAPED THE STANDSTILL!",
  "BACK ON THE GAS PEDAL — {name}!",
  "{name} WOKE UP AND WENT!",
  "THE PAUSE IS OVER — {name}!",
  "{name} BACK IN MOTION!",
  "RESTART FIRE FROM {name}!",
  "{name} BROKE FREE OUT THERE!",
  "BACK ON THE ATTACK — {name}!",
  "{name} UNFROZE AND FIRED!",
  "THE WHEELS SPIN AGAIN — {name}!",
  "{name} BACK ON THE SCOREBOARD!",
  "RESTART MOMENTUM — {name}!",
  "{name} CLIMBED OUT OF THE HOLE!",
  "BACK FROM THE ICE — {name}!",
  "{name} GOT THE ENGINE BACK!",
  "THE STANDSTILL ENDED — {name}!",
  "{name} BACK IN THE SCRUM!",
  "RESTART HEAT — {name}!",
  "{name} REFUSED TO STAY FROZEN!",
  "BACK ON POINTS — {name}!",
  "{name} UNSTUCK OUT THERE!",
  "THE GRIDLOCK BROKE — {name}!",
  "{name} BACK ON THE MOVE!",
  "RESTART ALERT — {name}!",
  "{name} SHOOK THE RUST OFF!",
  "BACK IN THE HUNT — {name}!",
  "{name} FOUND TRACTION AGAIN!",
  "THE FREEZE BROKE — {name}!",
  "{name} BACK ON THE PACE!",
  "RESTART POWER — {name}!",
  "{name} ESCAPED THE MUD!",
  "BACK FROM PARKED — {name}!",
  "{name} UNLOCKED THE PACE!",
  "THE HAND BRAKE IS OFF — {name}!",
  "{name} BACK IN THE MIX!",
  "RESTART CONFIRMED — {name} MOVING!",
  "{name} WOKE UP ON THE BOARD!",
  "BACK ON THE LEADERBOARD — {name}!",
  "{name} SHOOK OFF THE PAUSE!",
  "THE STALL CYCLE ENDED — {name}!",
  "{name} BACK WITH AUTHORITY!",
  "RESTART ENERGY SURGE — {name}!",
  "{name} UNFROZE MID-RACE!",
  "BACK IN BUSINESS — {name}!",
  "{name} GOT THE PACE BACK!",
  "THE ICE MELTED — {name}!",
  "{name} BACK ON THE ATTACK LINE!",
  "RESTART MODE — {name}!",
  "{name} BROKE OUT OF NEUTRAL!",
  "BACK FROM ZERO — {name}!",
  "{name} REFUSED TO STAY STUCK!",
  "THE ENGINE ROARED — {name}!",
  "{name} BACK ON THE SCORE LINE!",
  "RESTART PUSH FROM {name}!",
  "{name} UNLOCKED AND MOVING!",
  "BACK IN THE PACK — {name}!",
  "{name} SHOOK OFF THE GRIDLOCK!",
  "THE PAUSE BROKE — {name}!",
  "{name} BACK ON THE GAS AGAIN!",
  "RESTART SURGE ALERT — {name}!",
  "{name} ESCAPED THE FREEZE!",
  "BACK ON THE TICK — {name}!",
  "{name} FOUND THE LINE AGAIN!",
  "THE STANDSTILL IS OVER — {name}!",
  "{name} BACK IN THE RACE FLOW!",
  "RESTART CONFIRMED — {name} GOES!",
  "{name} UNSTUCK AND SCORING!",
  "BACK FROM THE DEAD STOP — {name}!",
  "{name} WOKE BACK UP ON POINTS!",
  "THE MOTOR TURNED OVER — {name}!",
  "{name} BACK ON THE BOARD!",
  "RESTART HEAT CHECK — {name}!",
  "{name} SHOOK OFF THE ICE!",
  "BACK IN MOTION — {name} SURGES!",
  "{name} UNFROZE WITH PURPOSE!",
  "THE STALL ENDED — {name} FIRES!",
  "{name} BACK ON THE PACE TRACK!",
  "RESTART COMPLETE — {name} MOVING!",
  "{name} BROKE THE FREEZE!",
  "BACK ON THE GAS — {name} GOES!",
  "{name} ESCAPED THE STALL CYCLE!",
  "THE WHEELS TURN AGAIN — {name}!",
  "{name} BACK IN CONTENTION!",
  "RESTART FLARE — {name}!",
  "{name} UNLOCKED FROM THE STALL!",
  "BACK FROM STANDSTILL — {name}!",
  "{name} GOT MOVING AGAIN!",
  "THE ICE IS GONE — {name}!",
  "{name} BACK ON THE SCORE CHART!",
  "RESTART MOMENTUM BUILD — {name}!",
  "{name} SHOOK THE STALL OFF!",
  "BACK IN THE SCRAMBLE — {name}!",
  "{name} UNFROZE OUT THERE!",
  "THE PAUSE IS DONE — {name}!",
  "{name} BACK WITH PACE!",
  "RESTART ENERGY — {name} MOVING!",
  "{name} BROKE OUT OF THE STALL!",
  "BACK ON POINTS — {name} GOES!",
  "{name} REFUSED TO STAY PARKED!",
  "THE GRIDLOCK ENDED — {name}!",
  "{name} BACK ON THE LEAD TRAIL!",
  "RESTART SURGE — {name} LIVE!",
  "{name} UNSTUCK FROM THE MUD!",
  "BACK FROM FROZEN — {name}!",
  "{name} FOUND THE ACCELERATOR!",
  "THE STALL IS BROKEN — {name}!",
  "{name} BACK IN THE POINT RACE!",
  "RESTART PUSH — {name}!",
  "{name} WOKE UP AND SCORED!",
  "BACK ON THE MOVE — {name}!",
  "{name} SHOOK OFF THE STANDSTILL!",
  "THE FREEZE LIFTED — {name}!",
  "{name} BACK ON THE GAS LINE!",
  "RESTART CONFIRMED — {name} LIVE!",
  "{name} UNLOCKED THE SCOREBOARD!",
  "BACK IN THE HUNT — {name} GOES!",
  "{name} ESCAPED NEUTRAL!",
  "THE ENGINE'S ALIVE — {name}!",
  "{name} BACK FROM THE ICE!",
  "RESTART HEAT — {name} MOVING!",
  "{name} BROKE FREE FROM THE STALL!",
  "BACK ON THE PACE — {name}!",
  "{name} UNFROZE AND ATTACKED!",
  "THE STANDSTILL BROKE — {name}!",
  "{name} BACK IN THE FLOW!",
  "RESTART ALERT — {name} GOES!",
  "{name} SHOOK OFF THE DEAD STOP!",
  "BACK ON THE BOARD — {name}!",
  "{name} GOT TRACTION BACK!",
  "THE PAUSE LIFTED — {name}!",
  "{name} BACK WITH MOMENTUM!",
  "RESTART SURGE FROM {name}!",
  "{name} UNSTUCK ON THE TRACK!",
  "BACK FROM PARKED — {name} GOES!",
  "{name} REFUSED TO STAY ICE COLD!",
  "THE STALL CYCLE BROKE — {name}!",
  "{name} BACK ON THE SCORE!",
  "RESTART POWER SURGE — {name}!",
  "{name} WOKE UP OUT THERE!",
  "BACK IN GEAR — {name} MOVING!",
  "{name} SHOOK THE FREEZE OFF!",
  "THE ICE BROKE — {name}!",
  "{name} BACK ON THE ATTACK!",
  "RESTART MODE ENGAGED — {name}!",
  "{name} UNLOCKED AND SCORING!",
  "BACK FROM THE STALL — {name}!",
  "{name} FOUND PACE AGAIN!",
  "THE GRIDLOCK LIFTED — {name}!",
  "{name} BACK IN THE RACE!",
  "RESTART FLARE — {name} GOES!",
  "{name} ESCAPED THE PAUSE!",
  "BACK ON THE GAS — {name} LIVE!",
  "{name} UNFROZE ON THE BOARD!",
  "THE STANDSTILL LIFTED — {name}!",
  "{name} BACK WITH HEAT!",
  "RESTART CONFIRMED — {name} SURGES!",
  "{name} BROKE OUT OF THE FREEZE!",
  "BACK IN MOTION — {name} LIVE!",
  "{name} SHOOK OFF THE GRIDLOCK!",
  "THE STALL LIFTED — {name}!",
  "{name} BACK ON THE PACE LINE AGAIN!",
  "RESTART ENERGY LIVE — {name}!",
  "{name} UNSTUCK AND MOVING!",
  "BACK FROM ZERO OUTPUT — {name}!",
  "{name} GOT THE PACE LINE BACK!",
  "THE FREEZE IS BROKEN — {name}!",
  "{name} BACK IN THE SCRUM!",
  "RESTART HEAT LIVE — {name}!",
  "{name} WOKE BACK UP ON THE BOARD!",
  "BACK ON THE TICK — {name} GOES!",
  "{name} REFUSED TO STAY DORMANT!",
  "THE PAUSE ENDED — {name} FIRES!",
  "{name} BACK ON THE SCORE TRACK!",
  "RESTART SURGE LIVE — {name}!",
  "{name} UNFROZE WITH HEAT!",
  "BACK FROM THE STANDSTILL — {name}!",
  "{name} SHOOK THE STALL LOOSE!",
  "THE ENGINE TURNED — {name}!",
  "{name} BACK ON POINTS AGAIN!",
  "RESTART PUSH LIVE — {name}!",
  "{name} ESCAPED THE ICE!",
  "BACK IN THE MIX — {name} GOES!",
  "{name} UNLOCKED FROM NEUTRAL!",
  "THE STALL BROKE — {name}!",
  "{name} BACK ON THE MOVE AGAIN!",
  "RESTART MOMENTUM LIVE — {name}!",
  "{name} BROKE FREE AND SCORED!",
  "BACK ON THE GAS — {name} SURGES!",
  "{name} FOUND THE GROOVE AGAIN!",
  "THE ICE LIFTED — {name}!",
  "{name} BACK IN THE HUNT AGAIN!",
  "RESTART CONFIRMED — {name} HEATING UP!",
  "{name} UNSTUCK FROM THE FREEZE!",
  "BACK FROM MOTIONLESS — {name}!",
  "{name} SHOOK OFF THE PAUSE!",
  "THE GRIDLOCK BROKE OPEN — {name}!",
  "{name} BACK ON THE LEADERBOARD!",
  "RESTART FIRE — {name}!",
  "{name} WOKE UP WITH PACE!",
  "BACK IN THE POINT RACE — {name}!",
  "{name} UNFROZE AND MOVED!",
  "THE STANDSTILL ENDED — {name} GOES!",
  "{name} BACK WITH AUTHORITY AGAIN!",
  "RESTART SURGE — {name} HEATING UP!",
  "{name} ESCAPED THE DEAD STOP!",
  "BACK ON THE PACE — {name} LIVE!",
  "{name} GOT UNSTUCK OUT THERE!",
  "THE STALL FADED — {name} MOVES!",
  "{name} BACK IN THE RACE FLOW AGAIN!",
  "RESTART ENERGY — {name} LIVE!",
  "{name} BROKE THE ICE OUT THERE!",
  "BACK FROM FROZEN SOLID — {name}!",
  "{name} SHOOK THE PAUSE OFF!",
  "THE FREEZE ENDED — {name}!",
  "{name} BACK ON THE BOARD AGAIN!",
  "RESTART HEAT — {name} SURGING!",
  "{name} UNLOCKED THE PACE LINE!",
  "BACK IN MOTION — {name} HEATING UP!",
  "{name} REFUSED TO STAY STRANDED!",
  "THE PAUSE BROKE OPEN — {name}!",
  "{name} BACK ON THE GAS WITH HEAT!",
  "RESTART COMPLETE — {name} SURGING!",
  "{name} UNFROZE AND BACK IN IT!",
  "BACK FROM THE HOLE — {name}!",
  "{name} FOUND MOMENTUM AGAIN!",
  "THE STALL IS HISTORY — {name}!",
  "{name} BACK ON THE SCORE LINE AGAIN!",
  "RESTART FLARE LIVE — {name}!",
  "{name} SHOOK OFF THE ICE COLD!",
  "BACK IN THE SCRAMBLE — {name} GOES!",
  "{name} UNSTUCK FROM THE STANDSTILL!",
  "THE ENGINE ROARED BACK — {name}!",
  "{name} BACK ON THE ATTACK AGAIN!",
  "RESTART PUSH — {name} HEATING UP!",
  "{name} ESCAPED THE GRIDLOCK!",
  "BACK ON POINTS — {name} SURGING!",
  "{name} WOKE UP WITH AUTHORITY!",
  "THE ICE MELTED OFF — {name}!",
  "{name} BACK IN THE MIX AGAIN!",
  "RESTART SURGE — {name} BACK!",
  "{name} UNFROZE ON THE TRACK!",
  "BACK FROM STUCK — {name}!",
  "{name} GOT THE WHEELS TURNING!",
  "THE STALL CYCLE IS OVER — {name}!",
  "{name} BACK ON THE PACE AGAIN!",
  "RESTART CONFIRMED — {name} BACK!",
  "{name} BROKE OUT AND SCORED!",
  "BACK IN GEAR — {name} SURGING!",
  "{name} SHOOK THE STANDSTILL OFF!",
  "THE FREEZE LIFTED OFF — {name}!",
  "{name} BACK ON THE MOVE WITH HEAT!",
  "RESTART ENERGY — {name} BACK!",
  "{name} UNLOCKED AND BACK IN IT!",
  "BACK FROM NEUTRAL — {name}!",
  "{name} FOUND THE LINE AND WENT!",
  "THE PAUSE IS HISTORY — {name}!",
  "{name} BACK IN THE HUNT WITH PACE!",
  "RESTART HEAT — {name} BACK IN IT!",
  "{name} ESCAPED THE STALL ZONE!",
  "BACK ON THE GAS — {name} BACK!",
  "{name} UNFROZE WITH AUTHORITY!",
  "THE STANDSTILL IS HISTORY — {name}!",
  "{name} BACK ON THE SCOREBOARD AGAIN!",
  "RESTART LIVE — {name}!",
  "{name} SHOOK OFF THE STRAND!",
  "BACK IN THE RACE — {name} GOES!",
  "{name} GOT MOVING WITH HEAT!",
  "THE GRIDLOCK IS OVER — {name}!",
  "{name} BACK ON THE TICK AGAIN!",
  "RESTART SURGE — {name} IN MOTION!",
  "{name} UNSTUCK AND BACK IN IT!",
  "BACK FROM THE FREEZE — {name}!",
  "{name} REFUSED TO STAY FLAT!",
  "THE STALL ZONE ENDED — {name}!",
  "{name} BACK WITH PACE AND HEAT!",
  "RESTART CONFIRMED — {name} IN MOTION!",
  "{name} BROKE FREE AND BACK IN IT!",
  "BACK ON THE BOARD — {name} SURGING!",
  "{name} UNFROZE WITH MOMENTUM!",
  "THE ICE IS HISTORY — {name}!",
  "{name} BACK IN THE SCRUM AGAIN!",
  "RESTART POWER — {name} BACK IN IT!",
  "{name} SHOOK THE DEAD STOP OFF!",
  "BACK IN MOTION — {name} BACK!",
  "{name} ESCAPED AND SCORED!",
  "THE PAUSE ZONE ENDED — {name}!",
  "{name} BACK ON THE GAS IN MOTION!",
  "RESTART HEAT — {name} IN MOTION!",
  "{name} UNLOCKED AND BACK ON PACE!",
  "BACK FROM STRANDED — {name}!",
  "{name} FOUND HEAT AGAIN!",
  "THE STALL FADED OUT — {name}!",
  "{name} BACK IN THE POINT HUNT!",
  "RESTART SURGE — {name} ON PACE!",
  "{name} WOKE UP IN MOTION!",
  "BACK ON THE PACE LINE — {name} BACK!",
  "{name} UNFROZE AND SURGED!",
  "THE FREEZE FADED — {name}!",
  "{name} BACK ON THE MOVE IN MOTION!",
  "RESTART COMPLETE — {name} ON PACE!",
  "{name} BROKE THE STANDSTILL!",
  "BACK IN THE FLOW — {name}!",
  "{name} SHOOK OFF STRANDED MODE!",
  "THE GRIDLOCK FADED — {name}!",
  "{name} BACK ON POINTS IN MOTION!",
  "RESTART FLARE — {name} ON PACE!",
  "{name} UNSTUCK AND SURGING!",
  "BACK FROM ICE COLD — {name}!",
  "{name} GOT BACK IN GEAR!",
  "THE STALL ZONE FADED — {name}!",
  "{name} BACK ON THE SCORE IN MOTION!",
  "RESTART PUSH — {name} ON PACE!",
  "{name} ESCAPED AND BACK IN IT!",
  "BACK ON THE ATTACK — {name} BACK!",
  "{name} UNFROZE IN MOTION!",
  "THE PAUSE FADED — {name}!",
  "{name} BACK WITH SURGE!",
  "RESTART LIVE — {name} ON PACE!",
  "{name} SHOOK THE ICE LOOSE!",
  "BACK IN THE PACK — {name} SURGING!",
  "{name} FOUND PACE AND WENT!",
  "THE STANDSTILL FADED — {name}!",
  "{name} BACK ON THE BOARD IN MOTION!",
  "RESTART ENERGY — {name} ON PACE!",
  "{name} UNLOCKED IN MOTION!",
  "BACK FROM THE PAUSE — {name}!",
  "{name} REFUSED TO STAY FLATLINE!",
  "THE FREEZE ZONE ENDED — {name}!",
  "{name} BACK IN MOTION ON PACE!",
  "RESTART SURGE — {name} MOVING AGAIN!",
  "{name} BROKE OUT IN MOTION!",
  "BACK ON THE GAS — {name} ON PACE!",
  "{name} UNFROZE AND BACK ON PACE!",
  "THE STALL ENDED CLEAN — {name}!",
  "{name} BACK IN THE RACE AGAIN!",
  "RESTART CONFIRMED — {name} MOVING AGAIN!",
  "{name} ESCAPED THE FLATLINE!",
  "BACK IN BUSINESS — {name} ON PACE!",
  "{name} WOKE UP AND BACK IN IT!",
  "THE ICE ZONE ENDED — {name}!",
  "{name} BACK ON THE PACE IN MOTION!",
  "RESTART HEAT — {name} MOVING AGAIN!",
  "{name} UNSTUCK AND ON PACE!",
  "BACK FROM DORMANT — {name}!",
  "{name} SHOOK THE FLATLINE OFF!",
  "THE GRIDLOCK ENDED CLEAN — {name}!",
  "{name} BACK ON THE SCORE SURGING!",
  "RESTART POWER — {name} MOVING AGAIN!",
  "{name} UNFROZE CLEAN OUT THERE!",
  "BACK ON THE MOVE — {name} ON PACE!",
  "{name} FOUND THE RESTART!",
  "THE PAUSE ENDED CLEAN — {name}!",
  "{name} BACK IN THE HUNT ON PACE!",
  "RESTART FLARE — {name} MOVING AGAIN!",
  "{name} BROKE FREE ON PACE!",
  "BACK IN MOTION — {name} MOVING AGAIN!",
  "{name} UNLOCKED CLEAN OUT THERE!",
  "THE STALL CLEARED — {name}!",
  "{name} BACK ON THE GAS MOVING AGAIN!",
  "RESTART SURGE CLEAN — {name}!",
  "{name} SHOOK OFF THE FLATLINE!",
  "BACK ON PACE — {name} MOVING AGAIN!",
  "{name} ESCAPED CLEAN OUT THERE!",
  "THE FREEZE CLEARED — {name}!",
  "{name} BACK IN THE MIX ON PACE!",
  "RESTART LIVE — {name} MOVING AGAIN!",
  "{name} UNFROZE AND MOVING AGAIN!",
  "BACK FROM THE FLATLINE — {name}!",
  "{name} GOT BACK ON PACE!",
  "THE STANDSTILL CLEARED — {name}!",
  "{name} BACK ON THE BOARD ON PACE!",
  "RESTART COMPLETE — {name} MOVING AGAIN!",
  "{name} BROKE THE PAUSE CLEAN!",
  "BACK IN THE SCRUM — {name} ON PACE!",
  "{name} UNSTUCK CLEAN OUT THERE!",
  "THE GRIDLOCK CLEARED — {name}!",
  "{name} BACK WITH RESTART ENERGY!",
  "RESTART PUSH CLEAN — {name}!",
  "{name} WOKE UP CLEAN OUT THERE!",
  "BACK ON THE TICK — {name} ON PACE!",
  "{name} REFUSED THE FLATLINE!",
  "THE ICE CLEARED — {name}!",
  "{name} BACK IN MOTION CLEAN!",
  "RESTART HEAT CLEAN — {name}!",
  "{name} UNLOCKED AND MOVING AGAIN!",
  "BACK FROM NEUTRAL GEAR — {name}!",
  "{name} FOUND RESTART PACE!",
  "THE PAUSE CLEARED — {name}!",
  "{name} BACK ON THE SCORE CLEAN!",
  "RESTART ENERGY CLEAN — {name}!",
  "{name} ESCAPED THE FLATLINE CLEAN!",
  "BACK IN GEAR CLEAN — {name}!",
  "{name} SHOOK THE STALL CLEAN!",
  "THE STALL CLEARED OUT — {name}!",
  "{name} BACK ON THE PACE CLEAN!",
  "RESTART SURGE CLEAN — {name}!",
  "{name} UNFROZE CLEAN AND WENT!",
  "BACK ON THE MOVE CLEAN — {name}!",
  "{name} GOT THE RESTART CLEAN!",
  "THE FREEZE CLEARED OUT — {name}!",
  "{name} BACK IN THE HUNT CLEAN!",
  "RESTART CONFIRMED CLEAN — {name}!",
  "{name} BROKE OUT CLEAN!",
  "BACK IN MOTION CLEAN — {name}!",
  "{name} UNSTUCK CLEAN AND WENT!",
  "THE STANDSTILL CLEARED OUT — {name}!",
  "{name} BACK ON POINTS CLEAN!",
  "RESTART FLARE CLEAN — {name}!",
  "{name} WOKE UP CLEAN AND WENT!",
  "BACK ON THE GAS CLEAN — {name}!",
  "{name} REFUSED TO STAY FLAT CLEAN!",
  "THE GRIDLOCK CLEARED OUT — {name}!",
  "{name} BACK ON THE BOARD CLEAN!",
  "RESTART LIVE CLEAN — {name}!",
  "{name} UNFROZE AND WENT CLEAN!",
  "BACK FROM STUCK CLEAN — {name}!",
  "{name} FOUND PACE CLEAN OUT THERE!",
  "THE PAUSE CLEARED OUT — {name}!",
  "{name} BACK IN THE RACE CLEAN!",
  "RESTART POWER CLEAN — {name}!",
  "{name} ESCAPED CLEAN AND WENT!",
  "BACK ON PACE CLEAN — {name}!",
  "{name} SHOOK OFF STUCK MODE!",
  "THE ICE CLEARED CLEAN — {name}!",
  "{name} BACK WITH CLEAN RESTART!",
  "RESTART HEAT — {name} CLEAN GO!",
  "{name} UNLOCKED CLEAN AND WENT!",
  "BACK IN THE MIX CLEAN — {name}!",
  "{name} BROKE THE STALL CLEAN!",
  "THE STALL CLEARED CLEAN — {name}!",
  "{name} BACK ON THE MOVE CLEAN GO!",
  "RESTART SURGE — {name} CLEAN GO!",
  "{name} UNFROZE FOR REAL OUT THERE!",
  "BACK ON THE PACE — {name} CLEAN GO!",
  "{name} GOT BACK IN THE FLOW!",
  "THE FREEZE IS DONE — {name} GOES!",
  "{name} BACK ON THE SCORE FOR REAL!",
  "RESTART — {name} IS BACK!",
] as const;

export const UNDERDOG_PHRASES = [
  "WINLESS {name} SHOCKS THE FIELD — P{rank}!",
  "{name} HAS ZERO WINS AND IS IN THE HUNT!",
  "UNDERDOG ALERT! {name} UP TO P{rank}!",
  "NO WINS ON THE BOARD — {name} IN P{rank}!",
  "THE WINLESS {name} IS HUNTING — P{rank}!",
  "UNDERDOG ENERGY — {name} AT P{rank}!",
  "{name} WITH NO WINS — STILL IN P{rank}!",
  "ZERO WINS, ALL HEART — {name} P{rank}!",
  "UNDERDOG RUN — {name} UP TO P{rank}!",
  "{name} SHOCKING THE FIELD FROM P{rank}!",
  "WINLESS AND DANGEROUS — {name}!",
  "THE FIELD FORGOT {name} — NOW P{rank}!",
  "UNDERDOG STORY — {name} IN P{rank}!",
  "{name} HASN'T WON YET — LOOK AT P{rank}!",
  "NO CHECKERED FLAGS — {name} STILL P{rank}!",
  "UNDERDOG ALERT — {name} AT P{rank}!",
  "{name} — ZERO WINS — P{rank} RIGHT NOW!",
  "THE LONG SHOT — {name} IN P{rank}!",
  "WINLESS {name} REFUSES TO FADE!",
  "UNDERDOG MAGIC — {name} P{rank}!",
] as const;

export const ROOKIE_RUN_PHRASES = [
  "{name} ON A ROOKIE RUN — NOW P{rank}!",
  "ROOKIE SURGE — {name} UP TO P{rank}!",
  "{name} ROOKIE MAGIC AT P{rank}!",
  "FRESH FACE FLYING — {name} P{rank}!",
  "ROOKIE RUN ALERT — {name}!",
  "{name} ROOKIE CHARGE TO P{rank}!",
  "THE ROOKIE IS HUNTING — {name} P{rank}!",
  "{name} ON A ROOKIE HEATER — P{rank}!",
  "ROOKIE ENERGY — {name} AT P{rank}!",
  "{name} ROOKIE RUN IN FULL EFFECT!",
  "NEW BLOOD RISING — {name} P{rank}!",
  "ROOKIE ALERT — {name} UP TO P{rank}!",
  "{name} ROOKIE PUSH — NOW P{rank}!",
  "FIRST-TIMER FLYING — {name}!",
  "ROOKIE ON THE MOVE — {name} P{rank}!",
  "{name} ROOKIE SURGE TO P{rank}!",
  "THE ROOKIE WON'T QUIT — P{rank}!",
  "ROOKIE RUN CONFIRMED — {name}!",
  "{name} — ROOKIE — P{rank} AND CLIMBING!",
  "ROOKIE STORYLINE — {name} AT P{rank}!",
] as const;

export const LEAD_PRESSURE_PHRASES = [
  "{name} CLINGING TO THE LEAD — PRESSURE BUILDING!",
  "CAN {name} HOLD ON UP FRONT?!",
  "LEAD UNDER SIEGE — {name} HANGING ON!",
  "THE PACK IS COMING FOR {name}!",
  "PRESSURE ON {name} UP FRONT!",
  "CAN {name} SURVIVE THE HUNT?!",
  "{name} LEADING BUT BARELY MOVING!",
  "THE LEAD IS SLIPPING — {name} STRUGGLING!",
  "UP FRONT: {name} — BUT FOR HOW LONG?!",
  "LEAD PRESSURE MOUNTING ON {name}!",
  "{name} HOLDING ON BY A THREAD!",
  "THE FIELD SMELLS BLOOD — {name} LEADS!",
  "FRAGILE LEAD FOR {name}!",
  "CAN {name} KEEP THE POINT?!",
  "LEAD DEFENSE MODE — {name}!",
  "{name} UNDER HEAVY PRESSURE UP FRONT!",
  "THE HUNT IS ON — {name} LEADS!",
  "LEAD STRESS — {name} UP TOP!",
  "{name} CLINGING TO P1 — DRAMA!",
  "WILL {name} HOLD?! PRESSURE BUILDING!",
] as const;

export const LATE_CLOSE_PHRASES = [
  "{chaser} CLOSING ON {leader} — ONLY {gap} PTS BACK!",
  "IT'S TIGHT! {chaser} HUNTING THE LEAD!",
  "FINAL STRETCH DRAMA — {chaser} IS RIGHT THERE!",
  "CLOSE AT THE TOP — {chaser} {gap} BEHIND {leader}!",
  "{chaser} IS HUNTING {leader} — {gap} PTS!",
  "NAIL-BITER — {chaser} CLOSING FAST!",
  "THE GAP IS {gap} — {chaser} ON {leader}!",
  "FINAL ACT DRAMA — {chaser} VS {leader}!",
  "{chaser} WITHIN {gap} OF {leader}!",
  "IT'S NOT OVER — {chaser} CLOSING!",
  "LATE RACE THRILLER — {gap} PTS SEPARATE THEM!",
  "{chaser} SMELLING AN UPSET ON {leader}!",
  "CLOSING STAGES — {chaser} {gap} BACK!",
  "THE LEAD IS IN PLAY — {chaser} CLOSING!",
  "{chaser} REELING IN {leader} — {gap} PTS!",
  "FINAL STRETCH — {chaser} RIGHT ON {leader}!",
  "DRAMA UP FRONT — ONLY {gap} PTS!",
  "{chaser} KNOCKING ON THE DOOR — {gap} BACK!",
  "TOO CLOSE TO CALL — {chaser} VS {leader}!",
  "LATE-RACE CHASE — {gap} POINT GAP!",
] as const;

export const RACE_START_PHRASES = [
  "8 RACERS ON THE GRID — WE ARE LIVE!",
  "THE GRID IS SET — 8 RACERS — LET'S GO!",
  "GREEN FLAG ENERGY — WE ARE UNDERWAY!",
  "RACE IS LIVE — 8 IN THE FIELD!",
  "FROM THE GRID — WE ARE RACING!",
  "THE FIELD IS LOCKED — RACE ON!",
  "8 RACERS — THE RACE IS ON!",
  "WE ARE LIVE FROM THE GRID!",
  "RACE UNDERWAY — 8 COMPETITORS!",
  "THE SHOW BEGINS — 8 ON TRACK!",
  "GRID CLEAR — RACE IS LIVE!",
  "8 RACERS — AND WE'RE OFF!",
  "THE RACE IS OFFICIALLY LIVE!",
  "FROM THE START — 8 RACERS GO!",
  "LIVE RACING — 8 IN THE FIELD!",
  "THE GRID RELEASES — WE RACE!",
  "8 COMPETITORS — RACE LIVE!",
  "WE HAVE LIFTOFF — RACE ON!",
  "RACE DAY LIVE — 8 RACERS!",
  "THE FIELD IS RACING — WE ARE LIVE!",
] as const;

export const RACE_WON_PHRASES = [
  "{winner} WINS! CHECKERED FLAG!",
  "CHECKERED FLAG FOR {winner}!",
  "{winner} TAKES THE WIN!",
  "VICTORY FOR {winner}!",
  "{winner} — RACE WINNER!",
  "AND THE WIN GOES TO {winner}!",
  "{winner} AT THE LINE — WINNER!",
  "CHECKERED FLAG — {winner}!",
  "{winner} GETS THE W!",
  "WINNER WINNER — {winner}!",
  "{winner} CROSSES FIRST!",
  "THE WIN BELONGS TO {winner}!",
  "{winner} — YOUR RACE WINNER!",
  "CHECKERED FOR {winner}!",
  "{winner} TAKES CHECKERED!",
  "RACE WIN — {winner}!",
  "{winner} STANDS TALL — WINNER!",
  "TOP STEP — {winner} WINS!",
  "{winner} — FLAG FALLS — WIN!",
  "VICTORY LAP FOR {winner}!",
] as const;

export const ELIMINATED_PHRASES = [
  "{last} FINISHES LAST — SENT TO HOLDING!",
  "LAST PLACE — {last} TO HOLDING!",
  "{last} ELIMINATED TO HOLDING!",
  "THE BUBBLE BURSTS — {last} OUT!",
  "{last} FINISHES P8 — HOLDING!",
  "SENT TO HOLDING — {last}!",
  "{last} LAST — ELIMINATED!",
  "P8 FOR {last} — HOLDING LINE!",
  "{last} DROPS TO HOLDING!",
  "LAST ACROSS — {last} ELIMINATED!",
  "HOLDING FOR {last} — LAST PLACE!",
  "{last} — LAST — HOLDING!",
  "THE RACE ENDS IN P8 FOR {last}!",
  "{last} TO THE HOLDING PEN!",
  "ELIMINATED: {last}!",
  "{last} FINISHES LAST TODAY!",
  "LAST PLACE FINISH — {last}!",
  "{last} OUT — HOLDING!",
  "P8 — {last} — HOLDING!",
  "{last} SENT PACKING TO HOLDING!",
] as const;
