import { seededInt } from "./seeded-rng";

export type TickerPhraseVars = Record<string, string | number>;

export function fillTickerPhrase(template: string, vars: TickerPhraseVars): string {
  let out = template;
  for (const [key, val] of Object.entries(vars)) {
    out = out.replaceAll(`{${key}}`, String(val));
  }
  return out;
}

export function pickTickerPhrase(
  seed: string,
  phrases: readonly string[],
  vars: TickerPhraseVars
): string {
  if (!phrases.length) return "";
  const template = phrases[seededInt(seed, 0, phrases.length - 1)];
  return fillTickerPhrase(template, vars);
}

export const LEAD_CHANGE_PHRASES = [
  "OH! {name} TAKES THE LEAD — {prev} DROPPED!",
  "LEAD CHANGE! {name} IS OUT FRONT NOW!",
  "{name} SEIZES THE POINT! WHAT A MOVE!",
  "NEW LEADER! {name} AT THE FRONT!",
  "WE HAVE A NEW LEADER — {name} PASSES {prev}!",
  "BREAKING: {name} GRABS THE TOP SPOT FROM {prev}!",
  "THE LEAD BELONGS TO {name} NOW — {prev} FADED!",
  "{name} STEPS INTO P1! {prev} CAN'T HOLD IT!",
  "UP FRONT IT'S {name}! {prev} LOSES THE POINT!",
  "LEAD CHANGE AT THE FRONT — {name} IS FLYING!",
  "{name} SNATCHES THE LEAD AWAY FROM {prev}!",
  "POINT LEADERSHIP FLIPS — {name} IS YOUR NEW FRONT RUNNER!",
  "LISTEN TO THIS CROWD — {name} TAKES COMMAND!",
  "{prev} HAD IT… AND NOW {name} HAS IT!",
  "THE THRONE CHANGES HANDS — {name} LEADS!",
  "OUT FRONT: {name}! {prev} PUSHED ASIDE!",
  "WHAT A SWAP! {name} LEADS, {prev} CHASING!",
  "{name} GRABS THE BRIGHT SPOT — LEAD CHANGE!",
  "LEAD UPDATE: {name} FROM {prev} — WE GO AGAIN!",
  "CAN YOU BELIEVE IT? {name} IS LEADING NOW!",
  "{name} TOOK THE WHEEL UP FRONT — {prev} DROPPED BACK!",
  "THE POINT IS {name}'S — {prev} LOST THE HANDLE!",
  "FRONT RUNNER ALERT: {name}!",
  "{name} PUNCHES THROUGH — NEW LEADER!",
  "LEAD TRANSFER COMPLETE — {name} OUT FRONT!",
  "OH MY — {name} STOLE THE LEAD FROM {prev}!",
  "WE'VE GOT DRAMA UP FRONT — {name} LEADS!",
  "{name} IS YOUR RACE LEADER NOW!",
  "THE LEAD LINE READS {name} — NOT {prev}!",
  "SWITCH AT THE FRONT — {name} IN P1!",
  "{name} WRESTLED THE LEAD AWAY FROM {prev}!",
  "POINT POSITION ONE: {name}!",
  "LEAD CHANGE CONFIRMED — {name} UP TOP!",
  "{prev} FADED — {name} TOOK OVER UP FRONT!",
  "THE FRONT SPOT FLIPS TO {name}!",
  "{name} IS LEADING THE CHARGE NOW!",
  "NEW NAME UP FRONT — IT'S {name}!",
  "LEADERSHIP CHANGE — {name} FROM {prev}!",
  "{name} GRABS P1 WITH AUTHORITY!",
  "UP TOP IT'S ALL {name} NOW!",
  "THE LEAD BELONGS TO {name} — STUNNING!",
] as const;

export const CHAOS_SURGE_PHRASES = [
  "CHAOS SURGE! {name} IS UNLEASHED!",
  "{name} WENT ABSOLUTELY WILD!",
  "OH MY — {name} HIT A CHAOS BURST!",
  "TOTAL CHAOS FROM {name} RIGHT NOW!",
  "{name} DETONATED A CHAOS SURGE!",
  "UNPREDICTABLE ENERGY — {name} EXPLODED!",
  "CHAOS MODE: {name} IS OFF THE CHARTS!",
  "{name} UNLEASHED PURE CHAOS OUT THERE!",
  "THE FIELD CAN'T HANDLE {name} RIGHT NOW!",
  "CHAOS BURST! {name} IS ELECTRIC!",
  "WILD SWING FROM {name} — CHAOS SURGE!",
  "{name} TURNED IT UP TO CHAOS!",
  "ABSOLUTE MAYHEM — {name} SURGED!",
  "CHAOS FACTOR MAX — {name} FLYING!",
  "{name} HIT THE CHAOS BUTTON!",
  "UNHINGED RUN FROM {name}!",
  "CHAOS SURGE ALERT — {name}!",
  "{name} IS PLAYING WITH FIRE AND WINNING!",
  "THE CHAOS GODS SMILE ON {name}!",
  "ERRATIC BRILLIANCE FROM {name}!",
  "{name} WENT CHAOTIC — POINTS POURING IN!",
  "CHAOS UNLEASHED — {name} ON A TEAR!",
  "{name} — CHAOS SURGE — HOLD ON!",
  "PURE CHAOS ENERGY FROM {name}!",
  "NOBODY CALLED THIS — {name} CHAOS SURGE!",
] as const;

export const COLLAPSE_PHRASES = [
  "{name} IS FADING FAST — DOWN {loss} SPOTS!",
  "DISASTER FOR {name}! {loss}-SPOT COLLAPSE!",
  "{name} IS FALLING APART OUT THERE!",
  "COLLAPSE! {name} DROPPED {loss} POSITIONS!",
  "{name} IS MELTING DOWN — {loss} SPOTS LOST!",
  "BRUTAL SLIDE FOR {name} — MINUS {loss}!",
  "{name} TUMBLING — {loss}-SPOT DISASTER!",
  "THE WHEELS CAME OFF FOR {name}!",
  "{name} IN FREE FALL — DOWN {loss}!",
  "CATASTROPHIC DROP FOR {name}!",
  "{name} LOST {loss} SPOTS IN ONE SWING!",
  "OH NO — {name} COLLAPSED {loss} PLACES!",
  "{name} IS SPIRALING — {loss} SPOT DROP!",
  "COMPLETE MELTDOWN — {name} DOWN {loss}!",
  "{name} GOT CAUGHT AND PAID — {loss} SPOTS!",
  "THE BOTTOM DROPPED OUT FOR {name}!",
  "{name} — {loss}-SPOT COLLAPSE — BRUTAL!",
  "DISASTER STRIKES {name} — DOWN {loss}!",
  "{name} FELL APART — {loss} POSITIONS GONE!",
  "COLLAPSE ALERT: {name} DOWN {loss}!",
  "{name} IS CRUMBLING OUT THERE!",
  "HARD FALL FOR {name} — {loss} SPOTS!",
  "{name} LOST THE PLOT — DOWN {loss}!",
  "THE FIELD PASSED {name} — {loss} SPOT DROP!",
  "{name} UNRAVELING — MINUS {loss}!",
  "TROUBLE FOR {name} — {loss}-SPOT SLIDE!",
  "{name} GOT SWALLOWED — DOWN {loss}!",
  "COLLAPSE CONFIRMED — {name} FADING!",
  "{name} DROPPED LIKE A STONE — {loss} SPOTS!",
  "NIGHTMARE MOMENT FOR {name}!",
] as const;

export const RANK_SLIP_PHRASES = [
  "{name} SLIPPED TWO SPOTS — TROUBLE!",
  "TWO-SPOT DROP FOR {name}!",
  "{name} LOST TWO POSITIONS!",
  "SLIDE FOR {name} — DOWN TWO!",
  "{name} FELL BACK A PAIR!",
  "TWO-SPOT SLIP — {name} IN TROUBLE!",
  "{name} DROPPED TWO — NOT IDEAL!",
  "PAIR OF SPOTS LOST FOR {name}!",
  "{name} SLID TWO PLACES BACK!",
  "MINOR DISASTER — {name} DOWN TWO!",
  "{name} LOST GROUND — TWO SPOTS!",
  "TWO DOWN FOR {name} THIS TICK!",
  "{name} SLIPPED — TWO SPOT DROP!",
  "BACKWARD STEP FOR {name} — MINUS TWO!",
  "{name} FADED TWO SPOTS!",
  "TWO-POSITION SLIP FOR {name}!",
  "{name} DROPPED A COUPLE!",
  "NOT THE MOVE {name} NEEDED — DOWN TWO!",
  "{name} LOST TWO IN THE SHUFFLE!",
  "SLIPPING: {name} DOWN TWO SPOTS!",
] as const;

export const RANK_SURGE_BIG_PHRASES = [
  "{name} SURGED {gain} SPOTS! INCREDIBLE!",
  "WHAT A RUN! {name} CLIMBED {gain} POSITIONS!",
  "{name} IS CHARGING — UP {gain} SPOTS!",
  "MASSIVE GAIN — {name} UP {gain}!",
  "{name} ROCKETED {gain} SPOTS!",
  "UNREAL CLIMB FROM {name} — PLUS {gain}!",
  "{name} FLEW UP {gain} POSITIONS!",
  "SENSATIONAL — {name} GAINED {gain} SPOTS!",
  "{name} ON A TEAR — UP {gain}!",
  "THE FIELD CAN'T STOP {name} — {gain} SPOT SURGE!",
  "{name} CHARGED {gain} PLACES!",
  "HUGE MOVE — {name} UP {gain} SPOTS!",
  "{name} SURGED THROUGH — {gain} SPOT GAIN!",
  "INCREDIBLE RUN — {name} PLUS {gain}!",
  "{name} CLIMBED {gain} — WHAT A SURGE!",
  "BREAKOUT MOMENT — {name} UP {gain}!",
  "{name} GAINED {gain} IN ONE BURST!",
  "THE CHASE IS ON — {name} UP {gain} SPOTS!",
  "{name} EXPLODED UP THE ORDER — {gain}!",
  "RANK SURGE — {name} PLUS {gain} SPOTS!",
  "{name} MOTORING — {gain} SPOT JUMP!",
  "STUNNING CLIMB — {name} UP {gain}!",
  "{name} WENT UP {gain} — FIELD SHAKEN!",
  "SURGE ALERT: {name} GAINED {gain}!",
  "{name} — {gain}-SPOT RUN — UNSTOPPABLE!",
  "WHAT A CHARGE FROM {name} — UP {gain}!",
  "{name} BLITZED {gain} SPOTS!",
  "RISING FAST — {name} PLUS {gain}!",
  "{name} CLAWED BACK {gain} POSITIONS!",
  "ELECTRIC SURGE — {name} UP {gain} SPOTS!",
] as const;

export const RANK_SURGE_TWO_PHRASES = [
  "{name} MOVED UP TWO — COMEBACK ALERT!",
  "TWO-SPOT GAIN FOR {name}!",
  "{name} CLIMBED TWO POSITIONS!",
  "PAIR OF SPOTS GAINED — {name}!",
  "{name} UP TWO — MOMENTUM BUILDING!",
  "TWO-SPOT SURGE FROM {name}!",
  "{name} GAINED TWO IN THE SHUFFLE!",
  "UP TWO FOR {name} — NICE MOVE!",
  "{name} STEPPED UP TWO SPOTS!",
  "COMEBACK FEELING — {name} PLUS TWO!",
  "{name} MOVED UP A PAIR!",
  "TWO-POSITION GAIN — {name}!",
  "{name} CLIMBED TWO — LOOK OUT!",
  "GAINING: {name} UP TWO SPOTS!",
  "{name} TOOK TWO SPOTS BACK!",
  "TWO UP FOR {name} THIS TICK!",
  "{name} SURGED TWO PLACES!",
  "POSITIVE MOVE — {name} PLUS TWO!",
  "{name} GAINED A COUPLE OF SPOTS!",
  "TWO-SPOT CHARGE FROM {name}!",
] as const;

export const BIG_LAP_PHRASES = [
  "{name} WITH A MONSTER LAP — +{delta} PTS!",
  "BIG LAP FROM {name}! GROUND GAINED!",
  "HUGE TICK FOR {name} — +{delta}!",
  "{name} PUT UP +{delta} THIS CYCLE!",
  "MONSTER OUTPUT — {name} +{delta} PTS!",
  "{name} SCORED +{delta} — BIG LAP!",
  "MASSIVE POINTS FROM {name} — +{delta}!",
  "{name} WITH A BANNER LAP — +{delta}!",
  "BIG NUMBERS — {name} +{delta} PTS!",
  "{name} UNLOADED +{delta} POINTS!",
  "LARGE LAP ALERT — {name} +{delta}!",
  "{name} STACKED +{delta} THIS TICK!",
  "ENORMOUS LAP — {name} +{delta}!",
  "{name} PUT THE FIELD ON NOTICE — +{delta}!",
  "POINT BURST FROM {name} — +{delta}!",
  "{name} WITH +{delta} — THAT'S A LAP!",
  "BIG-TICK ENERGY FROM {name} — +{delta}!",
  "{name} STACKED +{delta} POINTS!",
  "MAJOR LAP — {name} +{delta} PTS!",
  "{name} DROPPED +{delta} ON THE BOARD!",
  "HUGE OUTPUT — {name} +{delta}!",
  "{name} WITH A STATEMENT LAP — +{delta}!",
  "BIG POINTS — {name} +{delta}!",
  "{name} RIPPED +{delta} THIS CYCLE!",
  "LAP OF THE TICK — {name} +{delta}!",
] as const;

export const HOT_STRETCH_PHRASES = [
  "{name} ON A HEATER — SCORING BURST!",
  "HOT STRETCH! {name} IS UNSTOPPABLE RIGHT NOW!",
  "{name} CATCHING FIRE OUT THERE!",
  "{name} IS RED HOT RIGHT NOW!",
  "HEATER ALERT — {name} ON FIRE!",
  "{name} CAN'T MISS — HOT STRETCH!",
  "SCORCHING RUN FROM {name}!",
  "{name} IS BLAZING HOT!",
  "ON FIRE — {name} HOT STRETCH!",
  "{name} TURNED UP THE HEAT!",
  "HOT STREAK — {name} UNLOADING!",
  "{name} IS COOKING OUT THERE!",
  "TEMPERATURE RISING — {name} HEATING UP!",
  "{name} ON A SCORCHING STRETCH!",
  "WHITE HOT — {name} RIGHT NOW!",
  "{name} IS BURNING UP THE TRACK!",
  "HOT STRETCH CONFIRMED — {name}!",
  "{name} — UNREAL HEAT RIGHT NOW!",
  "THE HEATER IS ON — {name}!",
  "{name} IN THE ZONE — HOT STRETCH!",
] as const;

export const STALL_LONG_PHRASES = [
  "{name} STOPPED COLD — LONG STALL!",
  "{name} IS FROZEN OUT THERE!",
  "NO POINTS FROM {name} — IS THE RACE OVER FOR THEM?!",
  "{name} STUCK — LONG STALL IN PLAY!",
  "DEAD STOP FOR {name}!",
  "{name} WENT NOWHERE — LONG STALL!",
  "THE CLOCK IS TICKING — {name} STALLED!",
  "{name} FROZE UP COMPLETELY!",
  "LONG STALL — {name} STRANDED!",
  "{name} HIT A WALL — NOT MOVING!",
  "ZERO OUTPUT FROM {name} — STALLED!",
  "{name} IS STUCK IN THE MUD!",
  "STALL ALERT — {name} MOTIONLESS!",
  "{name} CAN'T GET GOING — LONG STALL!",
  "THE RACE LEFT {name} BEHIND — STALLED!",
  "{name} GRIND TO A HALT — STALL!",
  "LONG STALL FOR {name} — TROUBLE!",
  "{name} STOPPED DEAD IN THE WATER!",
  "NO FORWARD MOTION — {name} STALLED!",
  "{name} IS PARALYZED OUT THERE!",
] as const;

export const STALL_TOP_PHRASES = [
  "{name} STALLED IN THE TOP FOUR!",
  "WALL HIT! {name} BARELY MOVED!",
  "{name} STALLED UP FRONT — DRAMA!",
  "TOP FOUR STALL — {name} STUCK!",
  "{name} BARELY SCORED THIS TICK!",
  "STALL UP FRONT — {name} FROZE!",
  "{name} HIT A SPEED BUMP IN P{rank}!",
  "LEADER PACK STALL — {name}!",
  "{name} COULDN'T BUY A POINT!",
  "STALLED NEAR THE FRONT — {name}!",
  "{name} STUCK IN THE TOP GROUP!",
  "MINIMAL OUTPUT FROM {name} UP FRONT!",
  "{name} STALLED — TOP FOUR DRAMA!",
  "UP FRONT AND STUCK — {name}!",
  "THE LEAD GROUP STALLED — {name}!",
  "{name} BARELY TICKED THE SCOREBOARD!",
  "STALL IN THE HUNT — {name}!",
  "{name} FROZE NEAR THE FRONT!",
  "TOP FOUR TROUBLE — {name} STALLED!",
  "{name} STOPPED MOVING UP FRONT!",
] as const;

export const RESTART_PHRASES = [
  "{name} BACK ON THE TRACK — BIG RESTART!",
  "{name} ROARS BACK TO LIFE!",
  "AFTER THE STALL — {name} IS MOVING AGAIN!",
  "RESTART! {name} BACK IN BUSINESS!",
  "{name} RECOVERED FROM THE STALL!",
  "BACK IN MOTION — {name} RESTART!",
  "{name} SHOOK OFF THE STALL!",
  "LIFE AFTER STALL — {name} MOVING!",
  "{name} RESTARTED WITH AUTHORITY!",
  "THE STALL IS OVER — {name} GOES!",
  "{name} BACK ON THE GAS!",
  "RESTART ENERGY FROM {name}!",
  "{name} WOKE BACK UP OUT THERE!",
  "SECOND WIND — {name} RESTART!",
  "{name} BACK IN THE FIGHT!",
  "RESTART COMPLETE — {name}!",
  "{name} REFUSED TO STAY STALLED!",
  "BACK FROM THE DEAD — {name}!",
  "{name} UNFREEZED — BIG RESTART!",
  "MOMENTUM RESTORED — {name}!",
] as const;

export const UNDERDOG_PHRASES = [
  "WINLESS {name} SHOCKS THE FIELD — P{rank}!",
  "{name} HAS ZERO WINS AND IS IN THE HUNT!",
  "UNDERDOG ALERT! {name} UP TO P{rank}!",
  "NO WINS ON THE BOARD — {name} IN P{rank}!",
  "THE WINLESS {name} IS HUNTING — P{rank}!",
  "UNDERDOG ENERGY — {name} AT P{rank}!",
  "{name} WITH NO WINS — STILL IN P{rank}!",
  "ZERO WINS, ALL HEART — {name} P{rank}!",
  "UNDERDOG RUN — {name} UP TO P{rank}!",
  "{name} SHOCKING THE FIELD FROM P{rank}!",
  "WINLESS AND DANGEROUS — {name}!",
  "THE FIELD FORGOT {name} — NOW P{rank}!",
  "UNDERDOG STORY — {name} IN P{rank}!",
  "{name} HASN'T WON YET — LOOK AT P{rank}!",
  "NO CHECKERED FLAGS — {name} STILL P{rank}!",
  "UNDERDOG ALERT — {name} AT P{rank}!",
  "{name} — ZERO WINS — P{rank} RIGHT NOW!",
  "THE LONG SHOT — {name} IN P{rank}!",
  "WINLESS {name} REFUSES TO FADE!",
  "UNDERDOG MAGIC — {name} P{rank}!",
] as const;

export const ROOKIE_RUN_PHRASES = [
  "{name} ON A ROOKIE RUN — NOW P{rank}!",
  "ROOKIE SURGE — {name} UP TO P{rank}!",
  "{name} ROOKIE MAGIC AT P{rank}!",
  "FRESH FACE FLYING — {name} P{rank}!",
  "ROOKIE RUN ALERT — {name}!",
  "{name} ROOKIE CHARGE TO P{rank}!",
  "THE ROOKIE IS HUNTING — {name} P{rank}!",
  "{name} ON A ROOKIE HEATER — P{rank}!",
  "ROOKIE ENERGY — {name} AT P{rank}!",
  "{name} ROOKIE RUN IN FULL EFFECT!",
  "NEW BLOOD RISING — {name} P{rank}!",
  "ROOKIE ALERT — {name} UP TO P{rank}!",
  "{name} ROOKIE PUSH — NOW P{rank}!",
  "FIRST-TIMER FLYING — {name}!",
  "ROOKIE ON THE MOVE — {name} P{rank}!",
  "{name} ROOKIE SURGE TO P{rank}!",
  "THE ROOKIE WON'T QUIT — P{rank}!",
  "ROOKIE RUN CONFIRMED — {name}!",
  "{name} — ROOKIE — P{rank} AND CLIMBING!",
  "ROOKIE STORYLINE — {name} AT P{rank}!",
] as const;

export const LEAD_PRESSURE_PHRASES = [
  "{name} CLINGING TO THE LEAD — PRESSURE BUILDING!",
  "CAN {name} HOLD ON UP FRONT?!",
  "LEAD UNDER SIEGE — {name} HANGING ON!",
  "THE PACK IS COMING FOR {name}!",
  "PRESSURE ON {name} UP FRONT!",
  "CAN {name} SURVIVE THE HUNT?!",
  "{name} LEADING BUT BARELY MOVING!",
  "THE LEAD IS SLIPPING — {name} STRUGGLING!",
  "UP FRONT: {name} — BUT FOR HOW LONG?!",
  "LEAD PRESSURE MOUNTING ON {name}!",
  "{name} HOLDING ON BY A THREAD!",
  "THE FIELD SMELLS BLOOD — {name} LEADS!",
  "FRAGILE LEAD FOR {name}!",
  "CAN {name} KEEP THE POINT?!",
  "LEAD DEFENSE MODE — {name}!",
  "{name} UNDER HEAVY PRESSURE UP FRONT!",
  "THE HUNT IS ON — {name} LEADS!",
  "LEAD STRESS — {name} UP TOP!",
  "{name} CLINGING TO P1 — DRAMA!",
  "WILL {name} HOLD?! PRESSURE BUILDING!",
] as const;

export const LATE_CLOSE_PHRASES = [
  "{chaser} CLOSING ON {leader} — ONLY {gap} PTS BACK!",
  "IT'S TIGHT! {chaser} HUNTING THE LEAD!",
  "FINAL STRETCH DRAMA — {chaser} IS RIGHT THERE!",
  "CLOSE AT THE TOP — {chaser} {gap} BEHIND {leader}!",
  "{chaser} IS HUNTING {leader} — {gap} PTS!",
  "NAIL-BITER — {chaser} CLOSING FAST!",
  "THE GAP IS {gap} — {chaser} ON {leader}!",
  "FINAL ACT DRAMA — {chaser} VS {leader}!",
  "{chaser} WITHIN {gap} OF {leader}!",
  "IT'S NOT OVER — {chaser} CLOSING!",
  "LATE RACE THRILLER — {gap} PTS SEPARATE THEM!",
  "{chaser} SMELLING AN UPSET ON {leader}!",
  "CLOSING STAGES — {chaser} {gap} BACK!",
  "THE LEAD IS IN PLAY — {chaser} CLOSING!",
  "{chaser} REELING IN {leader} — {gap} PTS!",
  "FINAL STRETCH — {chaser} RIGHT ON {leader}!",
  "DRAMA UP FRONT — ONLY {gap} PTS!",
  "{chaser} KNOCKING ON THE DOOR — {gap} BACK!",
  "TOO CLOSE TO CALL — {chaser} VS {leader}!",
  "LATE-RACE CHASE — {gap} POINT GAP!",
] as const;

export const RACE_START_PHRASES = [
  "8 RACERS ON THE GRID — WE ARE LIVE!",
  "THE GRID IS SET — 8 RACERS — LET'S GO!",
  "GREEN FLAG ENERGY — WE ARE UNDERWAY!",
  "RACE IS LIVE — 8 IN THE FIELD!",
  "FROM THE GRID — WE ARE RACING!",
  "THE FIELD IS LOCKED — RACE ON!",
  "8 RACERS — THE RACE IS ON!",
  "WE ARE LIVE FROM THE GRID!",
  "RACE UNDERWAY — 8 COMPETITORS!",
  "THE SHOW BEGINS — 8 ON TRACK!",
  "GRID CLEAR — RACE IS LIVE!",
  "8 RACERS — AND WE'RE OFF!",
  "THE RACE IS OFFICIALLY LIVE!",
  "FROM THE START — 8 RACERS GO!",
  "LIVE RACING — 8 IN THE FIELD!",
  "THE GRID RELEASES — WE RACE!",
  "8 COMPETITORS — RACE LIVE!",
  "WE HAVE LIFTOFF — RACE ON!",
  "RACE DAY LIVE — 8 RACERS!",
  "THE FIELD IS RACING — WE ARE LIVE!",
] as const;

export const RACE_WON_PHRASES = [
  "{winner} WINS! CHECKERED FLAG!",
  "CHECKERED FLAG FOR {winner}!",
  "{winner} TAKES THE WIN!",
  "VICTORY FOR {winner}!",
  "{winner} — RACE WINNER!",
  "AND THE WIN GOES TO {winner}!",
  "{winner} AT THE LINE — WINNER!",
  "CHECKERED FLAG — {winner}!",
  "{winner} GETS THE W!",
  "WINNER WINNER — {winner}!",
  "{winner} CROSSES FIRST!",
  "THE WIN BELONGS TO {winner}!",
  "{winner} — YOUR RACE WINNER!",
  "CHECKERED FOR {winner}!",
  "{winner} TAKES CHECKERED!",
  "RACE WIN — {winner}!",
  "{winner} STANDS TALL — WINNER!",
  "TOP STEP — {winner} WINS!",
  "{winner} — FLAG FALLS — WIN!",
  "VICTORY LAP FOR {winner}!",
] as const;

export const ELIMINATED_PHRASES = [
  "{last} FINISHES LAST — SENT TO HOLDING!",
  "LAST PLACE — {last} TO HOLDING!",
  "{last} ELIMINATED TO HOLDING!",
  "THE BUBBLE BURSTS — {last} OUT!",
  "{last} FINISHES P8 — HOLDING!",
  "SENT TO HOLDING — {last}!",
  "{last} LAST — ELIMINATED!",
  "P8 FOR {last} — HOLDING LINE!",
  "{last} DROPS TO HOLDING!",
  "LAST ACROSS — {last} ELIMINATED!",
  "HOLDING FOR {last} — LAST PLACE!",
  "{last} — LAST — HOLDING!",
  "THE RACE ENDS IN P8 FOR {last}!",
  "{last} TO THE HOLDING PEN!",
  "ELIMINATED: {last}!",
  "{last} FINISHES LAST TODAY!",
  "LAST PLACE FINISH — {last}!",
  "{last} OUT — HOLDING!",
  "P8 — {last} — HOLDING!",
  "{last} SENT PACKING TO HOLDING!",
] as const;
